-- schema.sql — снимок схемы Supabase (public) проекта Sasha Math
-- =============================================================================
-- Задача T2 (ROADMAP.md): сохранить чертёж базы вне консоли Supabase.
--
-- Снят: 2026-07-10. Способ: read-only запросы к information_schema / pg_catalog
-- (колонки, ограничения, индексы, внешние ключи, определения функций) — см.
-- инструкцию в переписке. Это снимок «как есть», а не первая миграция: дальнейшие
-- изменения БД по-прежнему оформляются файлами database/migrations/NNN_*.sql.
--
-- ВАЖНЫЕ ОСОБЕННОСТИ, зафиксированные на момент снимка:
--   * RLS выключен на всех таблицах, КРОМЕ student_payments (миграция 002).
--     Открытость на запись — сознательно принятый риск, задача T10 в ROADMAP.md.
--   * Ученик во всём проекте адресуется по students.telegram_id, а НЕ по PK id.
--     Все внешние ключи ссылаются на telegram_id (уникальный индекс
--     idx_students_telegram_id обеспечивает эту ссылочную целостность).
--   * students.payment_date оставлена для совместимости, но обнулена и не
--     заполняется — платежи изолированы в student_payments (миграция 002).
--   * Таблица homework_submissions присутствует в БД, но текущими index.html/
--     teacher.html не используется (работа с ДЗ идёт через assignments) —
--     вероятно, наследие ранней версии. Удалять без отдельного решения нельзя.
--
-- Исправлено 2026-07-11: students.id — identity-колонка (generated by default as identity),
-- это не попало в исходный снимок (первоначальный запрос к information_schema не проверял
-- identity-статус колонок). Обнаружено при подготовке dev-копии схемы для форка Bot 2.0 —
-- loadProfile() в index.html вставляет нового ученика без явного id, полагаясь на автогенерацию.
-- =============================================================================

-- --- Таблицы -----------------------------------------------------------------

-- students — родительская таблица для всех внешних ключей.
-- PK = id, но ссылки и вся бизнес-логика идут по telegram_id (см. индекс ниже).
create table public.students (
  id                        bigint  generated by default as identity primary key,
  telegram_id               bigint  not null,
  name                      text,
  rating                    integer default 50,
  huikons                   integer default 0,
  lives                     integer default 3,
  current_streak            integer default 0,
  last_submission_date_msk  date,
  telegram_username         text,
  group_name                text,
  payment_date              date            -- обнулена и не используется (миграция 002)
);

-- Уникальность telegram_id; на этот индекс ссылаются все FK ниже.
create unique index if not exists idx_students_telegram_id
  on public.students (telegram_id);

-- assignments — задание-строка на ученика (ежедневные/еженедельные/индивидуальные).
create table public.assignments (
  id                 uuid         primary key default gen_random_uuid(),
  student_id         bigint       references public.students (telegram_id),
  type               text         not null,
  title              text,
  content_url        text,
  teacher_comment    text,
  day_of_week        integer,
  week_label         text,
  scheduled_date     date,
  activation_status  text         default 'draft',
  status             text         default 'assigned',
  created_at         timestamptz  default now(),
  submitted_at       timestamptz,
  checked_at         timestamptz,
  photo_url          text,
  teacher_feedback   text,
  approval_status    text,
  assigned_group     text,
  -- Поля недельных планов (миграция 011, W01). У legacy-строк все null;
  -- first_submitted_at / revision_* заполняются начиная с W04.
  -- FK plan_item_id -> weekly_plan_items добавляется ниже, после её создания.
  plan_item_id         uuid,
  task_count           integer      check (task_count is null or task_count > 0),
  first_submitted_at   timestamptz,
  revision_deadline_at timestamptz,
  revision_count       integer      check (revision_count is null or revision_count >= 0)
);

-- balance_history — журнал начислений/списаний хуиконов (пишется только из add_huikons).
create table public.balance_history (
  id             uuid         primary key default gen_random_uuid(),
  student_id     bigint       references public.students (telegram_id),
  change_amount  integer      not null,
  reason         text         not null,
  created_at     timestamptz  default now()
);

-- homework_submissions — НАСЛЕДИЕ, текущим кодом не используется (см. шапку файла).
create table public.homework_submissions (
  id               uuid         primary key default gen_random_uuid(),
  student_id       bigint       references public.students (telegram_id),
  variant_number   integer      not null,
  photo_url        text         not null,
  status           text         not null default 'pending',
  teacher_comment  text,
  created_at       timestamptz  default now(),
  checked_at       timestamptz
);

-- mock_exam_results — результаты пробников; upsert идемпотентен по (student_id, exam_name).
create table public.mock_exam_results (
  id          uuid         primary key default gen_random_uuid(),
  student_id  bigint       not null references public.students (telegram_id),
  exam_name   text         not null,
  score       text,
  updated_at  timestamptz  not null default now(),
  created_at  timestamptz  not null default now(),
  exam_date   date,
  unique (student_id, exam_name)
);

-- parent_links — привязка родителя к ученику; upsert идемпотентен по (parent_telegram_id, student_id).
create table public.parent_links (
  id                  uuid         primary key default gen_random_uuid(),
  parent_telegram_id  bigint       not null,
  student_id          bigint       not null references public.students (telegram_id),
  linked_at           timestamptz  not null default now(),
  unique (parent_telegram_id, student_id)
);

-- student_payments — платёжные снимки, изолированы от публичного чтения (миграция 002).
-- Без FK на students (историческое решение миграции 002).
create table public.student_payments (
  student_id    bigint  primary key,
  payment_date  date
);

alter table public.student_payments enable row level security;
-- RLS без единой policy = доступ только у service_role (Apps Script);
-- anon-ключ (index.html/teacher.html/боты) платежи не читает (миграция 002).

-- bot_notification_state — персистентная дата последней рассылки main.py (миграция 004).
-- Переживает передеплой/рестарт процесса — без неё "уже отправлено сегодня" терялось при
-- каждом рестарте после времени срабатывания, и рассылка уходила повторно.
create table public.bot_notification_state (
  notification_key  text  primary key,
  last_sent_date    date
);

-- --- Геймификация Bot 2.0 (миграция 005, задача G3) ---------------------------
-- students.rating = очки ТЕКУЩЕГО сезона (обнуляется при закрытии сезона, G7);
-- обоснование выбора хранения — в шапке миграции 005. Поле не переименовывается.

-- seasons — один ряд на сезон; id и есть «Сезон №N» в UI. end_date is null = сезон идёт.
create table public.seasons (
  id          bigint       generated by default as identity primary key,
  start_date  date         not null,
  end_date    date,                              -- null, пока сезон не закрыт
  created_at  timestamptz  not null default now()
);

-- Открытым может быть только один сезон одновременно.
create unique index if not exists idx_seasons_one_active
  on public.seasons ((true)) where end_date is null;

-- season_results — архив: итоговые очки и место ученика в закрытом сезоне.
-- Пишется один раз при закрытии сезона (G7), дальше только читается.
create table public.season_results (
  id          uuid         primary key default gen_random_uuid(),
  season_id   bigint       not null references public.seasons (id),
  student_id  bigint       not null references public.students (telegram_id),
  points      integer      not null,
  place       integer      not null,
  created_at  timestamptz  not null default now(),
  unique (season_id, student_id)
);

-- student_achievements — выданные достижения; строка = достижение получено, она же
-- флаг «право купить косметику» (этап 2). Вехи стрика и дисциплинарные достижения —
-- одно событие с одним начислением (SPEC_STAGE1.md, раздел 6). Идемпотентная выдача:
-- insert ... on conflict do nothing, бублики начислять только при реальной вставке.
create table public.student_achievements (
  id                uuid         primary key default gen_random_uuid(),
  student_id        bigint       not null references public.students (telegram_id),
  achievement_code  text         not null,
  unlocked_at       timestamptz  not null default now(),
  unique (student_id, achievement_code)
);

-- student_items — инвентарь; первый item_code — 'streak_shield' (щит стрика).
-- Лимит запаса (7 с миграции 012, было 2) — в RPC покупки, не в схеме.
create table public.student_items (
  id          uuid         primary key default gen_random_uuid(),
  student_id  bigint       not null references public.students (telegram_id),
  item_code   text         not null,
  quantity    integer      not null default 0 check (quantity >= 0),
  updated_at  timestamptz  not null default now(),
  created_at  timestamptz  not null default now(),
  unique (student_id, item_code)
);

-- streak_shield_uses — какие пропущенные дни покрыты щитом стрика (миграция 007, задача G9).
-- Нужна для идемпотентного сшивания разрывов при пересчёте цепочки с нуля (см. шапку 007).
create table public.streak_shield_uses (
  id           uuid         primary key default gen_random_uuid(),
  student_id   bigint       not null references public.students (telegram_id),
  bridged_date date         not null,
  created_at   timestamptz  not null default now(),
  unique (student_id, bridged_date)
);

create index if not exists idx_streak_shield_uses_student
  on public.streak_shield_uses (student_id);
alter table public.streak_shield_uses disable row level security;  -- как и все таблицы проекта (T10)

-- shop_items — каталог магазина «Бубличная» (миграция 008, задача S1). Полные решения —
-- в шапке миграции 008: buy_item как единая точка покупки (щит — делегированием в
-- buy_streak_shield), ротация через бандлы, автоэкипировка косметики.
create table public.shop_items (
  item_code             text         primary key,
  name                  text         not null,
  item_kind             text         not null check (item_kind in ('cosmetic','shield','service')),
  slot                  text         check (slot in ('name_color','crown','status_emoji','title','frame','background')),
  price                 integer      not null check (price > 0),
  availability          text         not null check (availability in ('always','rotation')),
  rotation_bundle       integer,
  condition_achievement text,
  render_payload        text,
  sort_order            integer      not null default 100,
  active                boolean      not null default true,
  created_at            timestamptz  not null default now(),
  check ((availability = 'rotation') = (rotation_bundle is not null))
);
alter table public.shop_items disable row level security;

-- season_bundles — какой ротационный набор на витрине какого сезона (миграция 008).
-- unique(bundle): использованный набор не возвращается («потом — никогда» для легендарок).
create table public.season_bundles (
  season_id  bigint       primary key references public.seasons (id),
  bundle     integer      not null unique,
  created_at timestamptz  not null default now()
);
alter table public.season_bundles disable row level security;

-- student_equipment — что надето по слотам; variant — выбранный эмодзи статуса (миграция 008).
create table public.student_equipment (
  id          uuid         primary key default gen_random_uuid(),
  student_id  bigint       not null references public.students (telegram_id),
  slot        text         not null,
  item_code   text         not null references public.shop_items (item_code),
  variant     text,
  updated_at  timestamptz  not null default now(),
  created_at  timestamptz  not null default now(),
  unique (student_id, slot)
);
create index if not exists idx_student_equipment_student
  on public.student_equipment (student_id);
alter table public.student_equipment disable row level security;

-- student_custom_titles — одно оплаченное право/текущая заявка на персональный титул
-- (миграция 010, S8). До approved текст не попадает в student_items/student_equipment;
-- после approved одобренный текст хранится в student_equipment.variant.
create table public.student_custom_titles (
  student_id       bigint       primary key references public.students (telegram_id),
  title_text       text         not null,
  status           text         not null check (status in ('pending', 'rejected', 'approved')),
  teacher_comment  text,
  purchased_at     timestamptz  not null default now(),
  submitted_at     timestamptz  not null default now(),
  reviewed_at      timestamptz,
  updated_at       timestamptz  not null default now(),
  check (char_length(title_text) between 3 and 24),
  check (title_text = btrim(title_text)),
  check (title_text !~ '[[:cntrl:]]'),
  check (teacher_comment is null or char_length(btrim(teacher_comment)) between 3 and 200),
  check (
    (status = 'pending'  and teacher_comment is null     and reviewed_at is null) or
    (status = 'rejected' and teacher_comment is not null and reviewed_at is not null) or
    (status = 'approved' and teacher_comment is null     and reviewed_at is not null)
  )
);
alter table public.student_custom_titles disable row level security;

-- student_showcase — витрина профиля: 3 слота, предмет ИЛИ достижение (миграция 009, S7).
-- Отдельная таблица, не расширение student_equipment: item_code там жёстко ссылается на
-- shop_items (FK), а витрина должна показывать ещё и student_achievements.achievement_code —
-- другое пространство кодов, одна FK-колонка не может ссылаться на две таблицы разом.
create table public.student_showcase (
  id          uuid         primary key default gen_random_uuid(),
  student_id  bigint       not null references public.students (telegram_id),
  position    smallint     not null check (position between 1 and 3),
  kind        text         not null check (kind in ('item', 'achievement')),
  ref_code    text         not null,
  updated_at  timestamptz  not null default now(),
  created_at  timestamptz  not null default now(),
  unique (student_id, position)
);
alter table public.student_showcase disable row level security;

-- --- Недельные планы Stage 2.5 (миграция 011, W01) ----------------------------
-- Шаблон плана недели, отделённый от персонального прогресса. assignments
-- остаётся персональным фактом задания и владельцем статуса сдачи; строки
-- материализуются серверной sync_student_week_assignments (см. функции ниже).
-- Полные решения и мотивация — в шапке миграции 011.

-- weekly_plans — одна строка = один план одной аудитории на одну неделю.
create table public.weekly_plans (
  id            uuid         primary key default gen_random_uuid(),
  week_start    date         not null check (extract(isodow from week_start) = 1),
  audience_type text         not null check (audience_type in ('all', 'group')),
  group_name    text,
  status        text         not null default 'published'
                             check (status in ('published', 'cancelled')),
  created_at    timestamptz  not null default now(),
  updated_at    timestamptz  not null default now(),
  check ((audience_type = 'all'   and group_name is null)
      or (audience_type = 'group' and group_name is not null and btrim(group_name) <> ''))
);

-- Одна АКТИВНАЯ строка на (week_start, audience_type, group_name);
-- отменённые планы — история, переизданию не мешают.
create unique index if not exists uq_weekly_plans_active_all
  on public.weekly_plans (week_start)
  where status = 'published' and audience_type = 'all';
create unique index if not exists uq_weekly_plans_active_group
  on public.weekly_plans (week_start, group_name)
  where status = 'published' and audience_type = 'group';

alter table public.weekly_plans disable row level security;

-- weekly_plan_items — слот плана: один daily на номер дня и один weekly.
-- Удалённый из плана item получает active = false, физически не уничтожается.
create table public.weekly_plan_items (
  id              uuid         primary key default gen_random_uuid(),
  plan_id         uuid         not null references public.weekly_plans (id),
  type            text         not null check (type in ('daily', 'weekly')),
  day_of_week     integer,
  title           text         not null check (btrim(title) <> ''),
  content_url     text         not null check (btrim(content_url) <> ''),
  teacher_comment text,
  task_count      integer      check (task_count is null or task_count > 0),
  active          boolean      not null default true,
  created_at      timestamptz  not null default now(),
  updated_at      timestamptz  not null default now(),
  check ((type = 'daily'  and day_of_week between 1 and 7)
      or (type = 'weekly' and day_of_week is null))
);

create unique index if not exists uq_weekly_plan_items_daily_slot
  on public.weekly_plan_items (plan_id, day_of_week)
  where active and type = 'daily';
create unique index if not exists uq_weekly_plan_items_weekly_slot
  on public.weekly_plan_items (plan_id)
  where active and type = 'weekly';

alter table public.weekly_plan_items disable row level security;

-- FK, отложенный из create table assignments (weekly_plan_items создаётся позже).
alter table public.assignments
  add constraint assignments_plan_item_id_fkey
  foreign key (plan_item_id) references public.weekly_plan_items (id);

-- Частичные уникальности плановых строк assignments (миграция 011):
-- legacy-строки (plan_item_id = null) под них не попадают.
create unique index if not exists uq_assignments_plan_daily
  on public.assignments (student_id, scheduled_date)
  where plan_item_id is not null and type = 'daily';
create unique index if not exists uq_assignments_plan_weekly
  on public.assignments (student_id, week_label)
  where plan_item_id is not null and type = 'weekly';
create unique index if not exists uq_assignments_plan_item
  on public.assignments (student_id, plan_item_id)
  where plan_item_id is not null;
create index if not exists idx_assignments_plan_item
  on public.assignments (plan_item_id)
  where plan_item_id is not null;

-- --- Недельный результат и щиты недели (миграция 012, W04) ---------------------
-- Серверный источник истины недельного итога. Награды здесь НЕ начисляются: finalize считает
-- и сохраняет reward_amount, выплату через add_huikons включает cutover W09. Расписание
-- (pg_cron) тоже включает W09 — 012 только создаёт finalize_due_student_weeks().
-- Полные решения и мотивация — в шапке миграции 012.

-- student_week_results — снимок недельного расчёта: N/A/S/E, статус и итог (SPEC §7.1).
-- Источником реальной работы остаются assignments; строка пересчитывается recalc_student_week
-- до финализации, после — заморожена.
create table public.student_week_results (
  id                    uuid         primary key default gen_random_uuid(),
  student_id            bigint       not null references public.students (telegram_id),
  week_start            date         not null check (extract(isodow from week_start) = 1),
  available_daily_count integer      not null default 0 check (available_daily_count >= 0),  -- N
  approved_daily_count  integer      not null default 0 check (approved_daily_count >= 0),   -- A
  requested_shields     integer      not null default 0 check (requested_shields >= 0),
  shields_used          integer      not null default 0 check (shields_used >= 0),           -- S
  effective_daily_count integer      not null default 0 check (effective_daily_count >= 0),  -- E
  status                text         not null default 'open'
                                     check (status in ('open', 'pending_review', 'awaiting_student', 'finalized', 'neutral')),
  successful            boolean,     -- null у нейтральной недели: она не успешная и не слабая
  reward_amount         integer      check (reward_amount is null or reward_amount >= 0),
  neutral_reason        text,
  finalized_at          timestamptz,
  created_at            timestamptz  not null default now(),
  updated_at            timestamptz  not null default now(),
  unique (student_id, week_start)
);

create index if not exists idx_student_week_results_open
  on public.student_week_results (week_start)
  where status not in ('finalized', 'neutral');

alter table public.student_week_results disable row level security;

-- weekly_shield_uses — резерв щита на КОНКРЕТНУЮ ежедневку (SPEC §7.2). Отдельная таблица от
-- streak_shield_uses (007): та закрывает разрывы старого processStreak(), эта резервирует щит
-- под недельный результат. on delete cascade — потому что sync_student_week_assignments (011)
-- удаляет неначатые плановые строки, а резерв ставится именно на неначатую ежедневку.
create table public.weekly_shield_uses (
  id            uuid         primary key default gen_random_uuid(),
  student_id    bigint       not null references public.students (telegram_id),
  week_start    date         not null check (extract(isodow from week_start) = 1),
  assignment_id uuid         not null references public.assignments (id) on delete cascade,
  status        text         not null check (status in ('requested', 'consumed', 'cancelled')),
  requested_at  timestamptz  not null default now(),
  consumed_at   timestamptz,
  cancelled_at  timestamptz,
  created_at    timestamptz  not null default now(),
  updated_at    timestamptz  not null default now()
);

-- Активный резерв уникален для assignment; списанный — тоже (нельзя списать дважды).
create unique index if not exists uq_weekly_shield_requested
  on public.weekly_shield_uses (assignment_id) where status = 'requested';
create unique index if not exists uq_weekly_shield_consumed
  on public.weekly_shield_uses (assignment_id) where status = 'consumed';
create index if not exists idx_weekly_shield_student_week
  on public.weekly_shield_uses (student_id, week_start);

alter table public.weekly_shield_uses disable row level security;

-- --- Еженедельные пробники Stage 2.5 (миграция 016, P02A) ----------------------
-- Канонический результат недельного пробника (score integer 0-100) отдельно от legacy
-- mock_exam_results (score text не трогается). Награда идемпотентна: бублики pay-once через
-- явный ledger, season points — детерминированная компенсирующая дельта. Запись только через
-- RPC record_weekly_mock_exam (см. функции ниже). Полная мотивация — в шапке миграции 016.
create table public.weekly_mock_exams (
  id                     uuid         primary key default gen_random_uuid(),
  student_id             bigint       not null references public.students (telegram_id),
  week_start             date         not null check (extract(isodow from week_start) = 1),
  score                  integer      not null check (score between 0 and 100),
  season_points_awarded  integer      not null default 0,  -- сколько season points уже дал этот результат (для дельты при edit)
  created_at             timestamptz  not null default now(),
  updated_at             timestamptz  not null default now(),
  unique (student_id, week_start)
);
create index if not exists idx_weekly_mock_exams_student
  on public.weekly_mock_exams (student_id, week_start);
alter table public.weekly_mock_exams disable row level security;

-- Явный ledger бубличных наград пробника: уникальность (student_id, week_start, reward_kind)
-- гарантирует одну базу и один рекорд на неделю (SPEC §9).
create table public.mock_exam_reward_log (
  id           uuid         primary key default gen_random_uuid(),
  student_id   bigint       not null references public.students (telegram_id),
  week_start   date         not null,
  reward_kind  text         not null check (reward_kind in ('base', 'record')),
  bubliks      integer      not null check (bubliks > 0),
  awarded_at   timestamptz  not null default now(),
  unique (student_id, week_start, reward_kind)
);
create index if not exists idx_mock_exam_reward_log_month
  on public.mock_exam_reward_log (student_id, reward_kind, awarded_at);
alter table public.mock_exam_reward_log disable row level security;

-- --- Индексы (кроме автоматических для PK/UNIQUE и idx_students_telegram_id выше) -----

create index if not exists idx_assignments_activation
  on public.assignments (activation_status, scheduled_date);
create index if not exists idx_assignments_student_status
  on public.assignments (student_id, status);
create index if not exists idx_assignments_week
  on public.assignments (week_label, type);

-- История сезонов конкретного ученика («Сезон №N» в архиве профиля, миграция 005).
create index if not exists idx_season_results_student
  on public.season_results (student_id);

-- --- Функции -----------------------------------------------------------------

-- add_huikons — атомарное начисление/списание хуиконов (миграция 001, задача T5).
CREATE OR REPLACE FUNCTION public.add_huikons(p_student_id bigint, p_amount integer, p_reason text)
 RETURNS TABLE(actual_change integer, new_balance integer)
 LANGUAGE plpgsql
AS $function$
declare
  v_old_balance int;
  v_new_balance int;
begin
  select huikons into v_old_balance
    from students
    where telegram_id = p_student_id
    for update;

  if v_old_balance is null then
    raise exception 'Student % not found', p_student_id;
  end if;

  v_new_balance := greatest(0, v_old_balance + p_amount);

  update students set huikons = v_new_balance where telegram_id = p_student_id;

  insert into balance_history (student_id, change_amount, reason)
    values (p_student_id, v_new_balance - v_old_balance, p_reason);

  return query select (v_new_balance - v_old_balance), v_new_balance;
end;
$function$;


-- get_student_progress — сводка выданных/выполненных заданий по типам (используется родительским ботом).
CREATE OR REPLACE FUNCTION public.get_student_progress(p_student_id bigint)
 RETURNS TABLE(type text, issued bigint, completed bigint)
 LANGUAGE sql
 STABLE
AS $function$
  select
    a.type,
    count(*) filter (where a.activation_status = 'active') as issued,
    count(*) filter (where a.status = 'checked' and a.approval_status = 'approved') as completed
  from assignments a
  where a.student_id = p_student_id
  group by a.type;
$function$;

-- close_season — закрытие сезона одной транзакцией (миграция 006, задача G8):
-- архив итогов в season_results (места по rank(), равные очки = одно место),
-- награды топ-3 с ненулевыми очками (100/60/30, GAME_DESIGN.md §5) через add_huikons
-- (reason='season_place_N'), обнуление rating, end_date у закрытого сезона, открытие
-- следующего. Сезон, открытый сегодня, закрыть нельзя (защита от двойного клика).
-- Полная мотивация решений — в шапке миграции 006.
CREATE OR REPLACE FUNCTION public.close_season()
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
  v_season_id bigint;
  v_start_date date;
  v_today date := (now() at time zone 'Europe/Moscow')::date;
  v_archived integer;
  v_awarded integer := 0;
  v_reward integer;
  r record;
begin
  select id, start_date into v_season_id, v_start_date
    from seasons
    where end_date is null
    order by id desc
    limit 1
    for update;

  if v_season_id is null then
    raise exception 'Нет открытого сезона';
  end if;

  if v_start_date >= v_today then
    raise exception 'Сезон №% открыт сегодня — закрывать можно не раньше следующего дня', v_season_id;
  end if;

  -- Блокируем учеников до снимка очков (гонка с add_season_points, см. миграцию 006).
  perform 1 from students for update;

  insert into season_results (season_id, student_id, points, place)
  select v_season_id, s.telegram_id, s.rating,
         rank() over (order by s.rating desc)
    from students s;
  get diagnostics v_archived = row_count;

  for r in
    select student_id, place
      from season_results
      where season_id = v_season_id and place <= 3 and points > 0
  loop
    v_reward := case r.place when 1 then 100 when 2 then 60 else 30 end;
    perform add_huikons(r.student_id, v_reward, 'season_place_' || r.place);
    v_awarded := v_awarded + 1;
  end loop;

  update students set rating = 0 where rating <> 0;

  update seasons set end_date = v_today where id = v_season_id;

  insert into seasons (start_date) values (v_today);

  return json_build_object(
    'season_id', v_season_id,
    'archived', v_archived,
    'awarded', v_awarded
  );
end;
$function$;

-- buy_streak_shield — атомарная покупка щита (миграция 007, задача G9): лимит и цена через
-- add_huikons (reason='buy_streak_shield'), инкремент инвентаря. Мотивация атомарности и
-- блокировок — в шапке миграции 007. Цена 40→90 и лимит 2→7 подняты миграцией 012 (W04,
-- SPEC_STAGE2_5 §7.2 / ECONOMY_V2 §6) по отдельному решению пользователя: щит — часть
-- недельной модели, а не общий пересчёт магазина. Существующие щиты сохранены как есть.
CREATE OR REPLACE FUNCTION public.buy_streak_shield(p_student_id bigint)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
  v_price  integer := 90;
  v_max    integer := 7;
  v_qty    integer;
  v_balance integer;
  v_new_balance integer;
begin
  select quantity into v_qty
    from student_items
    where student_id = p_student_id and item_code = 'streak_shield'
    for update;
  if v_qty is null then v_qty := 0; end if;

  if v_qty >= v_max then
    raise exception 'Лимит: не больше % щитов в запасе', v_max;
  end if;

  select huikons into v_balance
    from students
    where telegram_id = p_student_id
    for update;
  if v_balance is null then
    raise exception 'Ученик % не найден', p_student_id;
  end if;
  if v_balance < v_price then
    raise exception 'Недостаточно бубликов: нужно %, есть %', v_price, v_balance;
  end if;

  select new_balance into v_new_balance
    from add_huikons(p_student_id, -v_price, 'buy_streak_shield');

  insert into student_items (student_id, item_code, quantity)
    values (p_student_id, 'streak_shield', 1)
    on conflict (student_id, item_code)
    do update set quantity = student_items.quantity + 1, updated_at = now();

  select quantity into v_qty
    from student_items
    where student_id = p_student_id and item_code = 'streak_shield';

  return json_build_object('quantity', v_qty, 'balance', v_new_balance);
end;
$function$;

-- consume_streak_shield — атомарно покрыть один пропущенный день щитом (миграция 007, G9).
-- Идемпотентно: true если день покрыт (сейчас или ранее), false если щита нет.
CREATE OR REPLACE FUNCTION public.consume_streak_shield(p_student_id bigint, p_bridged_date date)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
declare
  v_qty integer;
begin
  if exists (select 1 from streak_shield_uses
               where student_id = p_student_id and bridged_date = p_bridged_date) then
    return true;
  end if;

  select quantity into v_qty
    from student_items
    where student_id = p_student_id and item_code = 'streak_shield'
    for update;

  if v_qty is null or v_qty <= 0 then
    return false;
  end if;

  insert into streak_shield_uses (student_id, bridged_date)
    values (p_student_id, p_bridged_date)
    on conflict (student_id, bridged_date) do nothing;

  update student_items
    set quantity = quantity - 1, updated_at = now()
    where student_id = p_student_id and item_code = 'streak_shield';

  return true;
end;
$function$;

-- ensure_season_rotation / buy_item / equip_item — RPC магазина (миграция 008, задача S1;
-- buy_item/equip_item точечно расширены миграцией 010 для персонального титула S8).
-- Тела и мотивация решений — в миграции 008 (ленивое назначение бандла открытому сезону;
-- единая покупка с делегированием щита, явной проверкой баланса, gate по достижению и
-- автоэкипировкой; бесплатное переодевание купленного). Сид каталога — тоже в миграции 008.
CREATE OR REPLACE FUNCTION public.ensure_season_rotation()
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
declare
  v_season bigint;
  v_bundle integer;
begin
  select id into v_season from seasons where end_date is null order by id desc limit 1;
  if v_season is null then
    return null;
  end if;

  select bundle into v_bundle from season_bundles where season_id = v_season;
  if v_bundle is not null then
    return v_bundle;
  end if;

  select min(rotation_bundle) into v_bundle
    from shop_items
    where rotation_bundle is not null
      and active
      and rotation_bundle not in (select bundle from season_bundles);
  if v_bundle is null then
    return null;
  end if;

  insert into season_bundles (season_id, bundle)
    values (v_season, v_bundle)
    on conflict (season_id) do nothing;

  select bundle into v_bundle from season_bundles where season_id = v_season;
  return v_bundle;
end;
$function$;

-- submit_custom_title / review_custom_title — покупка права и модерация персонального
-- титула (миграция 010, S8). Первая отправка списывает цену через add_huikons; retry после
-- rejected бесплатен; только approved создаёт владение и публичную экипировку.
CREATE OR REPLACE FUNCTION public.submit_custom_title(p_student_id bigint, p_title_text text)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
  v_title       text;
  v_status      text;
  v_price       integer;
  v_balance     integer;
  v_new_balance integer;
begin
  if p_title_text is null or p_title_text ~ '[[:cntrl:]]' then
    raise exception 'Титул должен быть одной строкой без управляющих символов';
  end if;

  v_title := regexp_replace(btrim(p_title_text), '[[:space:]]+', ' ', 'g');
  if char_length(v_title) < 3 or char_length(v_title) > 24 then
    raise exception 'Длина титула должна быть от 3 до 24 символов';
  end if;

  select huikons into v_balance
    from public.students
    where telegram_id = p_student_id
    for update;
  if v_balance is null then
    raise exception 'Ученик % не найден', p_student_id;
  end if;

  select status into v_status
    from public.student_custom_titles
    where student_id = p_student_id
    for update;

  if v_status = 'pending' then
    raise exception 'Титул уже находится на модерации';
  elsif v_status = 'approved' then
    raise exception 'Персональный титул уже одобрен и не может быть изменён';
  elsif v_status = 'rejected' then
    update public.student_custom_titles
      set title_text = v_title,
          status = 'pending',
          teacher_comment = null,
          submitted_at = now(),
          reviewed_at = null,
          updated_at = now()
      where student_id = p_student_id;

    return json_build_object('status', 'pending', 'balance', v_balance, 'charged', 0);
  end if;

  select price into v_price
    from public.shop_items
    where item_code = 'title_custom' and active;
  if v_price is null then
    raise exception 'Персональный титул сейчас недоступен';
  end if;
  if v_balance < v_price then
    raise exception 'Недостаточно бубликов: нужно %, есть %', v_price, v_balance;
  end if;

  select new_balance into v_new_balance
    from public.add_huikons(p_student_id, -v_price, 'buy_title_custom');

  insert into public.student_custom_titles (student_id, title_text, status)
    values (p_student_id, v_title, 'pending');

  return json_build_object(
    'status', 'pending',
    'balance', v_new_balance,
    'charged', v_price
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.review_custom_title(
  p_student_id bigint,
  p_decision text,
  p_teacher_comment text DEFAULT null
)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
  v_title   text;
  v_status  text;
  v_comment text;
begin
  if p_decision is null or p_decision not in ('approved', 'rejected') then
    raise exception 'Решение должно быть approved или rejected';
  end if;

  select title_text, status into v_title, v_status
    from public.student_custom_titles
    where student_id = p_student_id
    for update;
  if v_status is null then
    raise exception 'Заявка ученика % не найдена', p_student_id;
  end if;
  if v_status <> 'pending' then
    raise exception 'Заявка уже рассмотрена: %', v_status;
  end if;

  if p_decision = 'rejected' then
    if p_teacher_comment is null or p_teacher_comment ~ '[[:cntrl:]]' then
      raise exception 'При отказе нужна причина одной строкой';
    end if;
    v_comment := regexp_replace(btrim(p_teacher_comment), '[[:space:]]+', ' ', 'g');
    if char_length(v_comment) < 3 or char_length(v_comment) > 200 then
      raise exception 'Причина отказа должна быть от 3 до 200 символов';
    end if;

    update public.student_custom_titles
      set status = 'rejected',
          teacher_comment = v_comment,
          reviewed_at = now(),
          updated_at = now()
      where student_id = p_student_id;

    return json_build_object('status', 'rejected');
  end if;

  update public.student_custom_titles
    set status = 'approved',
        teacher_comment = null,
        reviewed_at = now(),
        updated_at = now()
    where student_id = p_student_id;

  insert into public.student_items (student_id, item_code, quantity)
    values (p_student_id, 'title_custom', 1)
    on conflict (student_id, item_code)
    do update set quantity = greatest(student_items.quantity, 1), updated_at = now();

  insert into public.student_equipment (student_id, slot, item_code, variant)
    values (p_student_id, 'title', 'title_custom', v_title)
    on conflict (student_id, slot)
    do update set item_code = excluded.item_code,
                  variant = excluded.variant,
                  updated_at = now();

  return json_build_object('status', 'approved', 'title_text', v_title);
end;
$function$;

CREATE OR REPLACE FUNCTION public.buy_item(p_student_id bigint, p_item_code text, p_variant text DEFAULT null)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
  v_item     shop_items%rowtype;
  v_bundle   integer;
  v_balance  integer;
  v_new_balance integer;
begin
  select * into v_item from shop_items where item_code = p_item_code and active;
  if v_item.item_code is null then
    raise exception 'Товар % не найден или снят с продажи', p_item_code;
  end if;

  if p_item_code = 'title_custom' then
    raise exception 'Персональный титул покупается только через отправку на модерацию';
  end if;

  if v_item.item_kind = 'shield' then
    return buy_streak_shield(p_student_id);
  end if;

  if v_item.availability = 'rotation' then
    v_bundle := ensure_season_rotation();
    if v_bundle is null or v_bundle <> v_item.rotation_bundle then
      raise exception 'Товар «%» сейчас не на витрине', v_item.name;
    end if;
  end if;

  if v_item.condition_achievement is not null then
    if not exists (select 1 from student_achievements
                     where student_id = p_student_id
                       and achievement_code = v_item.condition_achievement) then
      raise exception 'Для покупки «%» нужно достижение', v_item.name;
    end if;
  end if;

  if v_item.item_kind = 'service' then
    if p_variant is null or position(p_variant in coalesce(v_item.render_payload, '')) = 0 then
      raise exception 'Недопустимый вариант для «%»', v_item.name;
    end if;
  end if;

  if v_item.item_kind = 'cosmetic' then
    if exists (select 1 from student_items
                 where student_id = p_student_id and item_code = p_item_code) then
      raise exception 'Уже куплено';
    end if;
  end if;

  select huikons into v_balance from students where telegram_id = p_student_id for update;
  if v_balance is null then
    raise exception 'Ученик % не найден', p_student_id;
  end if;
  if v_balance < v_item.price then
    raise exception 'Недостаточно бубликов: нужно %, есть %', v_item.price, v_balance;
  end if;

  select new_balance into v_new_balance
    from add_huikons(p_student_id, -v_item.price, 'buy_' || p_item_code);

  if v_item.item_kind = 'cosmetic' then
    insert into student_items (student_id, item_code, quantity)
      values (p_student_id, p_item_code, 1);
    insert into student_equipment (student_id, slot, item_code)
      values (p_student_id, v_item.slot, p_item_code)
      on conflict (student_id, slot)
      do update set item_code = excluded.item_code, variant = null, updated_at = now();
  elsif v_item.item_kind = 'service' then
    insert into student_equipment (student_id, slot, item_code, variant)
      values (p_student_id, v_item.slot, p_item_code, p_variant)
      on conflict (student_id, slot)
      do update set item_code = excluded.item_code, variant = excluded.variant, updated_at = now();
  end if;

  return json_build_object('item_code', p_item_code, 'balance', v_new_balance);
end;
$function$;

CREATE OR REPLACE FUNCTION public.equip_item(p_student_id bigint, p_slot text, p_item_code text DEFAULT null)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
  v_slot         text;
  v_custom_title text;
begin
  if p_item_code is null then
    delete from student_equipment where student_id = p_student_id and slot = p_slot;
    return;
  end if;

  if p_slot = 'status_emoji' then
    raise exception 'Эмодзи-статус меняется только покупкой смены';
  end if;

  select slot into v_slot from shop_items where item_code = p_item_code and active;
  if v_slot is null or v_slot <> p_slot then
    raise exception 'Товар % не подходит слоту %', p_item_code, p_slot;
  end if;

  if not exists (select 1 from student_items
                   where student_id = p_student_id and item_code = p_item_code) then
    raise exception 'Сначала нужно купить этот предмет';
  end if;

  if p_item_code = 'title_custom' then
    select title_text into v_custom_title
      from student_custom_titles
      where student_id = p_student_id and status = 'approved';
    if v_custom_title is null then
      raise exception 'Персональный титул ещё не одобрен';
    end if;

    insert into student_equipment (student_id, slot, item_code, variant)
      values (p_student_id, p_slot, p_item_code, v_custom_title)
      on conflict (student_id, slot)
      do update set item_code = excluded.item_code,
                    variant = excluded.variant,
                    updated_at = now();
    return;
  end if;

  insert into student_equipment (student_id, slot, item_code)
    values (p_student_id, p_slot, p_item_code)
    on conflict (student_id, slot)
    do update set item_code = excluded.item_code, variant = null, updated_at = now();
end;
$function$;

-- set_showcase — поставить/снять предмет витрины профиля (миграция 009, S7). p_ref_code=null
-- снимает слот; иначе проверяет владение (student_items) или получение (student_achievements)
-- в зависимости от p_kind перед апсертом. Мотивация отдельной таблицы — в шапке миграции 009.
CREATE OR REPLACE FUNCTION public.set_showcase(p_student_id bigint, p_position smallint, p_kind text, p_ref_code text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin
  if p_ref_code is null then
    delete from student_showcase where student_id = p_student_id and position = p_position;
    return;
  end if;

  if p_kind = 'item' then
    if not exists (select 1 from student_items where student_id = p_student_id and item_code = p_ref_code) then
      raise exception 'Предмет % не куплен', p_ref_code;
    end if;
  elsif p_kind = 'achievement' then
    if not exists (select 1 from student_achievements where student_id = p_student_id and achievement_code = p_ref_code) then
      raise exception 'Достижение % не получено', p_ref_code;
    end if;
  else
    raise exception 'Неизвестный тип витрины: %', p_kind;
  end if;

  insert into student_showcase (student_id, position, kind, ref_code)
    values (p_student_id, p_position, p_kind, p_ref_code)
    on conflict (student_id, position)
    do update set kind = excluded.kind, ref_code = excluded.ref_code, updated_at = now();
end;
$function$;

-- add_season_points — атомарное начисление очков сезона (миграция 005, задача G3).
-- PostgREST не умеет относительный update, поэтому rating = rating + N делается здесь.
-- Очки сезона — отдельная валюта от бубликов: в balance_history НЕ пишет.
CREATE OR REPLACE FUNCTION public.add_season_points(p_student_id bigint, p_amount integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
declare
  v_new integer;
begin
  update students
    set rating = greatest(0, rating + p_amount)
    where telegram_id = p_student_id
    returning rating into v_new;

  if v_new is null then
    raise exception 'Student % not found', p_student_id;
  end if;

  return v_new;
end;
$function$;

-- sync_student_week_assignments — единственный алгоритм материализации недельных
-- планов в персональные assignments (миграция 011, W01; SPEC_STAGE2_5.md §5).
-- Вызывается publish_weekly_plan / cancel_weekly_plan и триггером students.
-- p_replace_from — с какой scheduled_date можно заменять/удалять НЕНАЧАТЫЕ
-- daily-строки: публикация/отмена передают завтра («только будущие», §5.2),
-- смена группы/новый ученик — сегодня (§5.3–5.4; null = сегодня). Вставка
-- отсутствующих строк — всегда от сегодня. weekly меняется, пока строка не
-- начата, без гейта по дате (§5.5). Полная мотивация — в шапке миграции 011.
CREATE OR REPLACE FUNCTION public.sync_student_week_assignments(
  p_student_id   bigint,
  p_week_start   date,
  p_replace_from date DEFAULT null
)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
  v_today        date := (now() at time zone 'Europe/Moscow')::date;
  v_week_label   text;
  v_insert_from  date;
  v_replace_from date;
  v_group        text;
  v_eff_ids      uuid[] := '{}';
  v_slot_date    date;
  v_existing     public.assignments%rowtype;
  v_started      boolean;
  r              record;
begin
  if p_week_start is null or extract(isodow from p_week_start) <> 1 then
    raise exception 'week_start % — не понедельник', p_week_start;
  end if;

  -- Прошедшие недели не материализуются и не переписываются (SPEC §5.3).
  if p_week_start + 6 < v_today then
    return;
  end if;

  select group_name into v_group
    from public.students
    where telegram_id = p_student_id;
  if not found then
    raise exception 'Ученик % не найден', p_student_id;
  end if;

  v_week_label   := to_char(p_week_start, 'YYYY-MM-DD');
  v_insert_from  := greatest(p_week_start, v_today);
  v_replace_from := greatest(p_week_start, coalesce(p_replace_from, v_today));

  -- Эффективный item на каждый слот: item точной группы ученика,
  -- иначе item плана all, иначе слота нет (SPEC §5.1, приоритет по слоту).
  for r in
    with candidate_items as (
      select i.id, i.type, i.day_of_week, i.title, i.content_url,
             i.teacher_comment, i.task_count, p.audience_type, p.group_name
        from public.weekly_plan_items i
        join public.weekly_plans p on p.id = i.plan_id
       where p.week_start = p_week_start
         and p.status = 'published'
         and i.active
         and (p.audience_type = 'all'
              or (v_group is not null
                  and p.audience_type = 'group'
                  and p.group_name = v_group))
    )
    select distinct on (c.type, coalesce(c.day_of_week, 0))
           c.id as item_id, c.type, c.day_of_week, c.title, c.content_url,
           c.teacher_comment, c.task_count,
           case when c.audience_type = 'group' then c.group_name
                else 'Все ученики' end as aud_label
      from candidate_items c
     order by c.type, coalesce(c.day_of_week, 0),
              (c.audience_type = 'group') desc
  loop
    v_eff_ids := v_eff_ids || r.item_id;

    if r.type = 'daily' then
      v_slot_date := p_week_start + (r.day_of_week - 1);
    else
      v_slot_date := p_week_start;
    end if;

    -- Существующая плановая строка слота (максимум одна — частичные уникальности).
    select a.* into v_existing
      from public.assignments a
     where a.student_id = p_student_id
       and a.plan_item_id is not null
       and ((r.type = 'daily'  and a.type = 'daily'  and a.scheduled_date = v_slot_date)
         or (r.type = 'weekly' and a.type = 'weekly' and a.week_label = v_week_label))
     limit 1
     for update;

    if found then
      v_started := v_existing.status is distinct from 'assigned'
                or v_existing.submitted_at is not null
                or v_existing.photo_url is not null
                or v_existing.first_submitted_at is not null;

      if v_started then
        continue;  -- начатая история неприкосновенна (SPEC §5.4)
      end if;

      if r.type = 'daily' and v_slot_date < v_replace_from then
        continue;  -- замена daily разрешена только с v_replace_from
      end if;

      if v_existing.plan_item_id       is distinct from r.item_id
         or v_existing.title           is distinct from r.title
         or v_existing.content_url     is distinct from r.content_url
         or v_existing.teacher_comment is distinct from r.teacher_comment
         or v_existing.task_count      is distinct from r.task_count
         or v_existing.assigned_group  is distinct from r.aud_label then
        update public.assignments
           set plan_item_id    = r.item_id,
               title           = r.title,
               content_url     = r.content_url,
               teacher_comment = r.teacher_comment,
               task_count      = r.task_count,
               assigned_group  = r.aud_label
         where id = v_existing.id;
      end if;
    else
      if r.type = 'daily' and v_slot_date < v_insert_from then
        continue;  -- прошлые дни не создаются и не входят в N (SPEC §5.3)
      end if;

      insert into public.assignments
        (student_id, type, title, content_url, teacher_comment, day_of_week,
         week_label, scheduled_date, activation_status, status, assigned_group,
         plan_item_id, task_count)
      values
        (p_student_id, r.type, r.title, r.content_url, r.teacher_comment,
         r.day_of_week, v_week_label, v_slot_date, 'scheduled', 'assigned',
         r.aud_label, r.item_id, r.task_count)
      on conflict (student_id, plan_item_id) where plan_item_id is not null
      do nothing;  -- гонка параллельных синхронизаций не даёт второй строки
    end if;
  end loop;

  -- Неначатые плановые строки недели без эффективного item (item деактивирован,
  -- план отменён, в новой аудитории слота нет) удаляются: daily — не раньше
  -- v_replace_from, weekly — пока не начата (SPEC §5.4–5.5). Legacy-строки
  -- (plan_item_id = null) не затрагиваются.
  delete from public.assignments a
   where a.student_id = p_student_id
     and a.plan_item_id is not null
     and a.week_label = v_week_label
     and a.status = 'assigned'
     and a.submitted_at is null
     and a.photo_url is null
     and a.first_submitted_at is null
     and (a.type <> 'daily'
          or (a.scheduled_date is not null and a.scheduled_date >= v_replace_from))
     and not (a.plan_item_id = any (v_eff_ids));
end;
$function$;

-- publish_weekly_plan — публикация И редактирование плана (upsert item'ов по
-- слотам) одной транзакцией с синхронизацией затронутых учеников (миграция 011;
-- SPEC §5.2, §5.5). Мультивыбор групп в UI = отдельный вызов на каждую группу.
-- Слоты, отсутствующие в p_items, деактивируются (кроме замороженных daily
-- текущей недели, чей день уже наступил). Повторный вызов с теми же данными
-- ничего не меняет. Полная мотивация — в шапке миграции 011.
CREATE OR REPLACE FUNCTION public.publish_weekly_plan(
  p_week_start    date,
  p_audience_type text,
  p_group_name    text DEFAULT null,
  p_items         jsonb DEFAULT '[]'::jsonb
)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
  v_today        date := (now() at time zone 'Europe/Moscow')::date;
  v_plan         public.weekly_plans%rowtype;
  v_item         public.weekly_plan_items%rowtype;
  itm            jsonb;
  v_type         text;
  v_dow          integer;
  v_title        text;
  v_url          text;
  v_comment      text;
  v_task_count   integer;
  v_slot_key     text;
  v_slot_date    date;
  v_touched      text[] := '{}';
  v_replace_from date;
  v_synced       integer := 0;
  v_active_items integer;
  r              record;
begin
  if p_week_start is null or extract(isodow from p_week_start) <> 1 then
    raise exception 'week_start должен быть понедельником';
  end if;
  if p_week_start + 6 < v_today then
    raise exception 'Неделя % уже прошла — публикация и редактирование запрещены', p_week_start;
  end if;
  if p_audience_type is null or p_audience_type not in ('all', 'group') then
    raise exception 'audience_type должен быть all или group';
  end if;
  if p_audience_type = 'group' and (p_group_name is null or btrim(p_group_name) = '') then
    raise exception 'Для группового плана нужна непустая группа';
  end if;
  if p_audience_type = 'all' and p_group_name is not null then
    raise exception 'Для плана all группа не указывается';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'items должен быть json-массивом';
  end if;

  -- Активный план аудитории; отменённые остаются историей — создаётся новый.
  select * into v_plan
    from public.weekly_plans
   where week_start = p_week_start
     and audience_type = p_audience_type
     and group_name is not distinct from p_group_name
     and status = 'published'
   for update;

  if not found then
    insert into public.weekly_plans (week_start, audience_type, group_name, status)
      values (p_week_start, p_audience_type, p_group_name, 'published')
      returning * into v_plan;
  end if;

  -- Upsert item'ов по слотам.
  for itm in select value from jsonb_array_elements(p_items)
  loop
    v_type := itm->>'type';
    if v_type is null or v_type not in ('daily', 'weekly') then
      raise exception 'Тип задания должен быть daily или weekly';
    end if;

    if v_type = 'daily' then
      v_dow := (itm->>'day_of_week')::integer;
      if v_dow is null or v_dow < 1 or v_dow > 7 then
        raise exception 'day_of_week для daily должен быть 1–7';
      end if;
      v_slot_key  := 'daily-' || v_dow;
      v_slot_date := p_week_start + (v_dow - 1);
    else
      if itm->>'day_of_week' is not null then
        raise exception 'day_of_week для weekly не указывается';
      end if;
      v_dow := null;
      v_slot_key  := 'weekly';
      v_slot_date := p_week_start;
    end if;

    if v_slot_key = any (v_touched) then
      raise exception 'Слот % указан в items дважды', v_slot_key;
    end if;
    v_touched := v_touched || v_slot_key;

    v_title      := btrim(coalesce(itm->>'title', ''));
    v_url        := btrim(coalesce(itm->>'content_url', ''));
    v_comment    := nullif(btrim(coalesce(itm->>'teacher_comment', '')), '');
    v_task_count := (itm->>'task_count')::integer;
    if v_title = '' or v_url = '' then
      raise exception 'У задания слота % должны быть название и ссылка', v_slot_key;
    end if;
    if v_task_count is not null and v_task_count <= 0 then
      raise exception 'task_count должен быть положительным числом или null';
    end if;

    select * into v_item
      from public.weekly_plan_items
     where plan_id = v_plan.id
       and active
       and type = v_type
       and day_of_week is not distinct from v_dow
     for update;

    if found then
      if v_item.title = v_title
         and v_item.content_url = v_url
         and v_item.teacher_comment is not distinct from v_comment
         and v_item.task_count is not distinct from v_task_count then
        continue;  -- идемпотентный повтор публикации
      end if;
      -- Редактирование текущей daily после наступления дня запрещено (SPEC §5.5).
      if v_type = 'daily' and v_slot_date <= v_today then
        raise exception 'День % уже наступил — редактирование этого daily запрещено', v_slot_date;
      end if;
      update public.weekly_plan_items
         set title           = v_title,
             content_url     = v_url,
             teacher_comment = v_comment,
             task_count      = v_task_count,
             updated_at      = now()
       where id = v_item.id;
    else
      -- Новый item на прошедший день не добавляется; на сегодня — разрешён
      -- (согласовано с SPEC §5.3: новичок получает daily от today).
      if v_type = 'daily' and v_slot_date < v_today then
        raise exception 'День % уже прошёл — добавить daily задним числом нельзя', v_slot_date;
      end if;
      insert into public.weekly_plan_items
        (plan_id, type, day_of_week, title, content_url, teacher_comment, task_count)
      values
        (v_plan.id, v_type, v_dow, v_title, v_url, v_comment, v_task_count);
    end if;
  end loop;

  -- Слоты, отсутствующие в новой публикации: active = false (SPEC §5.5).
  -- Замороженные daily (день наступил) молча сохраняются.
  for r in
    select i.id, i.type,
           case when i.type = 'daily' then p_week_start + (i.day_of_week - 1)
                else p_week_start end as slot_date,
           case when i.type = 'daily' then 'daily-' || i.day_of_week
                else 'weekly' end as slot_key
      from public.weekly_plan_items i
     where i.plan_id = v_plan.id
       and i.active
  loop
    if r.slot_key = any (v_touched) then
      continue;
    end if;
    if r.type = 'daily' and r.slot_date <= v_today then
      continue;
    end if;
    update public.weekly_plan_items
       set active = false, updated_at = now()
     where id = r.id;
  end loop;

  update public.weekly_plans set updated_at = now() where id = v_plan.id;

  -- Синхронизация затронутых учеников той же транзакцией (SPEC §5.2):
  -- замена/удаление только будущих неначатых daily-строк (с завтра).
  v_replace_from := greatest(p_week_start, v_today + 1);
  for r in
    select telegram_id
      from public.students
     where p_audience_type = 'all' or group_name = p_group_name
  loop
    perform public.sync_student_week_assignments(r.telegram_id, p_week_start, v_replace_from);
    v_synced := v_synced + 1;
  end loop;

  select count(*) into v_active_items
    from public.weekly_plan_items
   where plan_id = v_plan.id and active;

  return json_build_object(
    'plan_id',         v_plan.id,
    'week_start',      v_plan.week_start,
    'audience_type',   v_plan.audience_type,
    'group_name',      v_plan.group_name,
    'active_items',    v_active_items,
    'students_synced', v_synced
  );
end;
$function$;

-- cancel_weekly_plan — отмена плана без удаления истории (миграция 011; SPEC §5.5):
-- начатые строки не трогаются; неначатые будущие пересобираются на fallback
-- (план all) либо удаляются. Повторная отмена идемпотентна.
CREATE OR REPLACE FUNCTION public.cancel_weekly_plan(p_plan_id uuid)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
  v_today        date := (now() at time zone 'Europe/Moscow')::date;
  v_plan         public.weekly_plans%rowtype;
  v_replace_from date;
  v_synced       integer := 0;
  r              record;
begin
  select * into v_plan
    from public.weekly_plans
    where id = p_plan_id
    for update;
  if not found then
    raise exception 'План % не найден', p_plan_id;
  end if;
  if v_plan.status = 'cancelled' then
    return json_build_object('plan_id', v_plan.id, 'status', 'cancelled', 'students_synced', 0);
  end if;
  if v_plan.week_start + 6 < v_today then
    raise exception 'Неделя % уже прошла — отменять её план нельзя', v_plan.week_start;
  end if;

  update public.weekly_plans
     set status = 'cancelled', updated_at = now()
   where id = v_plan.id;

  v_replace_from := greatest(v_plan.week_start, v_today + 1);
  for r in
    select telegram_id
      from public.students
     where v_plan.audience_type = 'all' or group_name = v_plan.group_name
  loop
    perform public.sync_student_week_assignments(r.telegram_id, v_plan.week_start, v_replace_from);
    v_synced := v_synced + 1;
  end loop;

  return json_build_object('plan_id', v_plan.id, 'status', 'cancelled', 'students_synced', v_synced);
end;
$function$;

-- --- Недельный расчёт: утилиты и RPC (миграция 012, W04) -----------------------
-- Полные решения и мотивация — в шапке миграции 012. Ключевые:
--   * поздняя ПЕРВАЯ сдача не засчитывается в A (решение пользователя 2026-07-16, SPEC §6.1);
--   * submitted_at/checked_at нормализуются серверным now() в триггере — клиентские часы не
--     определяют право на 24-часовое окно (SPEC §6.2);
--   * backfill legacy не делается: там, где нужна первая отправка, читается
--     coalesce(first_submitted_at, submitted_at);
--   * награда не начисляется: reward_amount сохраняется, add_huikons зовёт W09.

-- Понедельник учебной недели, содержащей дату (SPEC §3).
CREATE OR REPLACE FUNCTION public.week_start_of(p_date date)
 RETURNS date
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select p_date - (extract(isodow from p_date)::int - 1);
$function$;

-- Момент следующего понедельника 00:00 МСК — правая граница учебной недели (SPEC §3).
CREATE OR REPLACE FUNCTION public.next_monday_msk(p_date date)
 RETURNS timestamptz
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select ((public.week_start_of(p_date) + 7)::timestamp) at time zone 'Europe/Moscow';
$function$;

-- Недельная награда по эффективному результату E (SPEC §7.3, ECONOMY_V2 §4).
CREATE OR REPLACE FUNCTION public.weekly_reward_amount(p_effective integer)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select case
    when p_effective >= 7 then 110
    when p_effective = 6  then 80
    when p_effective = 5  then 55
    when p_effective = 4  then 30
    else 0
  end;
$function$;

-- Была ли ПЕРВАЯ отправка своевременной (в свой scheduled_date по МСК).
CREATE OR REPLACE FUNCTION public.is_first_submission_on_time(
  p_first_submitted_at timestamptz,
  p_submitted_at       timestamptz,
  p_scheduled_date     date
)
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select coalesce(p_first_submitted_at, p_submitted_at) is not null
     and p_scheduled_date is not null
     and (coalesce(p_first_submitted_at, p_submitted_at) at time zone 'Europe/Moscow')::date
         = p_scheduled_date;
$function$;

-- Доступный запас щитов = инвентарь минус активные резервы всех нефинализированных недель:
-- одну единицу нельзя обещать двум неделям (SPEC §7.2).
CREATE OR REPLACE FUNCTION public.available_shield_quantity(p_student_id bigint)
 RETURNS integer
 LANGUAGE sql
 STABLE
AS $function$
  select coalesce((select quantity from public.student_items
                    where student_id = p_student_id and item_code = 'streak_shield'), 0)
       - (select count(*) from public.weekly_shield_uses
           where student_id = p_student_id and status = 'requested')::int;
$function$;

-- request_weekly_shield / cancel_weekly_shield — ручной выбор щитов до финализации.
-- Ничего не списывают: списание только при финализации. Тела — в миграции 012.
CREATE OR REPLACE FUNCTION public.request_weekly_shield(p_student_id bigint, p_assignment_id uuid)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
  v_asn        public.assignments%rowtype;
  v_week_start date;
  v_status     text;
  v_available  integer;
begin
  perform 1 from public.student_items
    where student_id = p_student_id and item_code = 'streak_shield' for update;

  select * into v_asn from public.assignments where id = p_assignment_id;
  if not found or v_asn.student_id is distinct from p_student_id then
    raise exception 'Задание не найдено у этого ученика';
  end if;
  if v_asn.type <> 'daily' then
    raise exception 'Щит применяется только к ежедневкам';
  end if;
  if v_asn.scheduled_date is null then
    raise exception 'У задания нет даты — щит применить нельзя';
  end if;
  if v_asn.status = 'checked' and v_asn.approval_status = 'approved' then
    raise exception 'Работа уже принята — щит не нужен';
  end if;

  v_week_start := public.week_start_of(v_asn.scheduled_date);

  select status into v_status from public.student_week_results
    where student_id = p_student_id and week_start = v_week_start for update;
  if v_status in ('finalized', 'neutral') then
    raise exception 'Неделя уже закрыта — выбор щитов изменить нельзя';
  end if;

  if exists (select 1 from public.weekly_shield_uses
               where assignment_id = p_assignment_id and status = 'requested') then
    return json_build_object('status', 'requested', 'available', public.available_shield_quantity(p_student_id));
  end if;
  if exists (select 1 from public.weekly_shield_uses
               where assignment_id = p_assignment_id and status = 'consumed') then
    raise exception 'На это задание щит уже списан';
  end if;

  v_available := public.available_shield_quantity(p_student_id);
  if v_available < 1 then
    raise exception 'Нет свободных щитов: все либо не куплены, либо уже обещаны другой неделе';
  end if;

  insert into public.weekly_shield_uses (student_id, week_start, assignment_id, status)
    values (p_student_id, v_week_start, p_assignment_id, 'requested');

  perform public.recalc_student_week(p_student_id, v_week_start);

  return json_build_object('status', 'requested', 'available', public.available_shield_quantity(p_student_id));
end;
$function$;

CREATE OR REPLACE FUNCTION public.cancel_weekly_shield(p_student_id bigint, p_assignment_id uuid)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
  v_week_start date;
  v_status     text;
begin
  select week_start into v_week_start from public.weekly_shield_uses
    where assignment_id = p_assignment_id and student_id = p_student_id and status = 'requested'
    for update;
  if not found then
    return json_build_object('status', 'cancelled', 'available', public.available_shield_quantity(p_student_id));
  end if;

  select status into v_status from public.student_week_results
    where student_id = p_student_id and week_start = v_week_start for update;
  if v_status in ('finalized', 'neutral') then
    raise exception 'Неделя уже закрыта — выбор щитов изменить нельзя';
  end if;

  update public.weekly_shield_uses
     set status = 'cancelled', cancelled_at = now(), updated_at = now()
   where assignment_id = p_assignment_id and status = 'requested';

  perform public.recalc_student_week(p_student_id, v_week_start);

  return json_build_object('status', 'cancelled', 'available', public.available_shield_quantity(p_student_id));
end;
$function$;

-- recalc_student_week — снимок недели по фактическим assignments. N/A считаются по
-- scheduled_date (а не week_label), поэтому legacy-строки попадают в свою реальную неделю.
-- Миграция 014 дополнительно исключает раннюю первую сдачу и пересдачу после deadline.
CREATE OR REPLACE FUNCTION public.recalc_student_week(p_student_id bigint, p_week_start date)
 RETURNS public.student_week_results
 LANGUAGE plpgsql
AS $function$
declare
  v_row       public.student_week_results%rowtype;
  v_n         integer;
  v_a         integer;
  v_requested integer;
  v_consumed  integer;
  v_shields   integer;
  v_e         integer;
  v_pending   boolean;
  v_awaiting  boolean;
  v_status    text;
begin
  if p_week_start is null or extract(isodow from p_week_start) <> 1 then
    raise exception 'week_start % is not Monday', p_week_start;
  end if;

  select * into v_row from public.student_week_results
    where student_id = p_student_id and week_start = p_week_start for update;

  if found and v_row.status in ('finalized', 'neutral') then
    return v_row;
  end if;

  select
    count(*),
    count(*) filter (
      where a.status = 'checked' and a.approval_status = 'approved'
        and public.is_first_submission_on_time(a.first_submitted_at, a.submitted_at, a.scheduled_date)
        and (coalesce(a.revision_count, 0) = 0
             or (a.revision_deadline_at is not null
                 and a.submitted_at is not null
                 and a.submitted_at <= a.revision_deadline_at))),
    bool_or(a.status = 'submitted'
            and public.is_first_submission_on_time(a.first_submitted_at, a.submitted_at, a.scheduled_date)
            and (coalesce(a.revision_count, 0) = 0
                 or (a.revision_deadline_at is not null
                     and a.submitted_at is not null
                     and a.submitted_at <= a.revision_deadline_at))),
    bool_or(a.status = 'checked' and a.approval_status = 'rejected'
            and a.revision_deadline_at is not null and a.revision_deadline_at > now())
  into v_n, v_a, v_pending, v_awaiting
  from public.assignments a
  where a.student_id = p_student_id
    and a.type = 'daily'
    and a.scheduled_date between p_week_start and p_week_start + 6;

  v_n := coalesce(v_n, 0);
  v_a := coalesce(v_a, 0);
  v_pending := coalesce(v_pending, false);
  v_awaiting := coalesce(v_awaiting, false);

  select count(*) filter (where status = 'requested'), count(*) filter (where status = 'consumed')
    into v_requested, v_consumed
    from public.weekly_shield_uses
   where student_id = p_student_id and week_start = p_week_start;

  v_requested := coalesce(v_requested, 0);
  v_consumed := coalesce(v_consumed, 0);
  v_shields := v_requested + v_consumed;
  v_e := least(v_n, v_a + v_shields, 7);

  if v_pending then
    v_status := 'pending_review';
  elsif v_awaiting then
    v_status := 'awaiting_student';
  else
    v_status := 'open';
  end if;

  insert into public.student_week_results as r
    (student_id, week_start, available_daily_count, approved_daily_count,
     requested_shields, shields_used, effective_daily_count, status)
  values
    (p_student_id, p_week_start, v_n, v_a, v_requested, v_consumed, v_e, v_status)
  on conflict (student_id, week_start) do update
    set available_daily_count = excluded.available_daily_count,
        approved_daily_count  = excluded.approved_daily_count,
        requested_shields     = excluded.requested_shields,
        shields_used          = excluded.shields_used,
        effective_daily_count = excluded.effective_daily_count,
        status                = excluded.status,
        updated_at            = now()
  returning * into v_row;

  return v_row;
end;
$function$;

-- finalize_student_week — идемпотентная финализация одной недели (SPEC §6.3, §7.2, §7.3):
-- пересчёт → проверка окон → списание выбранных щитов → фиксация итога. Награду не платит.
CREATE OR REPLACE FUNCTION public.finalize_student_week(p_student_id bigint, p_week_start date)
 RETURNS public.student_week_results
 LANGUAGE plpgsql
AS $function$
declare
  v_row      public.student_week_results%rowtype;
  v_qty      integer;
  v_consume  integer;
  v_e        integer;
begin
  perform 1 from public.student_items
    where student_id = p_student_id and item_code = 'streak_shield' for update;

  v_row := public.recalc_student_week(p_student_id, p_week_start);

  if v_row.status in ('finalized', 'neutral') then
    return v_row;
  end if;

  if now() < public.next_monday_msk(p_week_start)
     or v_row.status in ('pending_review', 'awaiting_student') then
    return v_row;
  end if;

  if v_row.available_daily_count < 4 then
    update public.weekly_shield_uses
       set status = 'cancelled', cancelled_at = now(), updated_at = now()
     where student_id = p_student_id and week_start = p_week_start and status = 'requested';

    update public.student_week_results
       set status = 'neutral',
           successful = null,
           requested_shields = 0,
           shields_used = 0,
           effective_daily_count = least(available_daily_count, approved_daily_count, 7),
           reward_amount = 0,
           neutral_reason = case
             when available_daily_count = 0 then 'нет назначенных ежедневок'
             else 'меньше четырёх доступных ежедневок' end,
           finalized_at = now(),
           updated_at = now()
     where student_id = p_student_id and week_start = p_week_start
    returning * into v_row;

    return v_row;
  end if;

  select coalesce(quantity, 0) into v_qty from public.student_items
    where student_id = p_student_id and item_code = 'streak_shield';
  v_qty := coalesce(v_qty, 0);
  v_consume := least(v_row.requested_shields, v_qty);

  if v_consume > 0 then
    update public.weekly_shield_uses
       set status = 'consumed', consumed_at = now(), updated_at = now()
     where id in (
       select id from public.weekly_shield_uses
        where student_id = p_student_id and week_start = p_week_start and status = 'requested'
        order by requested_at
        limit v_consume
     );

    update public.weekly_shield_uses
       set status = 'cancelled', cancelled_at = now(), updated_at = now()
     where student_id = p_student_id and week_start = p_week_start and status = 'requested';

    update public.student_items
       set quantity = quantity - v_consume, updated_at = now()
     where student_id = p_student_id and item_code = 'streak_shield';
  else
    update public.weekly_shield_uses
       set status = 'cancelled', cancelled_at = now(), updated_at = now()
     where student_id = p_student_id and week_start = p_week_start and status = 'requested';
  end if;

  v_e := least(v_row.available_daily_count, v_row.approved_daily_count + v_consume, 7);

  update public.student_week_results
     set requested_shields     = 0,
         shields_used          = v_consume,
         effective_daily_count = v_e,
         status                = 'finalized',
         successful            = (v_e >= 4),
         reward_amount         = public.weekly_reward_amount(v_e),
         finalized_at          = now(),
         updated_at            = now()
   where student_id = p_student_id and week_start = p_week_start
  returning * into v_row;

  return v_row;
end;
$function$;

-- finalize_due_student_weeks — пакетная финализация недель с закрытыми окнами. Миграция 014
-- добавила поиск материализованных plan_item daily без заранее созданного результата, чтобы
-- финализация не зависела от открытия Mini App. Расписание включает W09 с cutover_at.
CREATE OR REPLACE FUNCTION public.finalize_due_student_weeks()
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
declare
  v_count integer := 0;
  v_row   public.student_week_results%rowtype;
  r       record;
begin
  for r in
    with due_candidates as (
      select swr.student_id, swr.week_start
        from public.student_week_results swr
       where swr.status not in ('finalized', 'neutral')
         and now() >= public.next_monday_msk(swr.week_start)

      union

      select a.student_id, public.week_start_of(a.scheduled_date) as week_start
        from public.assignments a
       where a.type = 'daily'
         and a.plan_item_id is not null
         and a.scheduled_date is not null
         and now() >= public.next_monday_msk(a.scheduled_date)
         and not exists (
           select 1
             from public.student_week_results closed
            where closed.student_id = a.student_id
              and closed.week_start = public.week_start_of(a.scheduled_date)
              and closed.status in ('finalized', 'neutral')
         )
       group by a.student_id, public.week_start_of(a.scheduled_date)
    )
    select student_id, week_start
      from due_candidates
     order by week_start, student_id
  loop
    v_row := public.finalize_student_week(r.student_id, r.week_start);
    if v_row.status in ('finalized', 'neutral') then
      v_count := v_count + 1;
    end if;
  end loop;

  return v_count;
end;
$function$;

-- --- Триггеры ------------------------------------------------------------------

-- trg_assignments_revision_lifecycle — серверная семантика полей исправлений (миграция 012):
-- фиксирует first_submitted_at, наращивает revision_count при РЕАЛЬНОМ возврате и считает
-- revision_deadline_at (понедельник 00:00 МСК; +24ч при позднем возврате вовремя отправленной
-- работы). Триггером, а не RPC: в assignments пишут существующие клиенты, а W04 не меняет UI.
CREATE OR REPLACE FUNCTION public.trg_assignments_revision_lifecycle()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
  v_attempt_on_time boolean;
  v_next_monday     timestamptz;
begin
  if new.status = 'submitted' and new.submitted_at is distinct from old.submitted_at then
    new.submitted_at := now();
    if new.first_submitted_at is null then
      new.first_submitted_at := now();
    end if;
  end if;

  if new.status = 'checked' and new.checked_at is distinct from old.checked_at then
    new.checked_at := now();
  end if;

  if new.status = 'checked'
     and new.approval_status = 'rejected'
     and old.status = 'submitted' then

    new.revision_count := coalesce(old.revision_count, 0) + 1;

    if new.type = 'daily' then
      if coalesce(old.revision_count, 0) = 0 then
        v_attempt_on_time := public.is_first_submission_on_time(
          old.first_submitted_at, old.submitted_at, new.scheduled_date);
      else
        v_attempt_on_time := old.revision_deadline_at is not null
                         and old.submitted_at is not null
                         and old.submitted_at <= old.revision_deadline_at;
      end if;

      if v_attempt_on_time then
        v_next_monday := public.next_monday_msk(new.scheduled_date);
        if now() < v_next_monday then
          new.revision_deadline_at := v_next_monday;
        else
          new.revision_deadline_at := now() + interval '24 hours';
        end if;
      else
        new.revision_deadline_at := null;
      end if;
    end if;
  end if;

  return new;
end;
$function$;

create trigger trg_assignments_revision_lifecycle
  before update on public.assignments
  for each row
  execute function public.trg_assignments_revision_lifecycle();

-- trg_assignments_release_shield — принятая работа освобождает свой резерв щита (SPEC §7.2):
-- щит не тратится на день, который в итоге зачли по-настоящему.
CREATE OR REPLACE FUNCTION public.trg_assignments_release_shield()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if new.status = 'checked' and new.approval_status = 'approved'
     and (old.status is distinct from 'checked' or old.approval_status is distinct from 'approved') then
    update public.weekly_shield_uses
       set status = 'cancelled', cancelled_at = now(), updated_at = now()
     where assignment_id = new.id and status = 'requested';
  end if;
  return null;
end;
$function$;

create trigger trg_assignments_release_shield
  after update on public.assignments
  for each row
  execute function public.trg_assignments_release_shield();

-- trg_students_sync_weekly_plans — новый ученик и смена группы (миграция 011;
-- SPEC §5.3–5.4): синхронизирует текущую и опубликованные будущие недели.
-- Пишет только в assignments — рекурсия по students невозможна.
CREATE OR REPLACE FUNCTION public.trg_students_sync_weekly_plans()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
  v_today date := (now() at time zone 'Europe/Moscow')::date;
  r record;
begin
  for r in
    select distinct week_start
      from public.weekly_plans
     where status = 'published'
       and week_start + 6 >= v_today
  loop
    -- Новый ученик и смена группы: замена/вставка от сегодня (SPEC §5.3–5.4).
    perform public.sync_student_week_assignments(
      new.telegram_id, r.week_start, greatest(r.week_start, v_today));
  end loop;
  return new;
end;
$function$;

create trigger trg_students_weekly_plans_insert
  after insert on public.students
  for each row
  execute function public.trg_students_sync_weekly_plans();

create trigger trg_students_weekly_plans_group_change
  after update of group_name on public.students
  for each row
  when (old.group_name is distinct from new.group_name)
  execute function public.trg_students_sync_weekly_plans();

-- get_student_task_totals — серверный lifetime/range счётчик задач и дней занятий поверх
-- lifecycle-полей W01/W04 (миграция 013, P01A). Read-only производная от assignments: без
-- отдельного изменяемого counter. Принятая работа = status='checked' и
-- approval_status='approved'; solved_tasks суммирует только task_count > 0 (сложение null
-- бессмысленно), active_days считает ВСЕ принятые работы с известной датой отправки, включая
-- legacy с task_count IS NULL (решение пользователя 2026-07-16: день был реально активным
-- независимо от того, известно ли число задач) — такие строки одновременно увеличивают
-- unknown_approved_assignments. p_from/p_to = null → lifetime; иначе диапазон дат МСК
-- включительно, каждая граница независима. Полная мотивация — в шапке миграции 013.
CREATE OR REPLACE FUNCTION public.get_student_task_totals(
  p_student_id bigint,
  p_from       date DEFAULT null,
  p_to         date DEFAULT null
)
 RETURNS TABLE(
   solved_tasks                 bigint,
   active_days                  bigint,
   unknown_approved_assignments bigint
 )
 LANGUAGE sql
 STABLE
AS $function$
  with accepted as (
    select
      a.task_count,
      (coalesce(a.first_submitted_at, a.submitted_at) at time zone 'Europe/Moscow')::date as date_msk
    from public.assignments a
    where a.student_id = p_student_id
      and a.status = 'checked'
      and a.approval_status = 'approved'
      and (p_from is null or (coalesce(a.first_submitted_at, a.submitted_at) at time zone 'Europe/Moscow')::date >= p_from)
      and (p_to   is null or (coalesce(a.first_submitted_at, a.submitted_at) at time zone 'Europe/Moscow')::date <= p_to)
  )
  select
    coalesce(sum(task_count) filter (where task_count > 0), 0)::bigint as solved_tasks,
    count(distinct date_msk)::bigint                                   as active_days,
    count(*) filter (where task_count is null)::bigint                 as unknown_approved_assignments
  from accepted;
$function$;
-- =============================================================================
-- 015_current_week_read_model.sql
-- Read-only current-week model for student/parent consumers (W07 correction).
--
-- W07 duplicated the W04/014 weekly rules in parent_bot.py because the read-only RPC
-- required by SPEC_STAGE2_5 section 10 did not exist. This function restores one server
-- contract: it derives the current MSK week directly from assignments and shield reserves,
-- returns all seven calendar slots plus N/A/S/E and weekly status, and performs no writes.
-- It does not call recalc_student_week and does not create student_week_results.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.get_student_current_week(p_student_id bigint)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
AS $function$
with params as (
  select
    (now() at time zone 'Europe/Moscow')::date as today,
    public.week_start_of((now() at time zone 'Europe/Moscow')::date) as week_start,
    now() as now_ts
),
slots as (
  select p.week_start + gs.day_index as slot_date, gs.day_index
    from params p
    cross join generate_series(0, 6) as gs(day_index)
),
daily_ranked as (
  select
    a.*,
    row_number() over (
      partition by a.scheduled_date
      order by (a.plan_item_id is not null) desc, a.created_at desc, a.id desc
    ) as rn
  from public.assignments a
  cross join params p
  where a.student_id = p_student_id
    and a.type = 'daily'
    and a.scheduled_date between p.week_start and p.week_start + 6
),
daily as (
  select
    a.*,
    public.is_first_submission_on_time(
      a.first_submitted_at, a.submitted_at, a.scheduled_date
    )
    and (
      coalesce(a.revision_count, 0) = 0
      or (
        a.revision_deadline_at is not null
        and a.submitted_at is not null
        and a.submitted_at <= a.revision_deadline_at
      )
    ) as attempt_on_time
  from daily_ranked a
  where a.rn = 1
),
active_shields as (
  select distinct on (u.assignment_id)
    u.assignment_id,
    u.status
  from public.weekly_shield_uses u
  cross join params p
  where u.student_id = p_student_id
    and u.week_start = p.week_start
    and u.status in ('requested', 'consumed')
  order by u.assignment_id,
           case when u.status = 'consumed' then 0 else 1 end,
           u.created_at desc
),
day_rows as (
  select
    s.day_index,
    s.slot_date,
    d.id as assignment_id,
    d.title,
    d.task_count,
    d.revision_deadline_at,
    sh.status as shield_status,
    case
      when d.id is null then 'not_assigned'
      when sh.status is not null then 'shielded'
      when d.status = 'checked' and d.approval_status = 'approved' and d.attempt_on_time
        then 'approved'
      when d.status = 'checked' and d.approval_status = 'rejected'
           and d.revision_deadline_at is not null
           and d.revision_deadline_at > p.now_ts
        then 'revision'
      when d.status = 'submitted' then 'submitted'
      when d.status = 'assigned' and d.scheduled_date < p.today then 'missed'
      when d.status = 'assigned' then 'assigned'
      else 'missed'
    end as day_status
  from slots s
  cross join params p
  left join daily d on d.scheduled_date = s.slot_date
  left join active_shields sh on sh.assignment_id = d.id
),
daily_stats as (
  select
    count(*)::int as n,
    count(*) filter (
      where d.status = 'checked'
        and d.approval_status = 'approved'
        and d.attempt_on_time
    )::int as a,
    coalesce(bool_or(d.status = 'submitted' and d.attempt_on_time), false) as pending_review,
    coalesce(bool_or(
      d.status = 'checked'
      and d.approval_status = 'rejected'
      and d.revision_deadline_at is not null
      and d.revision_deadline_at > p.now_ts
    ), false) as awaiting_student
  from daily d
  cross join params p
),
shield_stats as (
  select count(*)::int as s from active_shields
),
totals as (
  select
    ds.n,
    ds.a,
    ss.s,
    least(ds.n, ds.a + ss.s, 7)::int as e,
    ds.pending_review,
    ds.awaiting_student
  from daily_stats ds
  cross join shield_stats ss
),
classified as (
  select
    t.*,
    case
      when t.pending_review then 'pending_review'
      when t.awaiting_student then 'awaiting_student'
      else 'open'
    end as result_status,
    case
      when t.pending_review or t.awaiting_student then 'pending'
      when t.n < 4 then 'neutral'
      when t.e >= 4 then 'successful'
      else 'weak'
    end as classification
  from totals t
),
weekly_ranked as (
  select
    a.*,
    row_number() over (
      order by (a.plan_item_id is not null) desc, a.created_at desc, a.id desc
    ) as rn
  from public.assignments a
  cross join params p
  where a.student_id = p_student_id
    and a.type = 'weekly'
    and a.week_label = p.week_start::text
),
weekly_payload as (
  select jsonb_build_object(
    'assignment_id', w.id,
    'title', w.title,
    'task_count', w.task_count,
    'status', case
      when w.status = 'assigned' then 'assigned'
      when w.status = 'submitted' then 'submitted'
      when w.status = 'checked' and w.approval_status = 'approved' then 'approved'
      when w.status = 'checked' and w.approval_status = 'rejected' then 'rejected'
      else 'unknown'
    end
  ) as payload
  from weekly_ranked w
  where w.rn = 1
),
days_payload as (
  select jsonb_agg(
    jsonb_build_object(
      'day_index', d.day_index,
      'date', d.slot_date,
      'assignment_id', d.assignment_id,
      'title', d.title,
      'task_count', d.task_count,
      'status', d.day_status,
      'shield_status', d.shield_status,
      'revision_deadline_at', d.revision_deadline_at
    ) order by d.day_index
  ) as payload
  from day_rows d
)
select jsonb_build_object(
  'week_start', p.week_start,
  'week_end', p.week_start + 6,
  'n', c.n,
  'a', c.a,
  's', c.s,
  'e', c.e,
  'result_status', c.result_status,
  'classification', c.classification,
  'reward_forecast', public.weekly_reward_amount(c.e),
  'days', coalesce(dp.payload, '[]'::jsonb),
  'weekly', (select wp.payload from weekly_payload wp limit 1)
)
from params p
cross join classified c
cross join days_payload dp;
$function$;

-- record_weekly_mock_exam — атомарная запись/редактирование результата недельного пробника
-- (миграция 016, P02A; SPEC §9, ECONOMY_V2 §§11,14). Единственная точка записи пробника.
-- База +20 и рекорд +30 бубликов — pay-once через mock_exam_reward_log; season points
-- 50 + рост (cap 20) — детерминированная компенсирующая дельта в weekly_mock_exams.
-- season_points_awarded. Зеркалит display-строку в mock_exam_results для существующих
-- графиков/списков. Блокировка students(for update) сериализует конкурентные вызовы.
-- Полная мотивация и границы — в шапке миграции 016.
CREATE OR REPLACE FUNCTION public.record_weekly_mock_exam(
  p_student_id bigint,
  p_week_start date,
  p_score      integer
)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
  v_prev_score   integer;
  v_prev_max     integer;
  v_growth       integer;
  v_season_target integer;
  v_season_prev  integer;
  v_season_delta integer;
  v_is_record    boolean;
  v_record_this_month boolean;
  v_base_awarded boolean := false;
  v_record_awarded boolean := false;
  v_now          timestamptz := now();
  v_month_start  date := date_trunc('month', (v_now at time zone 'Europe/Moscow'))::date;
  v_exam_name    text;
begin
  if p_week_start is null or extract(isodow from p_week_start) <> 1 then
    raise exception 'week_start % — не понедельник', p_week_start;
  end if;
  if p_score is null or p_score < 0 or p_score > 100 then
    raise exception 'score должен быть целым от 0 до 100';
  end if;

  perform 1 from public.students where telegram_id = p_student_id for update;
  if not found then
    raise exception 'Ученик % не найден', p_student_id;
  end if;

  select score into v_prev_score
    from public.weekly_mock_exams
    where student_id = p_student_id and week_start < p_week_start
    order by week_start desc
    limit 1;

  select max(score) into v_prev_max
    from public.weekly_mock_exams
    where student_id = p_student_id and week_start < p_week_start;

  v_growth := least(greatest(p_score - coalesce(v_prev_score, p_score), 0), 20);
  v_season_target := 50 + v_growth;

  select season_points_awarded into v_season_prev
    from public.weekly_mock_exams
    where student_id = p_student_id and week_start = p_week_start
    for update;

  if not found then
    insert into public.weekly_mock_exams (student_id, week_start, score, season_points_awarded)
      values (p_student_id, p_week_start, p_score, v_season_target);
    v_season_prev := 0;
  else
    update public.weekly_mock_exams
      set score = p_score,
          season_points_awarded = v_season_target,
          updated_at = v_now
      where student_id = p_student_id and week_start = p_week_start;
  end if;

  v_season_delta := v_season_target - v_season_prev;
  if v_season_delta <> 0 then
    perform public.add_season_points(p_student_id, v_season_delta);
  end if;

  v_exam_name := 'Недельный пробник ' || to_char(p_week_start, 'DD.MM.YYYY');
  insert into public.mock_exam_results (student_id, exam_name, score, exam_date, updated_at)
    values (p_student_id, v_exam_name, p_score::text, p_week_start, v_now)
    on conflict (student_id, exam_name)
    do update set score = excluded.score, exam_date = excluded.exam_date, updated_at = v_now;

  insert into public.mock_exam_reward_log (student_id, week_start, reward_kind, bubliks)
    values (p_student_id, p_week_start, 'base', 20)
    on conflict (student_id, week_start, reward_kind) do nothing;
  if found then
    perform public.add_huikons(p_student_id, 20, 'mock_exam_weekly');
    v_base_awarded := true;
  end if;

  v_is_record := v_prev_max is not null and p_score >= v_prev_max + 3;
  if v_is_record then
    select exists (
      select 1 from public.mock_exam_reward_log
        where student_id = p_student_id and reward_kind = 'record'
          and (awarded_at at time zone 'Europe/Moscow')::date >= v_month_start
          and (awarded_at at time zone 'Europe/Moscow')::date < (v_month_start + interval '1 month')
    ) into v_record_this_month;

    if not v_record_this_month then
      insert into public.mock_exam_reward_log (student_id, week_start, reward_kind, bubliks)
        values (p_student_id, p_week_start, 'record', 30)
        on conflict (student_id, week_start, reward_kind) do nothing;
      if found then
        perform public.add_huikons(p_student_id, 30, 'mock_exam_record');
        v_record_awarded := true;
      end if;
    end if;
  end if;

  return json_build_object(
    'week_start', p_week_start,
    'score', p_score,
    'season_points_awarded', v_season_target,
    'season_points_delta', v_season_delta,
    'base_awarded', v_base_awarded,
    'record_eligible', v_is_record,
    'record_awarded', v_record_awarded
  );
end;
$function$;
