-- schema.sql — снимок схемы Supabase (public) проекта Sasha Math
-- =============================================================================
-- Задача T2 (ROADMAP.md): сохранить чертёж базы вне консоли Supabase.
--
-- Снят: 2026-07-10. Способ: read-only запросы к information_schema / pg_catalog
-- (колонки, ограничения, индексы, внешние ключи, определения функций) — см.
-- инструкцию в переписке. Это снимок «как есть», а не первая миграция: дальнейшие
-- изменения БД по-прежнему оформляются файлами database/migrations/NNN_*.sql.
--
-- ВАЖНЫЕ ОСОБЕННОСТИ, зафиксированные на момент снимка:
--   * RLS выключен на всех таблицах, КРОМЕ student_payments (миграция 002).
--     Открытость на запись — сознательно принятый риск, задача T10 в ROADMAP.md.
--   * Ученик во всём проекте адресуется по students.telegram_id, а НЕ по PK id.
--     Все внешние ключи ссылаются на telegram_id (уникальный индекс
--     idx_students_telegram_id обеспечивает эту ссылочную целостность).
--   * students.payment_date оставлена для совместимости, но обнулена и не
--     заполняется — платежи изолированы в student_payments (миграция 002).
--   * Таблица homework_submissions присутствует в БД, но текущими index.html/
--     teacher.html не используется (работа с ДЗ идёт через assignments) —
--     вероятно, наследие ранней версии. Удалять без отдельного решения нельзя.
--
-- Исправлено 2026-07-11: students.id — identity-колонка (generated by default as identity),
-- это не попало в исходный снимок (первоначальный запрос к information_schema не проверял
-- identity-статус колонок). Обнаружено при подготовке dev-копии схемы для форка Bot 2.0 —
-- loadProfile() в index.html вставляет нового ученика без явного id, полагаясь на автогенерацию.
-- =============================================================================

-- --- Таблицы -----------------------------------------------------------------

-- students — родительская таблица для всех внешних ключей.
-- PK = id, но ссылки и вся бизнес-логика идут по telegram_id (см. индекс ниже).
create table public.students (
  id                        bigint  generated by default as identity primary key,
  telegram_id               bigint  not null,
  name                      text,
  rating                    integer default 50,
  huikons                   integer default 0,
  lives                     integer default 3,
  current_streak            integer default 0,
  last_submission_date_msk  date,
  telegram_username         text,
  group_name                text,
  payment_date              date            -- обнулена и не используется (миграция 002)
);

-- Уникальность telegram_id; на этот индекс ссылаются все FK ниже.
create unique index if not exists idx_students_telegram_id
  on public.students (telegram_id);

-- assignments — задание-строка на ученика (ежедневные/еженедельные/индивидуальные).
create table public.assignments (
  id                 uuid         primary key default gen_random_uuid(),
  student_id         bigint       references public.students (telegram_id),
  type               text         not null,
  title              text,
  content_url        text,
  teacher_comment    text,
  day_of_week        integer,
  week_label         text,
  scheduled_date     date,
  activation_status  text         default 'draft',
  status             text         default 'assigned',
  created_at         timestamptz  default now(),
  submitted_at       timestamptz,
  checked_at         timestamptz,
  photo_url          text,
  teacher_feedback   text,
  approval_status    text,
  assigned_group     text
);

-- balance_history — журнал начислений/списаний хуиконов (пишется только из add_huikons).
create table public.balance_history (
  id             uuid         primary key default gen_random_uuid(),
  student_id     bigint       references public.students (telegram_id),
  change_amount  integer      not null,
  reason         text         not null,
  created_at     timestamptz  default now()
);

-- homework_submissions — НАСЛЕДИЕ, текущим кодом не используется (см. шапку файла).
create table public.homework_submissions (
  id               uuid         primary key default gen_random_uuid(),
  student_id       bigint       references public.students (telegram_id),
  variant_number   integer      not null,
  photo_url        text         not null,
  status           text         not null default 'pending',
  teacher_comment  text,
  created_at       timestamptz  default now(),
  checked_at       timestamptz
);

-- mock_exam_results — результаты пробников; upsert идемпотентен по (student_id, exam_name).
create table public.mock_exam_results (
  id          uuid         primary key default gen_random_uuid(),
  student_id  bigint       not null references public.students (telegram_id),
  exam_name   text         not null,
  score       text,
  updated_at  timestamptz  not null default now(),
  created_at  timestamptz  not null default now(),
  exam_date   date,
  unique (student_id, exam_name)
);

-- parent_links — привязка родителя к ученику; upsert идемпотентен по (parent_telegram_id, student_id).
create table public.parent_links (
  id                  uuid         primary key default gen_random_uuid(),
  parent_telegram_id  bigint       not null,
  student_id          bigint       not null references public.students (telegram_id),
  linked_at           timestamptz  not null default now(),
  unique (parent_telegram_id, student_id)
);

-- student_payments — платёжные снимки, изолированы от публичного чтения (миграция 002).
-- Без FK на students (историческое решение миграции 002).
create table public.student_payments (
  student_id    bigint  primary key,
  payment_date  date
);

alter table public.student_payments enable row level security;
-- RLS без единой policy = доступ только у service_role (Apps Script);
-- anon-ключ (index.html/teacher.html/боты) платежи не читает (миграция 002).

-- bot_notification_state — персистентная дата последней рассылки main.py (миграция 004).
-- Переживает передеплой/рестарт процесса — без неё "уже отправлено сегодня" терялось при
-- каждом рестарте после времени срабатывания, и рассылка уходила повторно.
create table public.bot_notification_state (
  notification_key  text  primary key,
  last_sent_date    date
);

-- --- Индексы (кроме автоматических для PK/UNIQUE и idx_students_telegram_id выше) -----

create index if not exists idx_assignments_activation
  on public.assignments (activation_status, scheduled_date);
create index if not exists idx_assignments_student_status
  on public.assignments (student_id, status);
create index if not exists idx_assignments_week
  on public.assignments (week_label, type);

-- --- Функции -----------------------------------------------------------------

-- add_huikons — атомарное начисление/списание хуиконов (миграция 001, задача T5).
CREATE OR REPLACE FUNCTION public.add_huikons(p_student_id bigint, p_amount integer, p_reason text)
 RETURNS TABLE(actual_change integer, new_balance integer)
 LANGUAGE plpgsql
AS $function$
declare
  v_old_balance int;
  v_new_balance int;
begin
  select huikons into v_old_balance
    from students
    where telegram_id = p_student_id
    for update;

  if v_old_balance is null then
    raise exception 'Student % not found', p_student_id;
  end if;

  v_new_balance := greatest(0, v_old_balance + p_amount);

  update students set huikons = v_new_balance where telegram_id = p_student_id;

  insert into balance_history (student_id, change_amount, reason)
    values (p_student_id, v_new_balance - v_old_balance, p_reason);

  return query select (v_new_balance - v_old_balance), v_new_balance;
end;
$function$;

-- get_student_progress — сводка выданных/выполненных заданий по типам (используется родительским ботом).
CREATE OR REPLACE FUNCTION public.get_student_progress(p_student_id bigint)
 RETURNS TABLE(type text, issued bigint, completed bigint)
 LANGUAGE sql
 STABLE
AS $function$
  select
    a.type,
    count(*) filter (where a.activation_status = 'active') as issued,
    count(*) filter (where a.status = 'checked' and a.approval_status = 'approved') as completed
  from assignments a
  where a.student_id = p_student_id
  group by a.type;
$function$;
