-- schema.sql — снимок схемы Supabase (public) проекта Sasha Math
-- =============================================================================
-- Задача T2 (ROADMAP.md): сохранить чертёж базы вне консоли Supabase.
--
-- Снят: 2026-07-10. Способ: read-only запросы к information_schema / pg_catalog
-- (колонки, ограничения, индексы, внешние ключи, определения функций) — см.
-- инструкцию в переписке. Это снимок «как есть», а не первая миграция: дальнейшие
-- изменения БД по-прежнему оформляются файлами database/migrations/NNN_*.sql.
--
-- ВАЖНЫЕ ОСОБЕННОСТИ, зафиксированные на момент снимка:
--   * RLS выключен на всех таблицах, КРОМЕ student_payments (миграция 002).
--     Открытость на запись — сознательно принятый риск, задача T10 в ROADMAP.md.
--   * Ученик во всём проекте адресуется по students.telegram_id, а НЕ по PK id.
--     Все внешние ключи ссылаются на telegram_id (уникальный индекс
--     idx_students_telegram_id обеспечивает эту ссылочную целостность).
--   * students.payment_date оставлена для совместимости, но обнулена и не
--     заполняется — платежи изолированы в student_payments (миграция 002).
--   * Таблица homework_submissions присутствует в БД, но текущими index.html/
--     teacher.html не используется (работа с ДЗ идёт через assignments) —
--     вероятно, наследие ранней версии. Удалять без отдельного решения нельзя.
--
-- Исправлено 2026-07-11: students.id — identity-колонка (generated by default as identity),
-- это не попало в исходный снимок (первоначальный запрос к information_schema не проверял
-- identity-статус колонок). Обнаружено при подготовке dev-копии схемы для форка Bot 2.0 —
-- loadProfile() в index.html вставляет нового ученика без явного id, полагаясь на автогенерацию.
-- =============================================================================

-- --- Таблицы -----------------------------------------------------------------

-- students — родительская таблица для всех внешних ключей.
-- PK = id, но ссылки и вся бизнес-логика идут по telegram_id (см. индекс ниже).
create table public.students (
  id                        bigint  generated by default as identity primary key,
  telegram_id               bigint  not null,
  name                      text,
  rating                    integer default 50,
  huikons                   integer default 0,
  lives                     integer default 3,
  current_streak            integer default 0,
  last_submission_date_msk  date,
  telegram_username         text,
  group_name                text,
  payment_date              date            -- обнулена и не используется (миграция 002)
);

-- Уникальность telegram_id; на этот индекс ссылаются все FK ниже.
create unique index if not exists idx_students_telegram_id
  on public.students (telegram_id);

-- assignments — задание-строка на ученика (ежедневные/еженедельные/индивидуальные).
create table public.assignments (
  id                 uuid         primary key default gen_random_uuid(),
  student_id         bigint       references public.students (telegram_id),
  type               text         not null,
  title              text,
  content_url        text,
  teacher_comment    text,
  day_of_week        integer,
  week_label         text,
  scheduled_date     date,
  activation_status  text         default 'draft',
  status             text         default 'assigned',
  created_at         timestamptz  default now(),
  submitted_at       timestamptz,
  checked_at         timestamptz,
  photo_url          text,
  teacher_feedback   text,
  approval_status    text,
  assigned_group     text
);

-- balance_history — журнал начислений/списаний хуиконов (пишется только из add_huikons).
create table public.balance_history (
  id             uuid         primary key default gen_random_uuid(),
  student_id     bigint       references public.students (telegram_id),
  change_amount  integer      not null,
  reason         text         not null,
  created_at     timestamptz  default now()
);

-- homework_submissions — НАСЛЕДИЕ, текущим кодом не используется (см. шапку файла).
create table public.homework_submissions (
  id               uuid         primary key default gen_random_uuid(),
  student_id       bigint       references public.students (telegram_id),
  variant_number   integer      not null,
  photo_url        text         not null,
  status           text         not null default 'pending',
  teacher_comment  text,
  created_at       timestamptz  default now(),
  checked_at       timestamptz
);

-- mock_exam_results — результаты пробников; upsert идемпотентен по (student_id, exam_name).
create table public.mock_exam_results (
  id          uuid         primary key default gen_random_uuid(),
  student_id  bigint       not null references public.students (telegram_id),
  exam_name   text         not null,
  score       text,
  updated_at  timestamptz  not null default now(),
  created_at  timestamptz  not null default now(),
  exam_date   date,
  unique (student_id, exam_name)
);

-- parent_links — привязка родителя к ученику; upsert идемпотентен по (parent_telegram_id, student_id).
create table public.parent_links (
  id                  uuid         primary key default gen_random_uuid(),
  parent_telegram_id  bigint       not null,
  student_id          bigint       not null references public.students (telegram_id),
  linked_at           timestamptz  not null default now(),
  unique (parent_telegram_id, student_id)
);

-- student_payments — платёжные снимки, изолированы от публичного чтения (миграция 002).
-- Без FK на students (историческое решение миграции 002).
create table public.student_payments (
  student_id    bigint  primary key,
  payment_date  date
);

alter table public.student_payments enable row level security;
-- RLS без единой policy = доступ только у service_role (Apps Script);
-- anon-ключ (index.html/teacher.html/боты) платежи не читает (миграция 002).

-- bot_notification_state — персистентная дата последней рассылки main.py (миграция 004).
-- Переживает передеплой/рестарт процесса — без неё "уже отправлено сегодня" терялось при
-- каждом рестарте после времени срабатывания, и рассылка уходила повторно.
create table public.bot_notification_state (
  notification_key  text  primary key,
  last_sent_date    date
);

-- --- Геймификация Bot 2.0 (миграция 005, задача G3) ---------------------------
-- students.rating = очки ТЕКУЩЕГО сезона (обнуляется при закрытии сезона, G7);
-- обоснование выбора хранения — в шапке миграции 005. Поле не переименовывается.

-- seasons — один ряд на сезон; id и есть «Сезон №N» в UI. end_date is null = сезон идёт.
create table public.seasons (
  id          bigint       generated by default as identity primary key,
  start_date  date         not null,
  end_date    date,                              -- null, пока сезон не закрыт
  created_at  timestamptz  not null default now()
);

-- Открытым может быть только один сезон одновременно.
create unique index if not exists idx_seasons_one_active
  on public.seasons ((true)) where end_date is null;

-- season_results — архив: итоговые очки и место ученика в закрытом сезоне.
-- Пишется один раз при закрытии сезона (G7), дальше только читается.
create table public.season_results (
  id          uuid         primary key default gen_random_uuid(),
  season_id   bigint       not null references public.seasons (id),
  student_id  bigint       not null references public.students (telegram_id),
  points      integer      not null,
  place       integer      not null,
  created_at  timestamptz  not null default now(),
  unique (season_id, student_id)
);

-- student_achievements — выданные достижения; строка = достижение получено, она же
-- флаг «право купить косметику» (этап 2). Вехи стрика и дисциплинарные достижения —
-- одно событие с одним начислением (SPEC_STAGE1.md, раздел 6). Идемпотентная выдача:
-- insert ... on conflict do nothing, бублики начислять только при реальной вставке.
create table public.student_achievements (
  id                uuid         primary key default gen_random_uuid(),
  student_id        bigint       not null references public.students (telegram_id),
  achievement_code  text         not null,
  unlocked_at       timestamptz  not null default now(),
  unique (student_id, achievement_code)
);

-- student_items — инвентарь; первый item_code — 'streak_shield' (щит стрика).
-- Лимит «не больше 2 щитов» — в RPC покупки (G9), не в схеме.
create table public.student_items (
  id          uuid         primary key default gen_random_uuid(),
  student_id  bigint       not null references public.students (telegram_id),
  item_code   text         not null,
  quantity    integer      not null default 0 check (quantity >= 0),
  updated_at  timestamptz  not null default now(),
  created_at  timestamptz  not null default now(),
  unique (student_id, item_code)
);

-- streak_shield_uses — какие пропущенные дни покрыты щитом стрика (миграция 007, задача G9).
-- Нужна для идемпотентного сшивания разрывов при пересчёте цепочки с нуля (см. шапку 007).
create table public.streak_shield_uses (
  id           uuid         primary key default gen_random_uuid(),
  student_id   bigint       not null references public.students (telegram_id),
  bridged_date date         not null,
  created_at   timestamptz  not null default now(),
  unique (student_id, bridged_date)
);

create index if not exists idx_streak_shield_uses_student
  on public.streak_shield_uses (student_id);
alter table public.streak_shield_uses disable row level security;  -- как и все таблицы проекта (T10)

-- shop_items — каталог магазина «Бубличная» (миграция 008, задача S1). Полные решения —
-- в шапке миграции 008: buy_item как единая точка покупки (щит — делегированием в
-- buy_streak_shield), ротация через бандлы, автоэкипировка косметики.
create table public.shop_items (
  item_code             text         primary key,
  name                  text         not null,
  item_kind             text         not null check (item_kind in ('cosmetic','shield','service')),
  slot                  text         check (slot in ('name_color','crown','status_emoji','title','frame','background')),
  price                 integer      not null check (price > 0),
  availability          text         not null check (availability in ('always','rotation')),
  rotation_bundle       integer,
  condition_achievement text,
  render_payload        text,
  sort_order            integer      not null default 100,
  active                boolean      not null default true,
  created_at            timestamptz  not null default now(),
  check ((availability = 'rotation') = (rotation_bundle is not null))
);
alter table public.shop_items disable row level security;

-- season_bundles — какой ротационный набор на витрине какого сезона (миграция 008).
-- unique(bundle): использованный набор не возвращается («потом — никогда» для легендарок).
create table public.season_bundles (
  season_id  bigint       primary key references public.seasons (id),
  bundle     integer      not null unique,
  created_at timestamptz  not null default now()
);
alter table public.season_bundles disable row level security;

-- student_equipment — что надето по слотам; variant — выбранный эмодзи статуса (миграция 008).
create table public.student_equipment (
  id          uuid         primary key default gen_random_uuid(),
  student_id  bigint       not null references public.students (telegram_id),
  slot        text         not null,
  item_code   text         not null references public.shop_items (item_code),
  variant     text,
  updated_at  timestamptz  not null default now(),
  created_at  timestamptz  not null default now(),
  unique (student_id, slot)
);
create index if not exists idx_student_equipment_student
  on public.student_equipment (student_id);
alter table public.student_equipment disable row level security;

-- student_showcase — витрина профиля: 3 слота, предмет ИЛИ достижение (миграция 009, S7).
-- Отдельная таблица, не расширение student_equipment: item_code там жёстко ссылается на
-- shop_items (FK), а витрина должна показывать ещё и student_achievements.achievement_code —
-- другое пространство кодов, одна FK-колонка не может ссылаться на две таблицы разом.
create table public.student_showcase (
  id          uuid         primary key default gen_random_uuid(),
  student_id  bigint       not null references public.students (telegram_id),
  position    smallint     not null check (position between 1 and 3),
  kind        text         not null check (kind in ('item', 'achievement')),
  ref_code    text         not null,
  updated_at  timestamptz  not null default now(),
  created_at  timestamptz  not null default now(),
  unique (student_id, position)
);
alter table public.student_showcase disable row level security;

-- --- Индексы (кроме автоматических для PK/UNIQUE и idx_students_telegram_id выше) -----

create index if not exists idx_assignments_activation
  on public.assignments (activation_status, scheduled_date);
create index if not exists idx_assignments_student_status
  on public.assignments (student_id, status);
create index if not exists idx_assignments_week
  on public.assignments (week_label, type);

-- История сезонов конкретного ученика («Сезон №N» в архиве профиля, миграция 005).
create index if not exists idx_season_results_student
  on public.season_results (student_id);

-- --- Функции -----------------------------------------------------------------

-- add_huikons — атомарное начисление/списание хуиконов (миграция 001, задача T5).
CREATE OR REPLACE FUNCTION public.add_huikons(p_student_id bigint, p_amount integer, p_reason text)
 RETURNS TABLE(actual_change integer, new_balance integer)
 LANGUAGE plpgsql
AS $function$
declare
  v_old_balance int;
  v_new_balance int;
begin
  select huikons into v_old_balance
    from students
    where telegram_id = p_student_id
    for update;

  if v_old_balance is null then
    raise exception 'Student % not found', p_student_id;
  end if;

  v_new_balance := greatest(0, v_old_balance + p_amount);

  update students set huikons = v_new_balance where telegram_id = p_student_id;

  insert into balance_history (student_id, change_amount, reason)
    values (p_student_id, v_new_balance - v_old_balance, p_reason);

  return query select (v_new_balance - v_old_balance), v_new_balance;
end;
$function$;

-- get_student_progress — сводка выданных/выполненных заданий по типам (используется родительским ботом).
CREATE OR REPLACE FUNCTION public.get_student_progress(p_student_id bigint)
 RETURNS TABLE(type text, issued bigint, completed bigint)
 LANGUAGE sql
 STABLE
AS $function$
  select
    a.type,
    count(*) filter (where a.activation_status = 'active') as issued,
    count(*) filter (where a.status = 'checked' and a.approval_status = 'approved') as completed
  from assignments a
  where a.student_id = p_student_id
  group by a.type;
$function$;

-- close_season — закрытие сезона одной транзакцией (миграция 006, задача G8):
-- архив итогов в season_results (места по rank(), равные очки = одно место),
-- награды топ-3 с ненулевыми очками (100/60/30, GAME_DESIGN.md §5) через add_huikons
-- (reason='season_place_N'), обнуление rating, end_date у закрытого сезона, открытие
-- следующего. Сезон, открытый сегодня, закрыть нельзя (защита от двойного клика).
-- Полная мотивация решений — в шапке миграции 006.
CREATE OR REPLACE FUNCTION public.close_season()
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
  v_season_id bigint;
  v_start_date date;
  v_today date := (now() at time zone 'Europe/Moscow')::date;
  v_archived integer;
  v_awarded integer := 0;
  v_reward integer;
  r record;
begin
  select id, start_date into v_season_id, v_start_date
    from seasons
    where end_date is null
    order by id desc
    limit 1
    for update;

  if v_season_id is null then
    raise exception 'Нет открытого сезона';
  end if;

  if v_start_date >= v_today then
    raise exception 'Сезон №% открыт сегодня — закрывать можно не раньше следующего дня', v_season_id;
  end if;

  -- Блокируем учеников до снимка очков (гонка с add_season_points, см. миграцию 006).
  perform 1 from students for update;

  insert into season_results (season_id, student_id, points, place)
  select v_season_id, s.telegram_id, s.rating,
         rank() over (order by s.rating desc)
    from students s;
  get diagnostics v_archived = row_count;

  for r in
    select student_id, place
      from season_results
      where season_id = v_season_id and place <= 3 and points > 0
  loop
    v_reward := case r.place when 1 then 100 when 2 then 60 else 30 end;
    perform add_huikons(r.student_id, v_reward, 'season_place_' || r.place);
    v_awarded := v_awarded + 1;
  end loop;

  update students set rating = 0 where rating <> 0;

  update seasons set end_date = v_today where id = v_season_id;

  insert into seasons (start_date) values (v_today);

  return json_build_object(
    'season_id', v_season_id,
    'archived', v_archived,
    'awarded', v_awarded
  );
end;
$function$;

-- buy_streak_shield — атомарная покупка щита стрика (миграция 007, задача G9): лимит 2,
-- цена 40 через add_huikons (reason='buy_streak_shield'), инкремент инвентаря. Мотивация
-- атомарности и блокировок — в шапке миграции 007.
CREATE OR REPLACE FUNCTION public.buy_streak_shield(p_student_id bigint)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
  v_price  integer := 40;
  v_max    integer := 2;
  v_qty    integer;
  v_balance integer;
  v_new_balance integer;
begin
  select quantity into v_qty
    from student_items
    where student_id = p_student_id and item_code = 'streak_shield'
    for update;
  if v_qty is null then v_qty := 0; end if;

  if v_qty >= v_max then
    raise exception 'Лимит: не больше % щитов в запасе', v_max;
  end if;

  select huikons into v_balance
    from students
    where telegram_id = p_student_id
    for update;
  if v_balance is null then
    raise exception 'Ученик % не найден', p_student_id;
  end if;
  if v_balance < v_price then
    raise exception 'Недостаточно бубликов: нужно %, есть %', v_price, v_balance;
  end if;

  select new_balance into v_new_balance
    from add_huikons(p_student_id, -v_price, 'buy_streak_shield');

  insert into student_items (student_id, item_code, quantity)
    values (p_student_id, 'streak_shield', 1)
    on conflict (student_id, item_code)
    do update set quantity = student_items.quantity + 1, updated_at = now();

  select quantity into v_qty
    from student_items
    where student_id = p_student_id and item_code = 'streak_shield';

  return json_build_object('quantity', v_qty, 'balance', v_new_balance);
end;
$function$;

-- consume_streak_shield — атомарно покрыть один пропущенный день щитом (миграция 007, G9).
-- Идемпотентно: true если день покрыт (сейчас или ранее), false если щита нет.
CREATE OR REPLACE FUNCTION public.consume_streak_shield(p_student_id bigint, p_bridged_date date)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
declare
  v_qty integer;
begin
  if exists (select 1 from streak_shield_uses
               where student_id = p_student_id and bridged_date = p_bridged_date) then
    return true;
  end if;

  select quantity into v_qty
    from student_items
    where student_id = p_student_id and item_code = 'streak_shield'
    for update;

  if v_qty is null or v_qty <= 0 then
    return false;
  end if;

  insert into streak_shield_uses (student_id, bridged_date)
    values (p_student_id, p_bridged_date)
    on conflict (student_id, bridged_date) do nothing;

  update student_items
    set quantity = quantity - 1, updated_at = now()
    where student_id = p_student_id and item_code = 'streak_shield';

  return true;
end;
$function$;

-- ensure_season_rotation / buy_item / equip_item — RPC магазина (миграция 008, задача S1).
-- Тела и мотивация решений — в миграции 008 (ленивое назначение бандла открытому сезону;
-- единая покупка с делегированием щита, явной проверкой баланса, gate по достижению и
-- автоэкипировкой; бесплатное переодевание купленного). Сид каталога — тоже в миграции 008.
CREATE OR REPLACE FUNCTION public.ensure_season_rotation()
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
declare
  v_season bigint;
  v_bundle integer;
begin
  select id into v_season from seasons where end_date is null order by id desc limit 1;
  if v_season is null then
    return null;
  end if;

  select bundle into v_bundle from season_bundles where season_id = v_season;
  if v_bundle is not null then
    return v_bundle;
  end if;

  select min(rotation_bundle) into v_bundle
    from shop_items
    where rotation_bundle is not null
      and active
      and rotation_bundle not in (select bundle from season_bundles);
  if v_bundle is null then
    return null;
  end if;

  insert into season_bundles (season_id, bundle)
    values (v_season, v_bundle)
    on conflict (season_id) do nothing;

  select bundle into v_bundle from season_bundles where season_id = v_season;
  return v_bundle;
end;
$function$;

CREATE OR REPLACE FUNCTION public.buy_item(p_student_id bigint, p_item_code text, p_variant text DEFAULT null)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
  v_item     shop_items%rowtype;
  v_bundle   integer;
  v_balance  integer;
  v_new_balance integer;
begin
  select * into v_item from shop_items where item_code = p_item_code and active;
  if v_item.item_code is null then
    raise exception 'Товар % не найден или снят с продажи', p_item_code;
  end if;

  if v_item.item_kind = 'shield' then
    return buy_streak_shield(p_student_id);
  end if;

  if v_item.availability = 'rotation' then
    v_bundle := ensure_season_rotation();
    if v_bundle is null or v_bundle <> v_item.rotation_bundle then
      raise exception 'Товар «%» сейчас не на витрине', v_item.name;
    end if;
  end if;

  if v_item.condition_achievement is not null then
    if not exists (select 1 from student_achievements
                     where student_id = p_student_id
                       and achievement_code = v_item.condition_achievement) then
      raise exception 'Для покупки «%» нужно достижение', v_item.name;
    end if;
  end if;

  if v_item.item_kind = 'service' then
    if p_variant is null or position(p_variant in coalesce(v_item.render_payload, '')) = 0 then
      raise exception 'Недопустимый вариант для «%»', v_item.name;
    end if;
  end if;

  if v_item.item_kind = 'cosmetic' then
    if exists (select 1 from student_items
                 where student_id = p_student_id and item_code = p_item_code) then
      raise exception 'Уже куплено';
    end if;
  end if;

  select huikons into v_balance from students where telegram_id = p_student_id for update;
  if v_balance is null then
    raise exception 'Ученик % не найден', p_student_id;
  end if;
  if v_balance < v_item.price then
    raise exception 'Недостаточно бубликов: нужно %, есть %', v_item.price, v_balance;
  end if;

  select new_balance into v_new_balance
    from add_huikons(p_student_id, -v_item.price, 'buy_' || p_item_code);

  if v_item.item_kind = 'cosmetic' then
    insert into student_items (student_id, item_code, quantity)
      values (p_student_id, p_item_code, 1);
    insert into student_equipment (student_id, slot, item_code)
      values (p_student_id, v_item.slot, p_item_code)
      on conflict (student_id, slot)
      do update set item_code = excluded.item_code, variant = null, updated_at = now();
  elsif v_item.item_kind = 'service' then
    insert into student_equipment (student_id, slot, item_code, variant)
      values (p_student_id, v_item.slot, p_item_code, p_variant)
      on conflict (student_id, slot)
      do update set item_code = excluded.item_code, variant = excluded.variant, updated_at = now();
  end if;

  return json_build_object('item_code', p_item_code, 'balance', v_new_balance);
end;
$function$;

CREATE OR REPLACE FUNCTION public.equip_item(p_student_id bigint, p_slot text, p_item_code text DEFAULT null)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
  v_slot text;
begin
  if p_item_code is null then
    delete from student_equipment where student_id = p_student_id and slot = p_slot;
    return;
  end if;

  if p_slot = 'status_emoji' then
    raise exception 'Эмодзи-статус меняется только покупкой смены';
  end if;

  select slot into v_slot from shop_items where item_code = p_item_code and active;
  if v_slot is null or v_slot <> p_slot then
    raise exception 'Товар % не подходит слоту %', p_item_code, p_slot;
  end if;

  if not exists (select 1 from student_items
                   where student_id = p_student_id and item_code = p_item_code) then
    raise exception 'Сначала нужно купить этот предмет';
  end if;

  insert into student_equipment (student_id, slot, item_code)
    values (p_student_id, p_slot, p_item_code)
    on conflict (student_id, slot)
    do update set item_code = excluded.item_code, variant = null, updated_at = now();
end;
$function$;

-- set_showcase — поставить/снять предмет витрины профиля (миграция 009, S7). p_ref_code=null
-- снимает слот; иначе проверяет владение (student_items) или получение (student_achievements)
-- в зависимости от p_kind перед апсертом. Мотивация отдельной таблицы — в шапке миграции 009.
CREATE OR REPLACE FUNCTION public.set_showcase(p_student_id bigint, p_position smallint, p_kind text, p_ref_code text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin
  if p_ref_code is null then
    delete from student_showcase where student_id = p_student_id and position = p_position;
    return;
  end if;

  if p_kind = 'item' then
    if not exists (select 1 from student_items where student_id = p_student_id and item_code = p_ref_code) then
      raise exception 'Предмет % не куплен', p_ref_code;
    end if;
  elsif p_kind = 'achievement' then
    if not exists (select 1 from student_achievements where student_id = p_student_id and achievement_code = p_ref_code) then
      raise exception 'Достижение % не получено', p_ref_code;
    end if;
  else
    raise exception 'Неизвестный тип витрины: %', p_kind;
  end if;

  insert into student_showcase (student_id, position, kind, ref_code)
    values (p_student_id, p_position, p_kind, p_ref_code)
    on conflict (student_id, position)
    do update set kind = excluded.kind, ref_code = excluded.ref_code, updated_at = now();
end;
$function$;

-- add_season_points — атомарное начисление очков сезона (миграция 005, задача G3).
-- PostgREST не умеет относительный update, поэтому rating = rating + N делается здесь.
-- Очки сезона — отдельная валюта от бубликов: в balance_history НЕ пишет.
CREATE OR REPLACE FUNCTION public.add_season_points(p_student_id bigint, p_amount integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
declare
  v_new integer;
begin
  update students
    set rating = greatest(0, rating + p_amount)
    where telegram_id = p_student_id
    returning rating into v_new;

  if v_new is null then
    raise exception 'Student % not found', p_student_id;
  end if;

  return v_new;
end;
$function$;
