-- Миграция 005 — ядро геймификации Bot 2.0: достижения, инвентарь, сезоны (задача G3)
--
-- Зачем: этап 1 (SPEC_STAGE1.md) вводит три механики, которым нужно хранилище:
--   * вехи стрика / достижения категории «Дисциплина» (разделы 4 и 6 спеки) —
--     разовая идемпотентная выдача наград;
--   * щит стрика (раздел 4) — первый и пока единственный предмет инвентаря;
--   * сезонные очки с архивом «Сезон №N» (раздел 3).
--
-- Существующие таблицы НЕ изменяются. Все внешние ключи — на students.telegram_id,
-- как во всём проекте (уникальный индекс idx_students_telegram_id).
--
-- RLS не включается ни на одной из новых таблиц — весь остальной проект открыт тем же
-- анонимным ключом (принятый риск, ROADMAP.md T10, тот же аргумент, что в миграции 004):
-- новые таблицы не создают дыры сверх уже существующей.
--
-- ---------------------------------------------------------------------------
-- РЕШЕНИЕ ПО ХРАНЕНИЮ ОЧКОВ СЕЗОНА (требование карточки G3 — обосновать здесь).
--
-- Выбран вариант: students.rating = «очки ТЕКУЩЕГО сезона» (обнуляется при закрытии
-- сезона) + таблицы seasons/season_results только для архива истории.
--
-- Почему так, а не полностью отдельное хранилище (student_season_points и т.п.):
--   1. rating сейчас — мёртвое поле: лидерборд (loadLeaderboard в index.html) уже
--      сортирует по нему, но его никто не начисляет. Переиспользование оживляет
--      существующий код вместо создания параллельного (конституция: использовать
--      существующее, не дублировать).
--   2. Горячий путь — лидерборд и профиль — остаётся запросом к одной таблице
--      students без join на «текущий сезон», меньше кода и меньше точек отказа.
--   3. BOT2_CONTEXT.md уже фиксирует это направление («rating в Bot 2.0 становится
--      очками сезона»); поле НЕ переименовывается (правило 3).
--   4. Отдельное хранилище дало бы историю «по событиям», но для фазы А (один общий
--      лидерборд, сезон = 2 недели) достаточно итоговой строки на ученика в сезоне —
--      это и хранит season_results. Пожертвовали: поштучным журналом начислений очков
--      (аналога balance_history для очков в этапе 1 нет — осознанное упрощение,
--      при необходимости добавляется отдельной таблицей позже, ничего не ломая).
--
-- Известный нюанс: у students.rating остался default 50 (наследие старой системы),
-- менять его нельзя (существующие таблицы не трогаем). Обрабатывается кодом в G7:
-- вставка нового ученика (loadProfile) передаёт rating явно, а закрытие сезона в любом
-- случае обнуляет rating всем.
-- ---------------------------------------------------------------------------

-- seasons — один ряд на сезон; id и есть «Сезон №N» в UI (identity, вставка раз в
-- 2 недели — пропуски номеров практически исключены). end_date is null = сезон идёт.
create table if not exists public.seasons (
  id          bigint       generated by default as identity primary key,
  start_date  date         not null,
  end_date    date,                              -- null, пока сезон не закрыт
  created_at  timestamptz  not null default now()
);

-- Страховка от двух «текущих» сезонов одновременно: открытым может быть только один.
create unique index if not exists idx_seasons_one_active
  on public.seasons ((true)) where end_date is null;

-- season_results — архив: итоговые очки и место ученика в закрытом сезоне.
-- Пишется один раз при закрытии сезона (G7), дальше только читается (история профиля).
create table if not exists public.season_results (
  id          uuid         primary key default gen_random_uuid(),
  season_id   bigint       not null references public.seasons (id),
  student_id  bigint       not null references public.students (telegram_id),
  points      integer      not null,
  place       integer      not null,
  created_at  timestamptz  not null default now(),
  unique (season_id, student_id)                 -- повторное закрытие сезона идемпотентно
);

-- История сезонов конкретного ученика («Сезон №N» в архиве профиля).
create index if not exists idx_season_results_student
  on public.season_results (student_id);

-- student_achievements — выданные достижения. Наличие строки = достижение получено;
-- строка одновременно служит флагом «право купить косметику» для магазина этапа 2
-- (streak_100 → рамка «100 дней огня», rebirth → Феникс), отдельного поля не нужно.
--
-- Вехи стрика и «дисциплинарные» достижения — ОДНО событие с ОДНИМ начислением
-- (решение зафиксировано в SPEC_STAGE1.md, раздел 6): одна строка на порог.
-- Коды этапа 1: first_step, streak_7, streak_30, streak_100, streak_200, streak_365,
-- perfect_month, rebirth. Справочник кодов живёт константой в коде (shared.js), не
-- таблицей — таблица-справочник понадобится не раньше магазина этапа 2.
--
-- Идемпотентная выдача (правило G5): insert ... on conflict do nothing, и только если
-- строка реально вставилась — начислять бублики через add_huikons. Уникальность по
-- (student_id, achievement_code) гарантирует «не выдать дважды» даже при гонке.
create table if not exists public.student_achievements (
  id                uuid         primary key default gen_random_uuid(),
  student_id        bigint       not null references public.students (telegram_id),
  achievement_code  text         not null,
  unlocked_at       timestamptz  not null default now(),
  unique (student_id, achievement_code)
);

-- student_items — инвентарь: количество предметов item_code у ученика.
-- Первый и пока единственный item_code — 'streak_shield' (щит стрика, 40 бубликов,
-- не больше 2 в запасе). Лимит «не больше 2» — правило конкретного товара, живёт в
-- RPC покупки (G9), а не в схеме; схема гарантирует только неотрицательность.
-- Покупка обязана идти через RPC, которая внутри своей транзакции вызывает add_huikons
-- (правило 2 BOT2_CONTEXT.md) — сама RPC проектируется в G9.
create table if not exists public.student_items (
  id          uuid         primary key default gen_random_uuid(),
  student_id  bigint       not null references public.students (telegram_id),
  item_code   text         not null,
  quantity    integer      not null default 0 check (quantity >= 0),
  updated_at  timestamptz  not null default now(),
  created_at  timestamptz  not null default now(),
  unique (student_id, item_code)
);

-- add_season_points — атомарное начисление очков сезона (аналог add_huikons).
-- Нужна, потому что PostgREST не умеет относительный update (rating = rating + N):
-- «прочитать-прибавить-записать» с клиента теряет обновления при двух начислениях
-- подряд (приём работы +10 и день стрика +2 в одном submitReview). Один UPDATE
-- атомарен сам по себе, select for update не требуется.
-- Очки сезона — отдельная валюта от бубликов: в balance_history НЕ пишет.
create or replace function public.add_season_points(p_student_id bigint, p_amount integer)
 returns integer
 language plpgsql
as $function$
declare
  v_new integer;
begin
  update students
    set rating = greatest(0, rating + p_amount)
    where telegram_id = p_student_id
    returning rating into v_new;

  if v_new is null then
    raise exception 'Student % not found', p_student_id;
  end if;

  return v_new;
end;
$function$;
