-- GENERATED by scripts/generate_season_v2_seed.mjs.
-- Canonical source: data/season_presets_2026_2027.json (schema 2, revision 4).
-- Do not hand-edit names, prices, rarity or render_payload in this file.

begin;

insert into public.season_v2_presets(
  preset_code, catalog_code, catalog_revision, sequence_no, competition_season_no,
  season_type, default_start_date, default_end_date, suggested_name, short_description,
  theme_key, economy_profile, pricing_status, collection_code, collection_bonus,
  collection_total_target, catalog_only)
values
  (
    'ca26_01_summer_practice', 'cosmic_academy_2026_2027_v2', 4,
    1, null, 'interseason',
    '2026-07-28'::date, '2026-08-01'::date,
    'Режим энергосбережения', 'Короткая летняя разминка без ручного запуска: спокойный режим, вода, блокнот и минимум лишнего шума.', 'energy_saving_mode',
    'summer', 'provisional', 'ca26_collection_01',
    50, 690, true
  ),
  (
    'ca26_02_before_start', 'cosmic_academy_2026_2027_v2', 4,
    2, null, 'interseason',
    '2026-08-01'::date, '2026-09-03'::date,
    'Нулевой заряд', 'Августовская подготовка к учебному году: вещи собраны, вкладки открыты, заряд уже закончился.', 'zero_charge',
    'summer', 'provisional', 'ca26_collection_02',
    50, 690, false
  ),
  (
    'ca26_03_new_route', 'cosmic_academy_2026_2027_v2', 4,
    3, 1, 'regular',
    '2026-09-03'::date, '2026-09-17'::date,
    'Неверный поворот', 'Первый учебный маршрут идёт не по плану, но именно это превращает ошибку в историю.', 'wrong_turn',
    'regular', 'recommended', 'ca26_collection_03',
    50, 740, false
  ),
  (
    'ca26_04_autumn_start', 'cosmic_academy_2026_2027_v2', 4,
    4, 2, 'regular',
    '2026-09-17'::date, '2026-10-01'::date,
    'Вне расписания', 'Расписание существует, однако кот, тени и осенний стол живут по собственному времени.', 'off_schedule',
    'regular', 'recommended', 'ca26_collection_04',
    50, 740, false
  ),
  (
    'ca26_05_leaf_geometry', 'cosmic_academy_2026_2027_v2', 4,
    5, 3, 'regular',
    '2026-10-01'::date, '2026-10-15'::date,
    'Протокол симметрии', 'Осенние листья, линейки и енот проверяют, насколько мир действительно симметричен.', 'symmetry_protocol',
    'regular', 'recommended', 'ca26_collection_05',
    50, 740, false
  ),
  (
    'ca26_06_rainy_tasks', 'cosmic_academy_2026_2027_v2', 4,
    6, 4, 'regular',
    '2026-10-15'::date, '2026-10-29'::date,
    'Дедлайн 23:59', 'Поздний дождь, окно и последняя минута перед отправкой работы в 23:59.', 'deadline_2359',
    'regular', 'recommended', 'ca26_collection_06',
    50, 740, false
  ),
  (
    'ca26_07_connection_points', 'cosmic_academy_2026_2027_v2', 4,
    7, 5, 'regular',
    '2026-10-29'::date, '2026-11-12'::date,
    'Сообщение доставлено', 'Бумажные сообщения, школьный двор и связь, которая работает без понятного адреса.', 'message_delivered',
    'regular', 'recommended', 'ca26_collection_07',
    50, 740, false
  ),
  (
    'ca26_08_light_in_window', 'cosmic_academy_2026_2027_v2', 4,
    8, 6, 'regular',
    '2026-11-12'::date, '2026-11-26'::date,
    'Ночная смена', 'Тихий ноябрьский вечер, одна лампа и существа, которые просыпаются после полуночи.', 'night_shift',
    'regular', 'recommended', 'ca26_collection_08',
    50, 740, false
  ),
  (
    'ca26_09_first_snow', 'cosmic_academy_2026_2027_v2', 4,
    9, 7, 'regular',
    '2026-11-26'::date, '2026-12-10'::date,
    'Холодный статик', 'Первый серьёзный холод превращает знакомый двор в кристаллическую помеху.', 'cold_static',
    'regular', 'recommended', 'ca26_collection_09',
    50, 740, false
  ),
  (
    'ca26_10_pre_new_year_countdown', 'cosmic_academy_2026_2027_v2', 4,
    10, 8, 'regular',
    '2026-12-10'::date, '2026-12-24'::date,
    'Ещё пять минут', 'Декабрьский таймер показывает пять минут, которые почему-то повторяются снова.', 'five_more_minutes',
    'regular', 'recommended', 'ca26_collection_10',
    50, 740, false
  ),
  (
    'ca26_11_new_year_workshop', 'cosmic_academy_2026_2027_v2', 4,
    11, 9, 'regular',
    '2026-12-24'::date, '2027-01-07'::date,
    'Гирлянда 00:00', 'Новогодний период с живой гирляндой, архивом года и мягким светом вместо визуального шума.', 'garland_0000',
    'regular', 'recommended', 'ca26_collection_11',
    50, 740, false
  ),
  (
    'ca26_12_frosty_start', 'cosmic_academy_2026_2027_v2', 4,
    12, 10, 'regular',
    '2027-01-07'::date, '2027-01-21'::date,
    'Слабая частота', 'После каникул связь с расписанием восстанавливается медленно и не на всех частотах.', 'weak_frequency',
    'regular', 'recommended', 'ca26_collection_12',
    50, 740, false
  ),
  (
    'ca26_13_clean_sheet', 'cosmic_academy_2026_2027_v2', 4,
    13, 11, 'regular',
    '2027-01-21'::date, '2027-02-04'::date,
    'Ошибка на полях', 'Чистый лист быстро обрастает пометками, скотчем и случайной кляксой, ставшей главным элементом.', 'margin_error',
    'regular', 'recommended', 'ca26_collection_13',
    50, 740, false
  ),
  (
    'ca26_14_february_rhythm', 'cosmic_academy_2026_2027_v2', 4,
    14, 12, 'regular',
    '2027-02-04'::date, '2027-02-18'::date,
    'Восемь вкладок', 'Февраль держится на восьми вкладках, уведомлениях и попытке заниматься сразу всем.', 'eight_tabs',
    'regular', 'recommended', 'ca26_collection_14',
    50, 740, false
  ),
  (
    'ca26_15_strength_of_character', 'cosmic_academy_2026_2027_v2', 4,
    15, 13, 'regular',
    '2027-02-18'::date, '2027-03-04'::date,
    'Ещё попытка', 'Конец зимы проверяет не идеальность результата, а готовность сделать ещё одну попытку.', 'retry',
    'regular', 'recommended', 'ca26_collection_15',
    50, 740, false
  ),
  (
    'ca26_16_spring_inspiration', 'cosmic_academy_2026_2027_v2', 4,
    16, 14, 'regular',
    '2027-03-04'::date, '2027-03-18'::date,
    'Новый рост', 'Весенняя мастерская оживает: ростки, вода, новые идеи и свет, который наконец стал длиннее.', 'new_growth',
    'regular', 'recommended', 'ca26_collection_16',
    50, 740, false
  ),
  (
    'ca26_17_balance_point', 'cosmic_academy_2026_2027_v2', 4,
    17, 15, 'regular',
    '2027-03-18'::date, '2027-04-01'::date,
    'Точка равновесия', 'Керамика, дерево и наклонная библиотека удерживают равновесие без лишней серьёзности.', 'balance_point',
    'regular', 'recommended', 'ca26_collection_17',
    50, 740, false
  ),
  (
    'ca26_18_time_of_firsts', 'cosmic_academy_2026_2027_v2', 4,
    18, 16, 'regular',
    '2027-04-01'::date, '2027-04-15'::date,
    'Турист с Альфы-7', 'Первоапрельский гость с Альфы-7 принимает школьный двор за космодром и остаётся до звонка.', 'alpha_7_tourist',
    'regular', 'recommended', 'ca26_collection_18',
    50, 740, false
  ),
  (
    'ca26_19_april_geometry', 'cosmic_academy_2026_2027_v2', 4,
    19, 17, 'regular',
    '2027-04-15'::date, '2027-04-29'::date,
    'Метод тыка', 'Апрельские отражения исследуются самым честным способом — сначала проверить лужу, потом строить теорию.', 'poke_method',
    'regular', 'recommended', 'ca26_collection_19',
    50, 740, false
  ),
  (
    'ca26_20_may_spring', 'cosmic_academy_2026_2027_v2', 4,
    20, 18, 'regular',
    '2027-04-29'::date, '2027-05-13'::date,
    'Локальный дождь', 'Карты давления и локальное облако объясняют майскую погоду лучше любого прогноза.', 'local_rain',
    'regular', 'recommended', 'ca26_collection_20',
    50, 740, false
  ),
  (
    'ca26_21_last_bell', 'cosmic_academy_2026_2027_v2', 4,
    21, 19, 'regular',
    '2027-05-13'::date, '2027-05-27'::date,
    'Вышел первым', 'После последнего звонка класс пустеет быстрее, чем успевает обновиться расписание.', 'first_out',
    'regular', 'recommended', 'ca26_collection_21',
    50, 740, false
  ),
  (
    'ca26_22_exam_sprint', 'cosmic_academy_2026_2027_v2', 4,
    22, 20, 'regular',
    '2027-05-27'::date, '2027-06-10'::date,
    'Загрузка 2%', 'Экзаменационный терминал показывает два процента и принципиально не сообщает оставшееся время.', 'loading_2_percent',
    'regular', 'recommended', 'ca26_collection_22',
    50, 740, false
  ),
  (
    'ca26_23_beginning_of_summer', 'cosmic_academy_2026_2027_v2', 4,
    23, 21, 'regular',
    '2027-06-10'::date, '2027-06-24'::date,
    'Официально свободен', 'Учебный год ещё формально идёт, но рюкзак, поезд и мысли уже добрались до моря.', 'officially_free',
    'regular', 'recommended', 'ca26_collection_23',
    50, 740, false
  )
on conflict (preset_code) do update set
  catalog_code = excluded.catalog_code,
  catalog_revision = excluded.catalog_revision,
  sequence_no = excluded.sequence_no,
  competition_season_no = excluded.competition_season_no,
  season_type = excluded.season_type,
  default_start_date = excluded.default_start_date,
  default_end_date = excluded.default_end_date,
  suggested_name = excluded.suggested_name,
  short_description = excluded.short_description,
  theme_key = excluded.theme_key,
  economy_profile = excluded.economy_profile,
  pricing_status = excluded.pricing_status,
  collection_code = excluded.collection_code,
  collection_bonus = excluded.collection_bonus,
  collection_total_target = excluded.collection_total_target,
  catalog_only = excluded.catalog_only,
  updated_at = now();

insert into public.season_v2_preset_items(
  preset_code, item_code, slot, item_kind, name, description, rarity, price, currency,
  asset_key, render_payload, visual_key, motion_policy, sort_order)
values
  (
    'ca26_01_summer_practice', 'ca26_01_avatar_field_notebook', 'avatar', 'cosmetic',
    'Режим энергосбережения', 'Капибара сохраняет спокойствие, даже когда календарь уже нет.', 'legendary', 300,
    'gears', 'ca26_01_avatar_field_notebook', 'avatar_v4_capybara', 'capybara',
    'expressive', 10
  ),
  (
    'ca26_01_summer_practice', 'ca26_01_frame_sun_route', 'frame', 'cosmetic',
    'Солнечный маршрут', 'Тёплый плетёный шнур, сквозь который проходит холодная бирюзовая жила.', 'rare', 130,
    'gears', 'ca26_01_frame_sun_route', 'frame_v4_sun_route', 'sun_route',
    'static', 20
  ),
  (
    'ca26_01_summer_practice', 'ca26_01_title_field_researcher', 'title', 'cosmetic',
    'Почти занимаюсь', 'Спокойный титул без эффектов.', 'common', 90,
    'gears', 'ca26_01_title_field_researcher', 'title_v4_01_plain', 'plain',
    'static', 30
  ),
  (
    'ca26_01_summer_practice', 'ca26_01_background_summer_notes', 'background', 'cosmetic',
    'Полевые заметки', 'Солнечный стол у воды, снятый сверху.', 'epic', 170,
    'gears', 'ca26_01_background_summer_notes', 'scene_v4_field_notes', 'field_notes',
    'subtle', 40
  ),
  (
    'ca26_02_before_start', 'ca26_02_avatar_paper_planner', 'avatar', 'cosmetic',
    'Нулевой заряд', 'Хомяк собрал всё необходимое и потратил заряд ещё до старта.', 'rare', 130,
    'gears', 'ca26_02_avatar_paper_planner', 'avatar_v4_hamster', 'hamster',
    'static', 10
  ),
  (
    'ca26_02_before_start', 'ca26_02_frame_checkpoint_flight', 'frame', 'cosmetic',
    'Бумажный след', 'Мягкий рваный край бумаги удерживает непрерывная графитовая нить.', 'common', 90,
    'gears', 'ca26_02_frame_checkpoint_flight', 'frame_v4_paper_trace', 'paper_trace',
    'static', 20
  ),
  (
    'ca26_02_before_start', 'ca26_02_title_ready_to_start', 'title', 'cosmetic',
    'План был', 'Мягкий градиент для хорошего, но изменившегося плана.', 'epic', 170,
    'gears', 'ca26_02_title_ready_to_start', 'title_v4_02_pulse', 'pulse',
    'subtle', 30
  ),
  (
    'ca26_02_before_start', 'ca26_02_background_august_plan', 'background', 'cosmetic',
    'Пол комнаты', 'Рюкзак, кабели и вещи перед стартом года.', 'legendary', 300,
    'gears', 'ca26_02_background_august_plan', 'scene_v4_packing_floor', 'packing_floor',
    'expressive', 40
  ),
  (
    'ca26_03_new_route', 'ca26_03_avatar_route_notebook', 'avatar', 'cosmetic',
    'Неверный корпус', 'Бип снова вошёл не в ту дверь, но делает вид, что так и надо.', 'common', 100,
    'gears', 'ca26_03_avatar_route_notebook', 'avatar_v4_alien', 'alien',
    'static', 10
  ),
  (
    'ca26_03_new_route', 'ca26_03_frame_start_line', 'frame', 'cosmetic',
    'Неверный поворот', 'Три гибких неоновых кабеля пересекаются и собираются в один узел.', 'epic', 180,
    'gears', 'ca26_03_frame_start_line', 'frame_v4_wrong_turn', 'wrong_turn',
    'subtle', 20
  ),
  (
    'ca26_03_new_route', 'ca26_03_title_route_author', 'title', 'cosmetic',
    'Не туда, но вовремя', 'Легендарный титул иногда сбивается на координаты.', 'legendary', 320,
    'gears', 'ca26_03_title_route_author', 'title_v4_03_signal', 'signal',
    'expressive', 30
  ),
  (
    'ca26_03_new_route', 'ca26_03_background_new_path_map', 'background', 'cosmetic',
    'Коридор Б-0', 'Школьный коридор с невозможной точкой схода.', 'rare', 140,
    'gears', 'ca26_03_background_new_path_map', 'scene_v4_wrong_corridor', 'wrong_corridor',
    'static', 40
  ),
  (
    'ca26_04_autumn_start', 'ca26_04_avatar_autumn_planner', 'avatar', 'cosmetic',
    'Вне расписания', 'Кот использует расписание исключительно как поверхность для сна.', 'epic', 180,
    'gears', 'ca26_04_avatar_autumn_planner', 'avatar_v4_schedule_cat', 'schedule_cat',
    'subtle', 10
  ),
  (
    'ca26_04_autumn_start', 'ca26_04_frame_autumn_rhythm', 'frame', 'cosmetic',
    'Осенний импульс', 'Живой венок из крупных янтарных, красных и зелёных листьев.', 'legendary', 320,
    'gears', 'ca26_04_frame_autumn_rhythm', 'frame_v4_autumn_orbit', 'autumn_orbit',
    'expressive', 20
  ),
  (
    'ca26_04_autumn_start', 'ca26_04_title_order_keeper', 'title', 'cosmetic',
    'Вне расписания', 'Сдержанный моноширинный статус.', 'rare', 140,
    'gears', 'ca26_04_title_order_keeper', 'title_v4_04_mono', 'mono',
    'static', 30
  ),
  (
    'ca26_04_autumn_start', 'ca26_04_background_autumn_schedule', 'background', 'cosmetic',
    'Стол вне расписания', 'Календарь, тени жалюзи и смятый лист.', 'common', 100,
    'gears', 'ca26_04_background_autumn_schedule', 'scene_v4_schedule_desk', 'schedule_desk',
    'static', 40
  ),
  (
    'ca26_05_leaf_geometry', 'ca26_05_avatar_symmetry_leaf', 'avatar', 'cosmetic',
    'Протокол симметрии', 'Енот проверяет мир линейкой и находит подозрительно ровные совпадения.', 'legendary', 320,
    'gears', 'ca26_05_avatar_symmetry_leaf', 'avatar_v4_raccoon', 'raccoon',
    'expressive', 10
  ),
  (
    'ca26_05_leaf_geometry', 'ca26_05_frame_leaf_symmetry', 'frame', 'cosmetic',
    'Четыре оси', 'Цельный безель из потемневшей латуни с холодным внутренним кантом.', 'rare', 140,
    'gears', 'ca26_05_frame_leaf_symmetry', 'frame_v4_axis', 'axis',
    'static', 20
  ),
  (
    'ca26_05_leaf_geometry', 'ca26_05_title_symmetry_master', 'title', 'cosmetic',
    'Сходится по осям', 'Короткий спокойный титул.', 'common', 100,
    'gears', 'ca26_05_title_symmetry_master', 'title_v4_05_plain', 'plain',
    'static', 30
  ),
  (
    'ca26_05_leaf_geometry', 'ca26_05_background_leaf_fall_symmetry', 'background', 'cosmetic',
    'Осенний переход', 'Мокрая улица, разметка и листья под ногами.', 'epic', 180,
    'gears', 'ca26_05_background_leaf_fall_symmetry', 'scene_v4_autumn_crosswalk', 'autumn_crosswalk',
    'subtle', 40
  ),
  (
    'ca26_06_rainy_tasks', 'ca26_06_avatar_window_lamp', 'avatar', 'cosmetic',
    'Дедлайн 23:59', 'Ква сохраняет невозмутимость за минуту до отправки.', 'rare', 140,
    'gears', 'ca26_06_avatar_window_lamp', 'avatar_v4_frog', 'frog',
    'static', 10
  ),
  (
    'ca26_06_rainy_tasks', 'ca26_06_frame_rain_arcs', 'frame', 'cosmetic',
    'Дождевая линия', 'Прозрачная водяная трубка, на которой держатся крупные капли.', 'common', 100,
    'gears', 'ca26_06_frame_rain_arcs', 'frame_v4_rainline', 'rainline',
    'static', 20
  ),
  (
    'ca26_06_rainy_tasks', 'ca26_06_title_task_solver', 'title', 'cosmetic',
    'Сейчас всё решу', 'Эпический текст едва заметно набирает яркость.', 'epic', 180,
    'gears', 'ca26_06_title_task_solver', 'title_v4_06_pulse', 'pulse',
    'subtle', 30
  ),
  (
    'ca26_06_rainy_tasks', 'ca26_06_background_rain_at_window', 'background', 'cosmetic',
    'Остановка под дождём', 'Стекло павильона и отражения позднего автобуса.', 'legendary', 320,
    'gears', 'ca26_06_background_rain_at_window', 'scene_v4_rain_shelter', 'rain_shelter',
    'expressive', 40
  ),
  (
    'ca26_07_connection_points', 'ca26_07_avatar_connection_map', 'avatar', 'cosmetic',
    'Сообщение доставлено', 'Шифр доставил записку. Адрес выбирался интуитивно.', 'common', 100,
    'gears', 'ca26_07_avatar_connection_map', 'avatar_v4_pigeon', 'pigeon',
    'static', 10
  ),
  (
    'ca26_07_connection_points', 'ca26_07_frame_team_nodes', 'frame', 'cosmetic',
    'Потерянное письмо', 'Почтовая окантовка из красных, молочных и синих бумажных полос.', 'epic', 180,
    'gears', 'ca26_07_frame_team_nodes', 'frame_v4_dead_letter', 'dead_letter',
    'subtle', 20
  ),
  (
    'ca26_07_connection_points', 'ca26_07_title_linking_point', 'title', 'cosmetic',
    'Доставлено без адреса', 'Легендарный статус оставляет короткий след отправки.', 'legendary', 320,
    'gears', 'ca26_07_title_linking_point', 'title_v4_07_signal', 'signal',
    'expressive', 30
  ),
  (
    'ca26_07_connection_points', 'ca26_07_background_late_autumn_map', 'background', 'cosmetic',
    'Двор на частоте', 'Школьный двор, провода и самодельная антенна.', 'rare', 140,
    'gears', 'ca26_07_background_late_autumn_map', 'scene_v4_courtyard_radio', 'courtyard_radio',
    'static', 40
  ),
  (
    'ca26_08_light_in_window', 'ca26_08_avatar_warm_window', 'avatar', 'cosmetic',
    'Ночная смена', 'Люмен включается только после того, как остальные выключили свет.', 'epic', 180,
    'gears', 'ca26_08_avatar_warm_window', 'avatar_v4_moth', 'moth',
    'subtle', 10
  ),
  (
    'ca26_08_light_in_window', 'ca26_08_frame_lamp_light', 'frame', 'cosmetic',
    'Последний свет', 'Широкий витражный обод собирает фиолетовый сумрак и янтарный свет.', 'legendary', 320,
    'gears', 'ca26_08_frame_lamp_light', 'frame_v4_last_light', 'last_light',
    'expressive', 20
  ),
  (
    'ca26_08_light_in_window', 'ca26_08_title_bright_idea', 'title', 'cosmetic',
    'Последний свет', 'Холодная подпись без движения.', 'rare', 140,
    'gears', 'ca26_08_title_bright_idea', 'title_v4_08_mono', 'mono',
    'static', 30
  ),
  (
    'ca26_08_light_in_window', 'ca26_08_background_evening_notebook', 'background', 'cosmetic',
    'Окно после полуночи', 'Тёмная комната и единственная включённая лампа.', 'common', 100,
    'gears', 'ca26_08_background_evening_notebook', 'scene_v4_night_window', 'night_window',
    'static', 40
  ),
  (
    'ca26_09_first_snow', 'ca26_09_avatar_snow_crystal', 'avatar', 'cosmetic',
    'Не тает', 'Шурх пережил контрольную, оттепель и чужой прогноз.', 'legendary', 320,
    'gears', 'ca26_09_avatar_snow_crystal', 'avatar_v4_snow_blob', 'snow_blob',
    'expressive', 10
  ),
  (
    'ca26_09_first_snow', 'ca26_09_frame_first_crystal', 'frame', 'cosmetic',
    'Холодный статик', 'Кристаллическая корона с острыми ледяными помехами.', 'rare', 140,
    'gears', 'ca26_09_frame_first_crystal', 'frame_v4_cold_static', 'cold_static',
    'static', 20
  ),
  (
    'ca26_09_first_snow', 'ca26_09_title_winter_guide', 'title', 'cosmetic',
    'Не растаял', 'Статичный зимний титул.', 'common', 100,
    'gears', 'ca26_09_title_winter_guide', 'title_v4_09_plain', 'plain',
    'static', 30
  ),
  (
    'ca26_09_first_snow', 'ca26_09_background_first_snowfall', 'background', 'cosmetic',
    'Белый двор', 'Знакомый двор, почти исчезнувший под снегом.', 'epic', 180,
    'gears', 'ca26_09_background_first_snowfall', 'scene_v4_snow_yard', 'snow_yard',
    'subtle', 40
  ),
  (
    'ca26_10_pre_new_year_countdown', 'ca26_10_avatar_december_clock', 'avatar', 'cosmetic',
    'Ещё пять минут', 'Тик переносит будильник с профессиональной точностью.', 'rare', 140,
    'gears', 'ca26_10_avatar_december_clock', 'avatar_v4_clock', 'clock',
    'static', 10
  ),
  (
    'ca26_10_pre_new_year_countdown', 'ca26_10_frame_countdown_ring', 'frame', 'cosmetic',
    'Обратный отсчёт', 'Мягкий красный безель таймера стянут тонкой жёлтой разметкой.', 'common', 100,
    'gears', 'ca26_10_frame_countdown_ring', 'frame_v4_countdown', 'countdown',
    'static', 20
  ),
  (
    'ca26_10_pre_new_year_countdown', 'ca26_10_title_countdown_master', 'title', 'cosmetic',
    'Ещё пять минут', 'Индикатор времени проходит по буквам.', 'epic', 180,
    'gears', 'ca26_10_title_countdown_master', 'title_v4_10_pulse', 'pulse',
    'subtle', 30
  ),
  (
    'ca26_10_pre_new_year_countdown', 'ca26_10_background_december_countdown', 'background', 'cosmetic',
    'Комната 00:05', 'Красные цифры и тени перед дедлайном.', 'legendary', 320,
    'gears', 'ca26_10_background_december_countdown', 'scene_v4_countdown_room', 'countdown_room',
    'expressive', 40
  ),
  (
    'ca26_11_new_year_workshop', 'ca26_11_avatar_holiday_workshop', 'avatar', 'cosmetic',
    'Архив.zip', 'Упаковывает незакрытые задачи в папку, которую никто не откроет.', 'common', 100,
    'gears', 'ca26_11_avatar_holiday_workshop', 'avatar_v4_gift', 'gift',
    'static', 10
  ),
  (
    'ca26_11_new_year_workshop', 'ca26_11_frame_festive_garland', 'frame', 'cosmetic',
    'Гирлянда 00:00', 'Хвойное плетение с небольшими разноцветными лампочками и мягким праздничным свечением.', 'epic', 180,
    'gears', 'ca26_11_frame_festive_garland', 'frame_v4_new_year_lights', 'new_year_lights',
    'subtle', 20
  ),
  (
    'ca26_11_new_year_workshop', 'ca26_11_title_new_year_master', 'title', 'cosmetic',
    'Архив закрыт', 'Легендарный титул на мгновение показывает системный код.', 'legendary', 320,
    'gears', 'ca26_11_title_new_year_master', 'title_v4_11_glitch', 'glitch',
    'expressive', 30
  ),
  (
    'ca26_11_new_year_workshop', 'ca26_11_background_festive_workshop', 'background', 'cosmetic',
    'Закрытый архив', 'Полки, коробки и свет дежурной лампы.', 'rare', 140,
    'gears', 'ca26_11_background_festive_workshop', 'scene_v4_archive_room', 'archive_room',
    'static', 40
  ),
  (
    'ca26_12_frosty_start', 'ca26_12_avatar_frost_window', 'avatar', 'cosmetic',
    'Слабый сигнал', 'Одна антенна ловит связь, вторая всё ещё загружается.', 'epic', 180,
    'gears', 'ca26_12_avatar_frost_window', 'avatar_v4_frozen_alien', 'frozen_alien',
    'subtle', 10
  ),
  (
    'ca26_12_frosty_start', 'ca26_12_frame_frost_pattern', 'frame', 'cosmetic',
    'Слабая частота', 'Спутанный пучок проводов: две жилы светятся, две остаются холодными.', 'legendary', 320,
    'gears', 'ca26_12_frame_frost_pattern', 'frame_v4_weak_signal', 'weak_signal',
    'expressive', 20
  ),
  (
    'ca26_12_frosty_start', 'ca26_12_title_frost_endurance', 'title', 'cosmetic',
    'Сигнал нестабилен', 'Редкая подпись с техническим ритмом.', 'rare', 140,
    'gears', 'ca26_12_title_frost_endurance', 'title_v4_12_mono', 'mono',
    'static', 30
  ),
  (
    'ca26_12_frosty_start', 'ca26_12_background_frosty_morning', 'background', 'cosmetic',
    'Замёрзшее стекло', 'Остановка видна только через очищенный участок.', 'common', 100,
    'gears', 'ca26_12_background_frosty_morning', 'scene_v4_frosted_stop', 'frosted_stop',
    'static', 40
  ),
  (
    'ca26_13_clean_sheet', 'ca26_13_avatar_clean_page', 'avatar', 'cosmetic',
    'Ошибка на полях', 'Клякса появилась случайно и быстро стала главным элементом страницы.', 'legendary', 320,
    'gears', 'ca26_13_avatar_clean_page', 'avatar_v4_ink_blob', 'ink_blob',
    'expressive', 10
  ),
  (
    'ca26_13_clean_sheet', 'ca26_13_frame_notebook_margins', 'frame', 'cosmetic',
    'Поля документа', 'Рваное бумажное волокно перехвачено синей строчкой и красной линией.', 'rare', 140,
    'gears', 'ca26_13_frame_notebook_margins', 'frame_v4_margin_error', 'margin_error',
    'static', 20
  ),
  (
    'ca26_13_clean_sheet', 'ca26_13_title_page_author', 'title', 'cosmetic',
    'Начну с точки', 'Минимальный титул без анимации.', 'common', 100,
    'gears', 'ca26_13_title_page_author', 'title_v4_13_plain', 'plain',
    'static', 30
  ),
  (
    'ca26_13_clean_sheet', 'ca26_13_background_white_page', 'background', 'cosmetic',
    'Бумажное пространство', 'Листы, скотч и чернильные следы без горизонта.', 'epic', 180,
    'gears', 'ca26_13_background_white_page', 'scene_v4_paper_space', 'paper_space',
    'subtle', 40
  ),
  (
    'ca26_14_february_rhythm', 'ca26_14_avatar_study_metronome', 'avatar', 'cosmetic',
    'Восемь вкладок', 'Семь дел открыты. Восьмое уверенно воспроизводит музыку.', 'rare', 140,
    'gears', 'ca26_14_avatar_study_metronome', 'avatar_v4_octopus', 'octopus',
    'static', 10
  ),
  (
    'ca26_14_february_rhythm', 'ca26_14_frame_week_rhythm', 'frame', 'cosmetic',
    'Многооконный режим', 'Три полупрозрачных окна наложились друг на друга и потеряли правильную форму.', 'common', 100,
    'gears', 'ca26_14_frame_week_rhythm', 'frame_v4_multitask', 'multitask',
    'static', 20
  ),
  (
    'ca26_14_february_rhythm', 'ca26_14_title_rhythm_keeper', 'title', 'cosmetic',
    'Восемь вкладок', 'Эпическая смена оттенка между активными задачами.', 'epic', 180,
    'gears', 'ca26_14_title_rhythm_keeper', 'title_v4_14_pulse', 'pulse',
    'subtle', 30
  ),
  (
    'ca26_14_february_rhythm', 'ca26_14_background_winter_schedule', 'background', 'cosmetic',
    'Перегрузка вкладок', 'Рабочий стол, окна и уведомления поверх друг друга.', 'legendary', 320,
    'gears', 'ca26_14_background_winter_schedule', 'scene_v4_tab_overload', 'tab_overload',
    'expressive', 40
  ),
  (
    'ca26_15_strength_of_character', 'ca26_15_avatar_support_point', 'avatar', 'cosmetic',
    'Ещё попытка', 'Тягач снова идёт вверх, не обсуждая прошлый результат.', 'common', 100,
    'gears', 'ca26_15_avatar_support_point', 'avatar_v4_beetle', 'beetle',
    'static', 10
  ),
  (
    'ca26_15_strength_of_character', 'ca26_15_frame_resilience_contour', 'frame', 'cosmetic',
    'Повтор', 'Плотно переплетённый шнур возвращает узор к началу.', 'epic', 180,
    'gears', 'ca26_15_frame_resilience_contour', 'frame_v4_retry', 'retry',
    'subtle', 20
  ),
  (
    'ca26_15_strength_of_character', 'ca26_15_title_reliable_support', 'title', 'cosmetic',
    'Ещё один шаг', 'Легендарная строка продвигает световой маркер вперёд.', 'legendary', 320,
    'gears', 'ca26_15_title_reliable_support', 'title_v4_15_signal', 'signal',
    'expressive', 30
  ),
  (
    'ca26_15_strength_of_character', 'ca26_15_background_resilience_line', 'background', 'cosmetic',
    'Наклонная страница', 'Тетрадный лист превращается в крутой подъём.', 'rare', 140,
    'gears', 'ca26_15_background_resilience_line', 'scene_v4_notebook_slope', 'notebook_slope',
    'static', 40
  ),
  (
    'ca26_16_spring_inspiration', 'ca26_16_avatar_spring_sprout', 'avatar', 'cosmetic',
    'Новый рост', 'Пиксель вышел за границы рисунка и отказался возвращаться.', 'epic', 180,
    'gears', 'ca26_16_avatar_spring_sprout', 'avatar_v4_sprout', 'sprout',
    'subtle', 10
  ),
  (
    'ca26_16_spring_inspiration', 'ca26_16_frame_growth_lines', 'frame', 'cosmetic',
    'Хлорофилл', 'Плетёная лоза с крупными цветами, листьями и мягким зелёным свечением.', 'legendary', 320,
    'gears', 'ca26_16_frame_growth_lines', 'frame_v4_chlorophyll', 'chlorophyll',
    'expressive', 20
  ),
  (
    'ca26_16_spring_inspiration', 'ca26_16_title_source_of_ideas', 'title', 'cosmetic',
    'Есть идея', 'Короткий редкий титул.', 'rare', 140,
    'gears', 'ca26_16_title_source_of_ideas', 'title_v4_16_mono', 'mono',
    'static', 30
  ),
  (
    'ca26_16_spring_inspiration', 'ca26_16_background_spring_light', 'background', 'cosmetic',
    'Весенняя мастерская', 'Растения, банки с водой и холодный дневной свет.', 'common', 100,
    'gears', 'ca26_16_background_spring_light', 'scene_v4_spring_workshop', 'spring_workshop',
    'static', 40
  ),
  (
    'ca26_17_balance_point', 'ca26_17_avatar_balance_disc', 'avatar', 'cosmetic',
    'Держится', 'Полка уже накренилась, но Баланс сохраняет выражение лица.', 'legendary', 320,
    'gears', 'ca26_17_avatar_balance_disc', 'avatar_v4_balance_cat', 'balance_cat',
    'expressive', 10
  ),
  (
    'ca26_17_balance_point', 'ca26_17_frame_balance_circle', 'frame', 'cosmetic',
    'Точка равновесия', 'Цельный обод разделён между холодной керамикой и тёплым деревом.', 'rare', 140,
    'gears', 'ca26_17_frame_balance_circle', 'frame_v4_balance', 'balance',
    'static', 20
  ),
  (
    'ca26_17_balance_point', 'ca26_17_title_balance_keeper', 'title', 'cosmetic',
    'Держу баланс', 'Статичный статус без декоративного шума.', 'common', 100,
    'gears', 'ca26_17_title_balance_keeper', 'title_v4_17_plain', 'plain',
    'static', 30
  ),
  (
    'ca26_17_balance_point', 'ca26_17_background_equinox_day', 'background', 'cosmetic',
    'Наклонная библиотека', 'Стеллажи уходят в сторону, сохраняя порядок.', 'epic', 180,
    'gears', 'ca26_17_background_equinox_day', 'scene_v4_leaning_library', 'leaning_library',
    'subtle', 40
  ),
  (
    'ca26_18_time_of_firsts', 'ca26_18_avatar_launch_researcher', 'avatar', 'cosmetic',
    'Турист с Альфы-7', 'Перепутал школьный двор с космодромом и решил остаться.', 'rare', 140,
    'gears', 'ca26_18_avatar_launch_researcher', 'avatar_v4_space_tourist', 'space_tourist',
    'static', 10
  ),
  (
    'ca26_18_time_of_firsts', 'ca26_18_frame_launch_trajectory', 'frame', 'cosmetic',
    'Маршрут Альфы', 'Три тонких эластичных шнура оборачиваются вокруг аватара по разным траекториям.', 'common', 100,
    'gears', 'ca26_18_frame_launch_trajectory', 'frame_v4_alpha_route', 'alpha_route',
    'static', 20
  ),
  (
    'ca26_18_time_of_firsts', 'ca26_18_title_one_step_ahead', 'title', 'cosmetic',
    'Первый пошёл', 'Эпический стартовый импульс.', 'epic', 180,
    'gears', 'ca26_18_title_one_step_ahead', 'title_v4_18_pulse', 'pulse',
    'subtle', 30
  ),
  (
    'ca26_18_time_of_firsts', 'ca26_18_background_academy_launch', 'background', 'cosmetic',
    'Альфа-7', 'Орбита, холодный свет и чужая геометрия.', 'legendary', 320,
    'gears', 'ca26_18_background_academy_launch', 'scene_v4_orbital', 'orbital',
    'expressive', 40
  ),
  (
    'ca26_19_april_geometry', 'ca26_19_avatar_reflection_umbrella', 'avatar', 'cosmetic',
    'Метод тыка', 'Крякс исследует лужу способом, который сложно оспорить.', 'common', 100,
    'gears', 'ca26_19_avatar_reflection_umbrella', 'avatar_v4_duck', 'duck',
    'static', 10
  ),
  (
    'ca26_19_april_geometry', 'ca26_19_frame_water_ripples', 'frame', 'cosmetic',
    'Круги на воде', 'Полупрозрачные водяные кольца расходятся с разной амплитудой.', 'epic', 180,
    'gears', 'ca26_19_frame_water_ripples', 'frame_v4_ripple', 'ripple',
    'subtle', 20
  ),
  (
    'ca26_19_april_geometry', 'ca26_19_title_reflection_researcher', 'title', 'cosmetic',
    'Методом тыка', 'Легендарный титул иногда выбирает случайный символ.', 'legendary', 320,
    'gears', 'ca26_19_title_reflection_researcher', 'title_v4_19_glitch', 'glitch',
    'expressive', 30
  ),
  (
    'ca26_19_april_geometry', 'ca26_19_background_april_reflections', 'background', 'cosmetic',
    'Город в луже', 'Перевёрнутые дома и неон в отражении воды.', 'rare', 140,
    'gears', 'ca26_19_background_april_reflections', 'scene_v4_puddle_city', 'puddle_city',
    'static', 40
  ),
  (
    'ca26_20_may_spring', 'ca26_20_avatar_may_branch', 'avatar', 'cosmetic',
    'Локальный дождь', 'Миро отвечает за погоду в радиусе одного рабочего стола.', 'epic', 180,
    'gears', 'ca26_20_avatar_may_branch', 'avatar_v4_cloud', 'cloud',
    'subtle', 10
  ),
  (
    'ca26_20_may_spring', 'ca26_20_frame_may_light', 'frame', 'cosmetic',
    'Погодный цикл', 'Широкий обод меняется от тёплого солнечного стекла к холодному дождевому.', 'legendary', 320,
    'gears', 'ca26_20_frame_may_light', 'frame_v4_weather_loop', 'weather_loop',
    'expressive', 20
  ),
  (
    'ca26_20_may_spring', 'ca26_20_title_may_landmark', 'title', 'cosmetic',
    'Локальный дождь', 'Редкий холодный текст.', 'rare', 140,
    'gears', 'ca26_20_title_may_landmark', 'title_v4_20_mono', 'mono',
    'static', 30
  ),
  (
    'ca26_20_may_spring', 'ca26_20_background_bright_may', 'background', 'cosmetic',
    'Погодная комната', 'Карты давления, радар и локальное облако.', 'common', 100,
    'gears', 'ca26_20_background_bright_may', 'scene_v4_weather_room', 'weather_room',
    'static', 40
  ),
  (
    'ca26_21_last_bell', 'ca26_21_avatar_school_bell', 'avatar', 'cosmetic',
    'Вышел первым', 'Урок закончился, и Дзынь покинул помещение раньше остальных.', 'legendary', 320,
    'gears', 'ca26_21_avatar_school_bell', 'avatar_v4_bell', 'bell',
    'expressive', 10
  ),
  (
    'ca26_21_last_bell', 'ca26_21_frame_final_ribbon', 'frame', 'cosmetic',
    'После звонка', 'Мягкая нашивка из синей ткани прошита заметной янтарной строчкой.', 'rare', 140,
    'gears', 'ca26_21_frame_final_ribbon', 'frame_v4_afterbell', 'afterbell',
    'static', 20
  ),
  (
    'ca26_21_last_bell', 'ca26_21_title_year_finisher', 'title', 'cosmetic',
    'Сдал и вышел', 'Прямой титул без эффектов.', 'common', 100,
    'gears', 'ca26_21_title_year_finisher', 'title_v4_21_plain', 'plain',
    'static', 30
  ),
  (
    'ca26_21_last_bell', 'ca26_21_background_classroom_results', 'background', 'cosmetic',
    'Пустой класс', 'Стулья, пыль и длинный свет после последнего звонка.', 'epic', 180,
    'gears', 'ca26_21_background_classroom_results', 'scene_v4_empty_class', 'empty_class',
    'subtle', 40
  ),
  (
    'ca26_22_exam_sprint', 'ca26_22_avatar_solution_timer', 'avatar', 'cosmetic',
    'Загрузка 2%', 'Процессор показывает прогресс, не раскрывая оставшееся время.', 'rare', 140,
    'gears', 'ca26_22_avatar_solution_timer', 'avatar_v4_brain', 'brain',
    'static', 10
  ),
  (
    'ca26_22_exam_sprint', 'ca26_22_frame_timer_markings', 'frame', 'cosmetic',
    'Полоса загрузки', 'Полупрозрачный гелевый индикатор оставляет один намеренный разрыв.', 'common', 100,
    'gears', 'ca26_22_frame_timer_markings', 'frame_v4_loading', 'loading',
    'static', 20
  ),
  (
    'ca26_22_exam_sprint', 'ca26_22_title_exam_strategist', 'title', 'cosmetic',
    'Ответ почти готов', 'Эпическая строка загружается до двух процентов.', 'epic', 180,
    'gears', 'ca26_22_title_exam_strategist', 'title_v4_22_pulse', 'pulse',
    'subtle', 30
  ),
  (
    'ca26_22_exam_sprint', 'ca26_22_background_calm_exam', 'background', 'cosmetic',
    'Экзаменационный терминал', 'Стол под камерой и мигающий индикатор готовности.', 'legendary', 320,
    'gears', 'ca26_22_background_calm_exam', 'scene_v4_exam_terminal', 'exam_terminal',
    'expressive', 40
  ),
  (
    'ca26_23_beginning_of_summer', 'ca26_23_avatar_summer_backpack', 'avatar', 'cosmetic',
    'Уже в отпуске', 'Рюкзак мысленно уехал к морю за неделю до расписания.', 'common', 100,
    'gears', 'ca26_23_avatar_summer_backpack', 'avatar_v4_backpack', 'backpack',
    'static', 10
  ),
  (
    'ca26_23_beginning_of_summer', 'ca26_23_frame_summer_window', 'frame', 'cosmetic',
    'Летний выход', 'Морской браслет собран из коралловых бусин, бирюзы и зелёных листьев.', 'epic', 180,
    'gears', 'ca26_23_frame_summer_window', 'frame_v4_summer_exit', 'summer_exit',
    'subtle', 20
  ),
  (
    'ca26_23_beginning_of_summer', 'ca26_23_title_summer_opener', 'title', 'cosmetic',
    'Официально свободен', 'Легендарный финальный титул открывает летний канал.', 'legendary', 320,
    'gears', 'ca26_23_title_summer_opener', 'title_v4_23_signal', 'signal',
    'expressive', 30
  ),
  (
    'ca26_23_beginning_of_summer', 'ca26_23_background_open_summer', 'background', 'cosmetic',
    'Поезд к морю', 'Окно вагона, быстрое поле и первая полоска воды.', 'rare', 140,
    'gears', 'ca26_23_background_open_summer', 'scene_v4_summer_train', 'summer_train',
    'static', 40
  )
on conflict (preset_code, item_code) do update set
  slot = excluded.slot,
  item_kind = excluded.item_kind,
  name = excluded.name,
  description = excluded.description,
  rarity = excluded.rarity,
  price = excluded.price,
  currency = excluded.currency,
  asset_key = excluded.asset_key,
  render_payload = excluded.render_payload,
  visual_key = excluded.visual_key,
  motion_policy = excluded.motion_policy,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.shop_items(
  item_code, name, item_kind, slot, price, availability, rotation_bundle, render_payload,
  sort_order, active, description, rarity, currency, asset_key, visual_key, motion_policy,
  preset_code)
values
  (
    'ca26_01_avatar_field_notebook', 'Режим энергосбережения', 'cosmetic', 'avatar',
    300, 'rotation', 2601, 'avatar_v4_capybara',
    10, false, 'Капибара сохраняет спокойствие, даже когда календарь уже нет.', 'legendary',
    'gears', 'ca26_01_avatar_field_notebook', 'capybara', 'expressive',
    'ca26_01_summer_practice'
  ),
  (
    'ca26_01_frame_sun_route', 'Солнечный маршрут', 'cosmetic', 'frame',
    130, 'rotation', 2601, 'frame_v4_sun_route',
    20, false, 'Тёплый плетёный шнур, сквозь который проходит холодная бирюзовая жила.', 'rare',
    'gears', 'ca26_01_frame_sun_route', 'sun_route', 'static',
    'ca26_01_summer_practice'
  ),
  (
    'ca26_01_title_field_researcher', 'Почти занимаюсь', 'cosmetic', 'title',
    90, 'rotation', 2601, 'title_v4_01_plain',
    30, false, 'Спокойный титул без эффектов.', 'common',
    'gears', 'ca26_01_title_field_researcher', 'plain', 'static',
    'ca26_01_summer_practice'
  ),
  (
    'ca26_01_background_summer_notes', 'Полевые заметки', 'cosmetic', 'background',
    170, 'rotation', 2601, 'scene_v4_field_notes',
    40, false, 'Солнечный стол у воды, снятый сверху.', 'epic',
    'gears', 'ca26_01_background_summer_notes', 'field_notes', 'subtle',
    'ca26_01_summer_practice'
  ),
  (
    'ca26_02_avatar_paper_planner', 'Нулевой заряд', 'cosmetic', 'avatar',
    130, 'rotation', 2602, 'avatar_v4_hamster',
    10, true, 'Хомяк собрал всё необходимое и потратил заряд ещё до старта.', 'rare',
    'gears', 'ca26_02_avatar_paper_planner', 'hamster', 'static',
    'ca26_02_before_start'
  ),
  (
    'ca26_02_frame_checkpoint_flight', 'Бумажный след', 'cosmetic', 'frame',
    90, 'rotation', 2602, 'frame_v4_paper_trace',
    20, true, 'Мягкий рваный край бумаги удерживает непрерывная графитовая нить.', 'common',
    'gears', 'ca26_02_frame_checkpoint_flight', 'paper_trace', 'static',
    'ca26_02_before_start'
  ),
  (
    'ca26_02_title_ready_to_start', 'План был', 'cosmetic', 'title',
    170, 'rotation', 2602, 'title_v4_02_pulse',
    30, true, 'Мягкий градиент для хорошего, но изменившегося плана.', 'epic',
    'gears', 'ca26_02_title_ready_to_start', 'pulse', 'subtle',
    'ca26_02_before_start'
  ),
  (
    'ca26_02_background_august_plan', 'Пол комнаты', 'cosmetic', 'background',
    300, 'rotation', 2602, 'scene_v4_packing_floor',
    40, true, 'Рюкзак, кабели и вещи перед стартом года.', 'legendary',
    'gears', 'ca26_02_background_august_plan', 'packing_floor', 'expressive',
    'ca26_02_before_start'
  ),
  (
    'ca26_03_avatar_route_notebook', 'Неверный корпус', 'cosmetic', 'avatar',
    100, 'rotation', 2603, 'avatar_v4_alien',
    10, true, 'Бип снова вошёл не в ту дверь, но делает вид, что так и надо.', 'common',
    'gears', 'ca26_03_avatar_route_notebook', 'alien', 'static',
    'ca26_03_new_route'
  ),
  (
    'ca26_03_frame_start_line', 'Неверный поворот', 'cosmetic', 'frame',
    180, 'rotation', 2603, 'frame_v4_wrong_turn',
    20, true, 'Три гибких неоновых кабеля пересекаются и собираются в один узел.', 'epic',
    'gears', 'ca26_03_frame_start_line', 'wrong_turn', 'subtle',
    'ca26_03_new_route'
  ),
  (
    'ca26_03_title_route_author', 'Не туда, но вовремя', 'cosmetic', 'title',
    320, 'rotation', 2603, 'title_v4_03_signal',
    30, true, 'Легендарный титул иногда сбивается на координаты.', 'legendary',
    'gears', 'ca26_03_title_route_author', 'signal', 'expressive',
    'ca26_03_new_route'
  ),
  (
    'ca26_03_background_new_path_map', 'Коридор Б-0', 'cosmetic', 'background',
    140, 'rotation', 2603, 'scene_v4_wrong_corridor',
    40, true, 'Школьный коридор с невозможной точкой схода.', 'rare',
    'gears', 'ca26_03_background_new_path_map', 'wrong_corridor', 'static',
    'ca26_03_new_route'
  ),
  (
    'ca26_04_avatar_autumn_planner', 'Вне расписания', 'cosmetic', 'avatar',
    180, 'rotation', 2604, 'avatar_v4_schedule_cat',
    10, true, 'Кот использует расписание исключительно как поверхность для сна.', 'epic',
    'gears', 'ca26_04_avatar_autumn_planner', 'schedule_cat', 'subtle',
    'ca26_04_autumn_start'
  ),
  (
    'ca26_04_frame_autumn_rhythm', 'Осенний импульс', 'cosmetic', 'frame',
    320, 'rotation', 2604, 'frame_v4_autumn_orbit',
    20, true, 'Живой венок из крупных янтарных, красных и зелёных листьев.', 'legendary',
    'gears', 'ca26_04_frame_autumn_rhythm', 'autumn_orbit', 'expressive',
    'ca26_04_autumn_start'
  ),
  (
    'ca26_04_title_order_keeper', 'Вне расписания', 'cosmetic', 'title',
    140, 'rotation', 2604, 'title_v4_04_mono',
    30, true, 'Сдержанный моноширинный статус.', 'rare',
    'gears', 'ca26_04_title_order_keeper', 'mono', 'static',
    'ca26_04_autumn_start'
  ),
  (
    'ca26_04_background_autumn_schedule', 'Стол вне расписания', 'cosmetic', 'background',
    100, 'rotation', 2604, 'scene_v4_schedule_desk',
    40, true, 'Календарь, тени жалюзи и смятый лист.', 'common',
    'gears', 'ca26_04_background_autumn_schedule', 'schedule_desk', 'static',
    'ca26_04_autumn_start'
  ),
  (
    'ca26_05_avatar_symmetry_leaf', 'Протокол симметрии', 'cosmetic', 'avatar',
    320, 'rotation', 2605, 'avatar_v4_raccoon',
    10, true, 'Енот проверяет мир линейкой и находит подозрительно ровные совпадения.', 'legendary',
    'gears', 'ca26_05_avatar_symmetry_leaf', 'raccoon', 'expressive',
    'ca26_05_leaf_geometry'
  ),
  (
    'ca26_05_frame_leaf_symmetry', 'Четыре оси', 'cosmetic', 'frame',
    140, 'rotation', 2605, 'frame_v4_axis',
    20, true, 'Цельный безель из потемневшей латуни с холодным внутренним кантом.', 'rare',
    'gears', 'ca26_05_frame_leaf_symmetry', 'axis', 'static',
    'ca26_05_leaf_geometry'
  ),
  (
    'ca26_05_title_symmetry_master', 'Сходится по осям', 'cosmetic', 'title',
    100, 'rotation', 2605, 'title_v4_05_plain',
    30, true, 'Короткий спокойный титул.', 'common',
    'gears', 'ca26_05_title_symmetry_master', 'plain', 'static',
    'ca26_05_leaf_geometry'
  ),
  (
    'ca26_05_background_leaf_fall_symmetry', 'Осенний переход', 'cosmetic', 'background',
    180, 'rotation', 2605, 'scene_v4_autumn_crosswalk',
    40, true, 'Мокрая улица, разметка и листья под ногами.', 'epic',
    'gears', 'ca26_05_background_leaf_fall_symmetry', 'autumn_crosswalk', 'subtle',
    'ca26_05_leaf_geometry'
  ),
  (
    'ca26_06_avatar_window_lamp', 'Дедлайн 23:59', 'cosmetic', 'avatar',
    140, 'rotation', 2606, 'avatar_v4_frog',
    10, true, 'Ква сохраняет невозмутимость за минуту до отправки.', 'rare',
    'gears', 'ca26_06_avatar_window_lamp', 'frog', 'static',
    'ca26_06_rainy_tasks'
  ),
  (
    'ca26_06_frame_rain_arcs', 'Дождевая линия', 'cosmetic', 'frame',
    100, 'rotation', 2606, 'frame_v4_rainline',
    20, true, 'Прозрачная водяная трубка, на которой держатся крупные капли.', 'common',
    'gears', 'ca26_06_frame_rain_arcs', 'rainline', 'static',
    'ca26_06_rainy_tasks'
  ),
  (
    'ca26_06_title_task_solver', 'Сейчас всё решу', 'cosmetic', 'title',
    180, 'rotation', 2606, 'title_v4_06_pulse',
    30, true, 'Эпический текст едва заметно набирает яркость.', 'epic',
    'gears', 'ca26_06_title_task_solver', 'pulse', 'subtle',
    'ca26_06_rainy_tasks'
  ),
  (
    'ca26_06_background_rain_at_window', 'Остановка под дождём', 'cosmetic', 'background',
    320, 'rotation', 2606, 'scene_v4_rain_shelter',
    40, true, 'Стекло павильона и отражения позднего автобуса.', 'legendary',
    'gears', 'ca26_06_background_rain_at_window', 'rain_shelter', 'expressive',
    'ca26_06_rainy_tasks'
  ),
  (
    'ca26_07_avatar_connection_map', 'Сообщение доставлено', 'cosmetic', 'avatar',
    100, 'rotation', 2607, 'avatar_v4_pigeon',
    10, true, 'Шифр доставил записку. Адрес выбирался интуитивно.', 'common',
    'gears', 'ca26_07_avatar_connection_map', 'pigeon', 'static',
    'ca26_07_connection_points'
  ),
  (
    'ca26_07_frame_team_nodes', 'Потерянное письмо', 'cosmetic', 'frame',
    180, 'rotation', 2607, 'frame_v4_dead_letter',
    20, true, 'Почтовая окантовка из красных, молочных и синих бумажных полос.', 'epic',
    'gears', 'ca26_07_frame_team_nodes', 'dead_letter', 'subtle',
    'ca26_07_connection_points'
  ),
  (
    'ca26_07_title_linking_point', 'Доставлено без адреса', 'cosmetic', 'title',
    320, 'rotation', 2607, 'title_v4_07_signal',
    30, true, 'Легендарный статус оставляет короткий след отправки.', 'legendary',
    'gears', 'ca26_07_title_linking_point', 'signal', 'expressive',
    'ca26_07_connection_points'
  ),
  (
    'ca26_07_background_late_autumn_map', 'Двор на частоте', 'cosmetic', 'background',
    140, 'rotation', 2607, 'scene_v4_courtyard_radio',
    40, true, 'Школьный двор, провода и самодельная антенна.', 'rare',
    'gears', 'ca26_07_background_late_autumn_map', 'courtyard_radio', 'static',
    'ca26_07_connection_points'
  ),
  (
    'ca26_08_avatar_warm_window', 'Ночная смена', 'cosmetic', 'avatar',
    180, 'rotation', 2608, 'avatar_v4_moth',
    10, true, 'Люмен включается только после того, как остальные выключили свет.', 'epic',
    'gears', 'ca26_08_avatar_warm_window', 'moth', 'subtle',
    'ca26_08_light_in_window'
  ),
  (
    'ca26_08_frame_lamp_light', 'Последний свет', 'cosmetic', 'frame',
    320, 'rotation', 2608, 'frame_v4_last_light',
    20, true, 'Широкий витражный обод собирает фиолетовый сумрак и янтарный свет.', 'legendary',
    'gears', 'ca26_08_frame_lamp_light', 'last_light', 'expressive',
    'ca26_08_light_in_window'
  ),
  (
    'ca26_08_title_bright_idea', 'Последний свет', 'cosmetic', 'title',
    140, 'rotation', 2608, 'title_v4_08_mono',
    30, true, 'Холодная подпись без движения.', 'rare',
    'gears', 'ca26_08_title_bright_idea', 'mono', 'static',
    'ca26_08_light_in_window'
  ),
  (
    'ca26_08_background_evening_notebook', 'Окно после полуночи', 'cosmetic', 'background',
    100, 'rotation', 2608, 'scene_v4_night_window',
    40, true, 'Тёмная комната и единственная включённая лампа.', 'common',
    'gears', 'ca26_08_background_evening_notebook', 'night_window', 'static',
    'ca26_08_light_in_window'
  ),
  (
    'ca26_09_avatar_snow_crystal', 'Не тает', 'cosmetic', 'avatar',
    320, 'rotation', 2609, 'avatar_v4_snow_blob',
    10, true, 'Шурх пережил контрольную, оттепель и чужой прогноз.', 'legendary',
    'gears', 'ca26_09_avatar_snow_crystal', 'snow_blob', 'expressive',
    'ca26_09_first_snow'
  ),
  (
    'ca26_09_frame_first_crystal', 'Холодный статик', 'cosmetic', 'frame',
    140, 'rotation', 2609, 'frame_v4_cold_static',
    20, true, 'Кристаллическая корона с острыми ледяными помехами.', 'rare',
    'gears', 'ca26_09_frame_first_crystal', 'cold_static', 'static',
    'ca26_09_first_snow'
  ),
  (
    'ca26_09_title_winter_guide', 'Не растаял', 'cosmetic', 'title',
    100, 'rotation', 2609, 'title_v4_09_plain',
    30, true, 'Статичный зимний титул.', 'common',
    'gears', 'ca26_09_title_winter_guide', 'plain', 'static',
    'ca26_09_first_snow'
  ),
  (
    'ca26_09_background_first_snowfall', 'Белый двор', 'cosmetic', 'background',
    180, 'rotation', 2609, 'scene_v4_snow_yard',
    40, true, 'Знакомый двор, почти исчезнувший под снегом.', 'epic',
    'gears', 'ca26_09_background_first_snowfall', 'snow_yard', 'subtle',
    'ca26_09_first_snow'
  ),
  (
    'ca26_10_avatar_december_clock', 'Ещё пять минут', 'cosmetic', 'avatar',
    140, 'rotation', 2610, 'avatar_v4_clock',
    10, true, 'Тик переносит будильник с профессиональной точностью.', 'rare',
    'gears', 'ca26_10_avatar_december_clock', 'clock', 'static',
    'ca26_10_pre_new_year_countdown'
  ),
  (
    'ca26_10_frame_countdown_ring', 'Обратный отсчёт', 'cosmetic', 'frame',
    100, 'rotation', 2610, 'frame_v4_countdown',
    20, true, 'Мягкий красный безель таймера стянут тонкой жёлтой разметкой.', 'common',
    'gears', 'ca26_10_frame_countdown_ring', 'countdown', 'static',
    'ca26_10_pre_new_year_countdown'
  ),
  (
    'ca26_10_title_countdown_master', 'Ещё пять минут', 'cosmetic', 'title',
    180, 'rotation', 2610, 'title_v4_10_pulse',
    30, true, 'Индикатор времени проходит по буквам.', 'epic',
    'gears', 'ca26_10_title_countdown_master', 'pulse', 'subtle',
    'ca26_10_pre_new_year_countdown'
  ),
  (
    'ca26_10_background_december_countdown', 'Комната 00:05', 'cosmetic', 'background',
    320, 'rotation', 2610, 'scene_v4_countdown_room',
    40, true, 'Красные цифры и тени перед дедлайном.', 'legendary',
    'gears', 'ca26_10_background_december_countdown', 'countdown_room', 'expressive',
    'ca26_10_pre_new_year_countdown'
  ),
  (
    'ca26_11_avatar_holiday_workshop', 'Архив.zip', 'cosmetic', 'avatar',
    100, 'rotation', 2611, 'avatar_v4_gift',
    10, true, 'Упаковывает незакрытые задачи в папку, которую никто не откроет.', 'common',
    'gears', 'ca26_11_avatar_holiday_workshop', 'gift', 'static',
    'ca26_11_new_year_workshop'
  ),
  (
    'ca26_11_frame_festive_garland', 'Гирлянда 00:00', 'cosmetic', 'frame',
    180, 'rotation', 2611, 'frame_v4_new_year_lights',
    20, true, 'Хвойное плетение с небольшими разноцветными лампочками и мягким праздничным свечением.', 'epic',
    'gears', 'ca26_11_frame_festive_garland', 'new_year_lights', 'subtle',
    'ca26_11_new_year_workshop'
  ),
  (
    'ca26_11_title_new_year_master', 'Архив закрыт', 'cosmetic', 'title',
    320, 'rotation', 2611, 'title_v4_11_glitch',
    30, true, 'Легендарный титул на мгновение показывает системный код.', 'legendary',
    'gears', 'ca26_11_title_new_year_master', 'glitch', 'expressive',
    'ca26_11_new_year_workshop'
  ),
  (
    'ca26_11_background_festive_workshop', 'Закрытый архив', 'cosmetic', 'background',
    140, 'rotation', 2611, 'scene_v4_archive_room',
    40, true, 'Полки, коробки и свет дежурной лампы.', 'rare',
    'gears', 'ca26_11_background_festive_workshop', 'archive_room', 'static',
    'ca26_11_new_year_workshop'
  ),
  (
    'ca26_12_avatar_frost_window', 'Слабый сигнал', 'cosmetic', 'avatar',
    180, 'rotation', 2612, 'avatar_v4_frozen_alien',
    10, true, 'Одна антенна ловит связь, вторая всё ещё загружается.', 'epic',
    'gears', 'ca26_12_avatar_frost_window', 'frozen_alien', 'subtle',
    'ca26_12_frosty_start'
  ),
  (
    'ca26_12_frame_frost_pattern', 'Слабая частота', 'cosmetic', 'frame',
    320, 'rotation', 2612, 'frame_v4_weak_signal',
    20, true, 'Спутанный пучок проводов: две жилы светятся, две остаются холодными.', 'legendary',
    'gears', 'ca26_12_frame_frost_pattern', 'weak_signal', 'expressive',
    'ca26_12_frosty_start'
  ),
  (
    'ca26_12_title_frost_endurance', 'Сигнал нестабилен', 'cosmetic', 'title',
    140, 'rotation', 2612, 'title_v4_12_mono',
    30, true, 'Редкая подпись с техническим ритмом.', 'rare',
    'gears', 'ca26_12_title_frost_endurance', 'mono', 'static',
    'ca26_12_frosty_start'
  ),
  (
    'ca26_12_background_frosty_morning', 'Замёрзшее стекло', 'cosmetic', 'background',
    100, 'rotation', 2612, 'scene_v4_frosted_stop',
    40, true, 'Остановка видна только через очищенный участок.', 'common',
    'gears', 'ca26_12_background_frosty_morning', 'frosted_stop', 'static',
    'ca26_12_frosty_start'
  ),
  (
    'ca26_13_avatar_clean_page', 'Ошибка на полях', 'cosmetic', 'avatar',
    320, 'rotation', 2613, 'avatar_v4_ink_blob',
    10, true, 'Клякса появилась случайно и быстро стала главным элементом страницы.', 'legendary',
    'gears', 'ca26_13_avatar_clean_page', 'ink_blob', 'expressive',
    'ca26_13_clean_sheet'
  ),
  (
    'ca26_13_frame_notebook_margins', 'Поля документа', 'cosmetic', 'frame',
    140, 'rotation', 2613, 'frame_v4_margin_error',
    20, true, 'Рваное бумажное волокно перехвачено синей строчкой и красной линией.', 'rare',
    'gears', 'ca26_13_frame_notebook_margins', 'margin_error', 'static',
    'ca26_13_clean_sheet'
  ),
  (
    'ca26_13_title_page_author', 'Начну с точки', 'cosmetic', 'title',
    100, 'rotation', 2613, 'title_v4_13_plain',
    30, true, 'Минимальный титул без анимации.', 'common',
    'gears', 'ca26_13_title_page_author', 'plain', 'static',
    'ca26_13_clean_sheet'
  ),
  (
    'ca26_13_background_white_page', 'Бумажное пространство', 'cosmetic', 'background',
    180, 'rotation', 2613, 'scene_v4_paper_space',
    40, true, 'Листы, скотч и чернильные следы без горизонта.', 'epic',
    'gears', 'ca26_13_background_white_page', 'paper_space', 'subtle',
    'ca26_13_clean_sheet'
  ),
  (
    'ca26_14_avatar_study_metronome', 'Восемь вкладок', 'cosmetic', 'avatar',
    140, 'rotation', 2614, 'avatar_v4_octopus',
    10, true, 'Семь дел открыты. Восьмое уверенно воспроизводит музыку.', 'rare',
    'gears', 'ca26_14_avatar_study_metronome', 'octopus', 'static',
    'ca26_14_february_rhythm'
  ),
  (
    'ca26_14_frame_week_rhythm', 'Многооконный режим', 'cosmetic', 'frame',
    100, 'rotation', 2614, 'frame_v4_multitask',
    20, true, 'Три полупрозрачных окна наложились друг на друга и потеряли правильную форму.', 'common',
    'gears', 'ca26_14_frame_week_rhythm', 'multitask', 'static',
    'ca26_14_february_rhythm'
  ),
  (
    'ca26_14_title_rhythm_keeper', 'Восемь вкладок', 'cosmetic', 'title',
    180, 'rotation', 2614, 'title_v4_14_pulse',
    30, true, 'Эпическая смена оттенка между активными задачами.', 'epic',
    'gears', 'ca26_14_title_rhythm_keeper', 'pulse', 'subtle',
    'ca26_14_february_rhythm'
  ),
  (
    'ca26_14_background_winter_schedule', 'Перегрузка вкладок', 'cosmetic', 'background',
    320, 'rotation', 2614, 'scene_v4_tab_overload',
    40, true, 'Рабочий стол, окна и уведомления поверх друг друга.', 'legendary',
    'gears', 'ca26_14_background_winter_schedule', 'tab_overload', 'expressive',
    'ca26_14_february_rhythm'
  ),
  (
    'ca26_15_avatar_support_point', 'Ещё попытка', 'cosmetic', 'avatar',
    100, 'rotation', 2615, 'avatar_v4_beetle',
    10, true, 'Тягач снова идёт вверх, не обсуждая прошлый результат.', 'common',
    'gears', 'ca26_15_avatar_support_point', 'beetle', 'static',
    'ca26_15_strength_of_character'
  ),
  (
    'ca26_15_frame_resilience_contour', 'Повтор', 'cosmetic', 'frame',
    180, 'rotation', 2615, 'frame_v4_retry',
    20, true, 'Плотно переплетённый шнур возвращает узор к началу.', 'epic',
    'gears', 'ca26_15_frame_resilience_contour', 'retry', 'subtle',
    'ca26_15_strength_of_character'
  ),
  (
    'ca26_15_title_reliable_support', 'Ещё один шаг', 'cosmetic', 'title',
    320, 'rotation', 2615, 'title_v4_15_signal',
    30, true, 'Легендарная строка продвигает световой маркер вперёд.', 'legendary',
    'gears', 'ca26_15_title_reliable_support', 'signal', 'expressive',
    'ca26_15_strength_of_character'
  ),
  (
    'ca26_15_background_resilience_line', 'Наклонная страница', 'cosmetic', 'background',
    140, 'rotation', 2615, 'scene_v4_notebook_slope',
    40, true, 'Тетрадный лист превращается в крутой подъём.', 'rare',
    'gears', 'ca26_15_background_resilience_line', 'notebook_slope', 'static',
    'ca26_15_strength_of_character'
  ),
  (
    'ca26_16_avatar_spring_sprout', 'Новый рост', 'cosmetic', 'avatar',
    180, 'rotation', 2616, 'avatar_v4_sprout',
    10, true, 'Пиксель вышел за границы рисунка и отказался возвращаться.', 'epic',
    'gears', 'ca26_16_avatar_spring_sprout', 'sprout', 'subtle',
    'ca26_16_spring_inspiration'
  ),
  (
    'ca26_16_frame_growth_lines', 'Хлорофилл', 'cosmetic', 'frame',
    320, 'rotation', 2616, 'frame_v4_chlorophyll',
    20, true, 'Плетёная лоза с крупными цветами, листьями и мягким зелёным свечением.', 'legendary',
    'gears', 'ca26_16_frame_growth_lines', 'chlorophyll', 'expressive',
    'ca26_16_spring_inspiration'
  ),
  (
    'ca26_16_title_source_of_ideas', 'Есть идея', 'cosmetic', 'title',
    140, 'rotation', 2616, 'title_v4_16_mono',
    30, true, 'Короткий редкий титул.', 'rare',
    'gears', 'ca26_16_title_source_of_ideas', 'mono', 'static',
    'ca26_16_spring_inspiration'
  ),
  (
    'ca26_16_background_spring_light', 'Весенняя мастерская', 'cosmetic', 'background',
    100, 'rotation', 2616, 'scene_v4_spring_workshop',
    40, true, 'Растения, банки с водой и холодный дневной свет.', 'common',
    'gears', 'ca26_16_background_spring_light', 'spring_workshop', 'static',
    'ca26_16_spring_inspiration'
  ),
  (
    'ca26_17_avatar_balance_disc', 'Держится', 'cosmetic', 'avatar',
    320, 'rotation', 2617, 'avatar_v4_balance_cat',
    10, true, 'Полка уже накренилась, но Баланс сохраняет выражение лица.', 'legendary',
    'gears', 'ca26_17_avatar_balance_disc', 'balance_cat', 'expressive',
    'ca26_17_balance_point'
  ),
  (
    'ca26_17_frame_balance_circle', 'Точка равновесия', 'cosmetic', 'frame',
    140, 'rotation', 2617, 'frame_v4_balance',
    20, true, 'Цельный обод разделён между холодной керамикой и тёплым деревом.', 'rare',
    'gears', 'ca26_17_frame_balance_circle', 'balance', 'static',
    'ca26_17_balance_point'
  ),
  (
    'ca26_17_title_balance_keeper', 'Держу баланс', 'cosmetic', 'title',
    100, 'rotation', 2617, 'title_v4_17_plain',
    30, true, 'Статичный статус без декоративного шума.', 'common',
    'gears', 'ca26_17_title_balance_keeper', 'plain', 'static',
    'ca26_17_balance_point'
  ),
  (
    'ca26_17_background_equinox_day', 'Наклонная библиотека', 'cosmetic', 'background',
    180, 'rotation', 2617, 'scene_v4_leaning_library',
    40, true, 'Стеллажи уходят в сторону, сохраняя порядок.', 'epic',
    'gears', 'ca26_17_background_equinox_day', 'leaning_library', 'subtle',
    'ca26_17_balance_point'
  ),
  (
    'ca26_18_avatar_launch_researcher', 'Турист с Альфы-7', 'cosmetic', 'avatar',
    140, 'rotation', 2618, 'avatar_v4_space_tourist',
    10, true, 'Перепутал школьный двор с космодромом и решил остаться.', 'rare',
    'gears', 'ca26_18_avatar_launch_researcher', 'space_tourist', 'static',
    'ca26_18_time_of_firsts'
  ),
  (
    'ca26_18_frame_launch_trajectory', 'Маршрут Альфы', 'cosmetic', 'frame',
    100, 'rotation', 2618, 'frame_v4_alpha_route',
    20, true, 'Три тонких эластичных шнура оборачиваются вокруг аватара по разным траекториям.', 'common',
    'gears', 'ca26_18_frame_launch_trajectory', 'alpha_route', 'static',
    'ca26_18_time_of_firsts'
  ),
  (
    'ca26_18_title_one_step_ahead', 'Первый пошёл', 'cosmetic', 'title',
    180, 'rotation', 2618, 'title_v4_18_pulse',
    30, true, 'Эпический стартовый импульс.', 'epic',
    'gears', 'ca26_18_title_one_step_ahead', 'pulse', 'subtle',
    'ca26_18_time_of_firsts'
  ),
  (
    'ca26_18_background_academy_launch', 'Альфа-7', 'cosmetic', 'background',
    320, 'rotation', 2618, 'scene_v4_orbital',
    40, true, 'Орбита, холодный свет и чужая геометрия.', 'legendary',
    'gears', 'ca26_18_background_academy_launch', 'orbital', 'expressive',
    'ca26_18_time_of_firsts'
  ),
  (
    'ca26_19_avatar_reflection_umbrella', 'Метод тыка', 'cosmetic', 'avatar',
    100, 'rotation', 2619, 'avatar_v4_duck',
    10, true, 'Крякс исследует лужу способом, который сложно оспорить.', 'common',
    'gears', 'ca26_19_avatar_reflection_umbrella', 'duck', 'static',
    'ca26_19_april_geometry'
  ),
  (
    'ca26_19_frame_water_ripples', 'Круги на воде', 'cosmetic', 'frame',
    180, 'rotation', 2619, 'frame_v4_ripple',
    20, true, 'Полупрозрачные водяные кольца расходятся с разной амплитудой.', 'epic',
    'gears', 'ca26_19_frame_water_ripples', 'ripple', 'subtle',
    'ca26_19_april_geometry'
  ),
  (
    'ca26_19_title_reflection_researcher', 'Методом тыка', 'cosmetic', 'title',
    320, 'rotation', 2619, 'title_v4_19_glitch',
    30, true, 'Легендарный титул иногда выбирает случайный символ.', 'legendary',
    'gears', 'ca26_19_title_reflection_researcher', 'glitch', 'expressive',
    'ca26_19_april_geometry'
  ),
  (
    'ca26_19_background_april_reflections', 'Город в луже', 'cosmetic', 'background',
    140, 'rotation', 2619, 'scene_v4_puddle_city',
    40, true, 'Перевёрнутые дома и неон в отражении воды.', 'rare',
    'gears', 'ca26_19_background_april_reflections', 'puddle_city', 'static',
    'ca26_19_april_geometry'
  ),
  (
    'ca26_20_avatar_may_branch', 'Локальный дождь', 'cosmetic', 'avatar',
    180, 'rotation', 2620, 'avatar_v4_cloud',
    10, true, 'Миро отвечает за погоду в радиусе одного рабочего стола.', 'epic',
    'gears', 'ca26_20_avatar_may_branch', 'cloud', 'subtle',
    'ca26_20_may_spring'
  ),
  (
    'ca26_20_frame_may_light', 'Погодный цикл', 'cosmetic', 'frame',
    320, 'rotation', 2620, 'frame_v4_weather_loop',
    20, true, 'Широкий обод меняется от тёплого солнечного стекла к холодному дождевому.', 'legendary',
    'gears', 'ca26_20_frame_may_light', 'weather_loop', 'expressive',
    'ca26_20_may_spring'
  ),
  (
    'ca26_20_title_may_landmark', 'Локальный дождь', 'cosmetic', 'title',
    140, 'rotation', 2620, 'title_v4_20_mono',
    30, true, 'Редкий холодный текст.', 'rare',
    'gears', 'ca26_20_title_may_landmark', 'mono', 'static',
    'ca26_20_may_spring'
  ),
  (
    'ca26_20_background_bright_may', 'Погодная комната', 'cosmetic', 'background',
    100, 'rotation', 2620, 'scene_v4_weather_room',
    40, true, 'Карты давления, радар и локальное облако.', 'common',
    'gears', 'ca26_20_background_bright_may', 'weather_room', 'static',
    'ca26_20_may_spring'
  ),
  (
    'ca26_21_avatar_school_bell', 'Вышел первым', 'cosmetic', 'avatar',
    320, 'rotation', 2621, 'avatar_v4_bell',
    10, true, 'Урок закончился, и Дзынь покинул помещение раньше остальных.', 'legendary',
    'gears', 'ca26_21_avatar_school_bell', 'bell', 'expressive',
    'ca26_21_last_bell'
  ),
  (
    'ca26_21_frame_final_ribbon', 'После звонка', 'cosmetic', 'frame',
    140, 'rotation', 2621, 'frame_v4_afterbell',
    20, true, 'Мягкая нашивка из синей ткани прошита заметной янтарной строчкой.', 'rare',
    'gears', 'ca26_21_frame_final_ribbon', 'afterbell', 'static',
    'ca26_21_last_bell'
  ),
  (
    'ca26_21_title_year_finisher', 'Сдал и вышел', 'cosmetic', 'title',
    100, 'rotation', 2621, 'title_v4_21_plain',
    30, true, 'Прямой титул без эффектов.', 'common',
    'gears', 'ca26_21_title_year_finisher', 'plain', 'static',
    'ca26_21_last_bell'
  ),
  (
    'ca26_21_background_classroom_results', 'Пустой класс', 'cosmetic', 'background',
    180, 'rotation', 2621, 'scene_v4_empty_class',
    40, true, 'Стулья, пыль и длинный свет после последнего звонка.', 'epic',
    'gears', 'ca26_21_background_classroom_results', 'empty_class', 'subtle',
    'ca26_21_last_bell'
  ),
  (
    'ca26_22_avatar_solution_timer', 'Загрузка 2%', 'cosmetic', 'avatar',
    140, 'rotation', 2622, 'avatar_v4_brain',
    10, true, 'Процессор показывает прогресс, не раскрывая оставшееся время.', 'rare',
    'gears', 'ca26_22_avatar_solution_timer', 'brain', 'static',
    'ca26_22_exam_sprint'
  ),
  (
    'ca26_22_frame_timer_markings', 'Полоса загрузки', 'cosmetic', 'frame',
    100, 'rotation', 2622, 'frame_v4_loading',
    20, true, 'Полупрозрачный гелевый индикатор оставляет один намеренный разрыв.', 'common',
    'gears', 'ca26_22_frame_timer_markings', 'loading', 'static',
    'ca26_22_exam_sprint'
  ),
  (
    'ca26_22_title_exam_strategist', 'Ответ почти готов', 'cosmetic', 'title',
    180, 'rotation', 2622, 'title_v4_22_pulse',
    30, true, 'Эпическая строка загружается до двух процентов.', 'epic',
    'gears', 'ca26_22_title_exam_strategist', 'pulse', 'subtle',
    'ca26_22_exam_sprint'
  ),
  (
    'ca26_22_background_calm_exam', 'Экзаменационный терминал', 'cosmetic', 'background',
    320, 'rotation', 2622, 'scene_v4_exam_terminal',
    40, true, 'Стол под камерой и мигающий индикатор готовности.', 'legendary',
    'gears', 'ca26_22_background_calm_exam', 'exam_terminal', 'expressive',
    'ca26_22_exam_sprint'
  ),
  (
    'ca26_23_avatar_summer_backpack', 'Уже в отпуске', 'cosmetic', 'avatar',
    100, 'rotation', 2623, 'avatar_v4_backpack',
    10, true, 'Рюкзак мысленно уехал к морю за неделю до расписания.', 'common',
    'gears', 'ca26_23_avatar_summer_backpack', 'backpack', 'static',
    'ca26_23_beginning_of_summer'
  ),
  (
    'ca26_23_frame_summer_window', 'Летний выход', 'cosmetic', 'frame',
    180, 'rotation', 2623, 'frame_v4_summer_exit',
    20, true, 'Морской браслет собран из коралловых бусин, бирюзы и зелёных листьев.', 'epic',
    'gears', 'ca26_23_frame_summer_window', 'summer_exit', 'subtle',
    'ca26_23_beginning_of_summer'
  ),
  (
    'ca26_23_title_summer_opener', 'Официально свободен', 'cosmetic', 'title',
    320, 'rotation', 2623, 'title_v4_23_signal',
    30, true, 'Легендарный финальный титул открывает летний канал.', 'legendary',
    'gears', 'ca26_23_title_summer_opener', 'signal', 'expressive',
    'ca26_23_beginning_of_summer'
  ),
  (
    'ca26_23_background_open_summer', 'Поезд к морю', 'cosmetic', 'background',
    140, 'rotation', 2623, 'scene_v4_summer_train',
    40, true, 'Окно вагона, быстрое поле и первая полоска воды.', 'rare',
    'gears', 'ca26_23_background_open_summer', 'summer_train', 'static',
    'ca26_23_beginning_of_summer'
  )
on conflict (item_code) do update set
  name = excluded.name,
  item_kind = excluded.item_kind,
  slot = excluded.slot,
  price = excluded.price,
  availability = excluded.availability,
  rotation_bundle = excluded.rotation_bundle,
  render_payload = excluded.render_payload,
  sort_order = excluded.sort_order,
  active = excluded.active,
  description = excluded.description,
  rarity = excluded.rarity,
  currency = excluded.currency,
  asset_key = excluded.asset_key,
  visual_key = excluded.visual_key,
  motion_policy = excluded.motion_policy,
  preset_code = excluded.preset_code;

-- Period 01 is intentionally absent from public.seasons and disabled in shop_items.
-- It remains available only through the canonical teacher preview.
do $preflight$
begin
  if exists (
    select 1
      from public.seasons s
     where s.preset_code is null
       and s.status = 'scheduled'
       and s.starts_at is not null
       and s.ends_at is not null
       and tstzrange(s.starts_at, s.ends_at, '[)')
           && tstzrange(
                '2026-08-01 00:00:00 Europe/Moscow'::timestamptz,
                '2027-06-24 00:00:00 Europe/Moscow'::timestamptz,
                '[)')
  ) then
    raise exception 'season_v2_conflicting_legacy_schedule';
  end if;
end
$preflight$;

insert into public.seasons(
  title, description, status, start_date, end_date, starts_at, ends_at,
  preset_code, sequence_no, scheduled_at, updated_at)
select p.suggested_name,
       p.short_description,
       'scheduled',
       p.default_start_date,
       p.default_end_date,
       (p.default_start_date::timestamp at time zone 'Europe/Moscow'),
       (p.default_end_date::timestamp at time zone 'Europe/Moscow'),
       p.preset_code,
       p.sequence_no,
       now(),
       now()
  from public.season_v2_presets p
 where p.sequence_no >= 2
   and not exists (
     select 1 from public.seasons s where s.preset_code = p.preset_code
   )
 order by p.sequence_no;

insert into public.season_v2_plan_items(
  season_id, item_code, name, description, price, render_payload)
select s.id, i.item_code, i.name, i.description, i.price, i.render_payload
  from public.seasons s
  join public.season_v2_preset_items i on i.preset_code = s.preset_code
 where s.sequence_no between 2 and 23
on conflict (season_id, item_code) do nothing;

insert into public.season_bundles(season_id, bundle)
select s.id, 2600 + s.sequence_no
  from public.seasons s
 where s.sequence_no between 2 and 23
on conflict (season_id) do nothing;

commit;
