import { readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const catalog = JSON.parse(
  await readFile(new URL("data/season_presets_2026_2027.json", root), "utf8"),
);

if (catalog.schema_version !== 2 || catalog.catalog_revision !== 4 || catalog.presets?.length !== 23) {
  throw new Error("Season V2 seed requires the approved revision 4 catalog with 23 periods");
}

const sql = (value) => {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return `'${String(value).replaceAll("'", "''")}'`;
};

const presetRows = catalog.presets.map((preset) => `  (
    ${sql(preset.preset_code)}, ${sql(catalog.catalog_code)}, ${catalog.catalog_revision},
    ${preset.sequence_no}, ${sql(preset.competition_season_no)}, ${sql(preset.season_type)},
    ${sql(preset.start_date)}::date, ${sql(preset.end_date)}::date,
    ${sql(preset.suggested_name)}, ${sql(preset.short_description)}, ${sql(preset.theme_key)},
    ${sql(preset.economy_profile)}, ${sql(preset.pricing_status)}, ${sql(preset.collection_code)},
    ${preset.collection_bonus}, ${preset.collection_total_target}, ${preset.sequence_no === 1}
  )`).join(",\n");

const items = catalog.presets.flatMap((preset) =>
  preset.items.map((item) => ({ ...item, preset_code: preset.preset_code, sequence_no: preset.sequence_no })),
);

const itemRows = items.map((item) => `  (
    ${sql(item.preset_code)}, ${sql(item.item_code)}, ${sql(item.slot)}, ${sql(item.item_kind)},
    ${sql(item.name)}, ${sql(item.description)}, ${sql(item.rarity)}, ${item.price},
    ${sql(item.currency)}, ${sql(item.asset_key)}, ${sql(item.render_payload)}, ${sql(item.visual_key)},
    ${sql(item.motion_policy)}, ${item.sort_order}
  )`).join(",\n");

const shopRows = items.map((item) => `  (
    ${sql(item.item_code)}, ${sql(item.name)}, ${sql(item.item_kind)}, ${sql(item.slot)},
    ${item.price}, 'rotation', ${2600 + item.sequence_no}, ${sql(item.render_payload)},
    ${item.sort_order}, ${item.sequence_no !== 1}, ${sql(item.description)}, ${sql(item.rarity)},
    ${sql(item.currency)}, ${sql(item.asset_key)}, ${sql(item.visual_key)}, ${sql(item.motion_policy)},
    ${sql(item.preset_code)}
  )`).join(",\n");

const output = `-- GENERATED by scripts/generate_season_v2_seed.mjs.
-- Canonical source: data/season_presets_2026_2027.json (schema 2, revision 4).
-- Do not hand-edit names, prices, rarity or render_payload in this file.

begin;

insert into public.season_v2_presets(
  preset_code, catalog_code, catalog_revision, sequence_no, competition_season_no,
  season_type, default_start_date, default_end_date, suggested_name, short_description,
  theme_key, economy_profile, pricing_status, collection_code, collection_bonus,
  collection_total_target, catalog_only)
values
${presetRows}
on conflict (preset_code) do update set
  catalog_code = excluded.catalog_code,
  catalog_revision = excluded.catalog_revision,
  sequence_no = excluded.sequence_no,
  competition_season_no = excluded.competition_season_no,
  season_type = excluded.season_type,
  default_start_date = excluded.default_start_date,
  default_end_date = excluded.default_end_date,
  suggested_name = excluded.suggested_name,
  short_description = excluded.short_description,
  theme_key = excluded.theme_key,
  economy_profile = excluded.economy_profile,
  pricing_status = excluded.pricing_status,
  collection_code = excluded.collection_code,
  collection_bonus = excluded.collection_bonus,
  collection_total_target = excluded.collection_total_target,
  catalog_only = excluded.catalog_only,
  updated_at = now();

insert into public.season_v2_preset_items(
  preset_code, item_code, slot, item_kind, name, description, rarity, price, currency,
  asset_key, render_payload, visual_key, motion_policy, sort_order)
values
${itemRows}
on conflict (preset_code, item_code) do update set
  slot = excluded.slot,
  item_kind = excluded.item_kind,
  name = excluded.name,
  description = excluded.description,
  rarity = excluded.rarity,
  price = excluded.price,
  currency = excluded.currency,
  asset_key = excluded.asset_key,
  render_payload = excluded.render_payload,
  visual_key = excluded.visual_key,
  motion_policy = excluded.motion_policy,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.shop_items(
  item_code, name, item_kind, slot, price, availability, rotation_bundle, render_payload,
  sort_order, active, description, rarity, currency, asset_key, visual_key, motion_policy,
  preset_code)
values
${shopRows}
on conflict (item_code) do update set
  name = excluded.name,
  item_kind = excluded.item_kind,
  slot = excluded.slot,
  price = excluded.price,
  availability = excluded.availability,
  rotation_bundle = excluded.rotation_bundle,
  render_payload = excluded.render_payload,
  sort_order = excluded.sort_order,
  active = excluded.active,
  description = excluded.description,
  rarity = excluded.rarity,
  currency = excluded.currency,
  asset_key = excluded.asset_key,
  visual_key = excluded.visual_key,
  motion_policy = excluded.motion_policy,
  preset_code = excluded.preset_code;

-- Period 01 is intentionally absent from public.seasons and disabled in shop_items.
-- It remains available only through the canonical teacher preview.
do $preflight$
begin
  if exists (
    select 1
      from public.seasons s
     where s.preset_code is null
       and s.status = 'scheduled'
       and s.starts_at is not null
       and s.ends_at is not null
       and tstzrange(s.starts_at, s.ends_at, '[)')
           && tstzrange(
                '2026-08-01 00:00:00 Europe/Moscow'::timestamptz,
                '2027-06-24 00:00:00 Europe/Moscow'::timestamptz,
                '[)')
  ) then
    raise exception 'season_v2_conflicting_legacy_schedule';
  end if;
end
$preflight$;

insert into public.seasons(
  title, description, status, start_date, end_date, starts_at, ends_at,
  preset_code, sequence_no, scheduled_at, updated_at)
select p.suggested_name,
       p.short_description,
       'scheduled',
       p.default_start_date,
       p.default_end_date,
       (p.default_start_date::timestamp at time zone 'Europe/Moscow'),
       (p.default_end_date::timestamp at time zone 'Europe/Moscow'),
       p.preset_code,
       p.sequence_no,
       now(),
       now()
  from public.season_v2_presets p
 where p.sequence_no >= 2
   and not exists (
     select 1 from public.seasons s where s.preset_code = p.preset_code
   )
 order by p.sequence_no;

insert into public.season_v2_plan_items(
  season_id, item_code, name, description, price, render_payload)
select s.id, i.item_code, i.name, i.description, i.price, i.render_payload
  from public.seasons s
  join public.season_v2_preset_items i on i.preset_code = s.preset_code
 where s.sequence_no between 2 and 23
on conflict (season_id, item_code) do nothing;

insert into public.season_bundles(season_id, bundle)
select s.id, 2600 + s.sequence_no
  from public.seasons s
 where s.sequence_no between 2 and 23
on conflict (season_id) do nothing;

commit;
`;

const target = new URL("database/migrations/058_season_v2_catalog_seed.sql", root);
await writeFile(target, output, "utf8");
console.log(`Generated ${items.length} items across ${catalog.presets.length} presets.`);
